### ISSUE TITLE
Add support for empty documents

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#1000]
It is possible to pass empty document to command document. One of it's usages as replacement document in update operation.

- [ ] Check for this issue number being mentioned in source code
- [ ] Check that validation function passes such documents
- [ ] Check `findAndModify` command
- [ ] Enable tests

Example: when you pass an empty `bson.D` for update with replacement document, the result we store should be the doc with only `_id` field being set.

**Comment by rumyantseva** [comment]
Estimated as M as we are not 100% sure about the number of things that could need attention.

**Comment by AlekSi** [comment]
That issue is in progress, it has to be assigned to someone
