### ISSUE TITLE
Comparison with unset fields works incorrectly

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1023]
It seems that MongoDB differentiates between null and unset values, but we don't. See #1024.

## potential issues
- when we create filter documents we compare documents fetched from db with a filter given in the update query.
- when fields are not set in document we skip them, but we shouldn't

**Comment by AlekSi** [comment]
@ribaraka will you be interested in fixing that?

**Comment by AlekSi** [comment]
On @rumyantseva to investigate

**Comment by rumyantseva** [comment]
A simpler example:

```
test> db.thingsunset.insertOne({"foo": "bar"});
{
  acknowledged: true,
  insertedId: ObjectId("630c8b397640890b9c9b6d29")
}
test> db.thingsunset.find({"hello": null});
[ { _id: ObjectId("630c8b397640890b9c9b6d29"), foo: 'bar' } ]
```

In this example, `{"hello": null}` found the entry we inserted, but it's wrong. Expected result: nothing should be found.

**Comment by rumyantseva** [comment]
The logic was implemented on purpose - https://github.com/FerretDB/FerretDB/blob/225850381bdf592e698dbac56b9d55e12107dcb8/internal/handlers/common/filter.go#L124 :) 
It was introduced in #456.

**Comment by rumyantseva** [comment]
Results of my investigation:
- Such logic was implemented on purpose (see my comment above).
- Potentially weak place: nested arrays with `nil` values.

**Comment by AlekSi** [comment]
> Such logic was implemented on purpose (see my comment above).

But why?

Do we have enough information to estimate that issue now?

**Comment by rumyantseva** [comment]
@AlekSi kind of. It doesn't look too big (so, it's not L), but personally I stuck with attempt of fixing it and new issues coming because of the fixes (so it's not S).

**Comment by AlekSi** [comment]
Removing that code makes nested array tests fail. Let's remove support for nested arrays first
