### ISSUE TITLE
`DeletedCount` is incorrect in some cases

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1029]
Tests from #1030 should pass, not be skipped.

**Comment by noisersup** [comment]
I cannot reproduce the bug. After removing skips all test are passed. I've also used debugger and DeletedCount is set when it should.

**Comment by rumyantseva** [comment]
Not in Sprint as hard to reproduce.

**Comment by rumyantseva** [comment]
Run this test as a part of parallel tests to reproduce the problem, it might not be reproduced with `task -C 1`

**Comment by AlekSi** [comment]
Back to @noisersup because he can reproduce it now
