### ISSUE TITLE
Improve contribution guidelines

### ISSUE THREAD

**Issue by ravilushqa** [FerretDB/FerretDB#1036]
I started my contribution by looking at https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md and moving step by step. And first step `task init` is failing by default.

The problem is with a command `git describe --tags --dirty > gen/version.txt` git describe return error on forks with default mark `Copy the main branch only`. I think would be helpful to describe this behavior in CONTRIBUTING.md, so that new contributors will not face that issues

**Comment by AlekSi** [comment]
Sounds great, let's update our docs

**Comment by AlekSi** [comment]
The checkbox in question:

![CleanShot 2022-08-22 at 17 43 38@2x](https://user-images.githubusercontent.com/11512/185949736-35d667d0-4f47-41f9-b4a2-905609f3c725.png)
