### ISSUE TITLE
Migrate fuzztool to Kong

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1103]
Our current CLI handler for arguments and flags is too simplistic. We need some more features like auto-completion and support for environment variables, but not too many, like support for configuration files in 10 different formats. https://github.com/alecthomas/kong looks like a nice library. Let's try to use it on a small helper tool before migrating the main FerretDB binary to it.

Switch fuzztool from the standard library's `flag` package to Kong. The proposed syntax is:
* `fuzztool corpus seed <dir>`
* `fuzztool corpus <dir> generated`
* etc.

The first argument (`corpus`) is a command, and the second and third arguments are the source and destination, which could be a directory name or fixed strings `seed` and `generated`. All arguments should be required.

**Comment by noisersup** [comment]
Are we sure that we want to mix paths and fixed string in the arguments? Someone could be confused and after using "seed" value would try to find the "./seed" directory

**Comment by AlekSi** [comment]
Let's handle "seed" and "generated" as special cases for now. We might improve it later
