### ISSUE TITLE
Implement `serverStatus` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#113]
Return an empty result for now.

**Comment by jyz0309** [comment]
Can I take this issue? IMO, I need to add a function like this, correct me if I am wrong😳.
```
func (h *Handler) MsgServerStatus(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg, error) {
	var reply wire.OpMsg
	err := reply.SetSections(wire.OpMsgSection{
		Documents: []types.Document{types.MustMakeDocument(
			"status", "ok",
		)},
	})
	if err != nil {
		return nil, lazyerrors.Error(err)
	}

	return &reply, nil
}
```

**Comment by OpenSauce** [comment]
@jyz0309 Hi jyz! Sounds great - and yeah, you will need something similar to that, I'd take a look at this current MR https://github.com/FerretDB/FerretDB/pull/97/files for inspiration, and the associated msg### files. If you add a test for serverStatus (if there isn't one already) in the handler_tests that will make sure you're in the right direction and give you a good start.

**Comment by jyz0309** [comment]
Ok, and I also want to know that this command just return an empty result(or just return `status:ok`) for now right?

**Comment by OpenSauce** [comment]
That's correct, if not I'm sure @AlekSi will point you in the right direction 😃
