### ISSUE TITLE
Validate command documents after reading them from the wire

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#1151]
We should disallow NaN and negative zero values globally for all data and "command" (that probably do not exist) documents.

Let's reject them in the `wire` package after reading them from the connection. `bson` package should still support them because we need to read the full documents first. `fjson` package should still support them because we need it for logging. But let's remove all checks for NaNs and negative zeros from other packages.

The implementation probably should be an unexported function in the `wire` package, not a method in the `types` package.

References to this issue in the source code, diff documentation, integration tests, add unit tests and dance tests are in the scope (as usual).

Add check in both [op_msg,go ](https://github.com/FerretDB/FerretDB/blob/main/internal/wire/op_msg.go#L58) and op_query.go 

Dance tests scope:
- [x] NaN, negative zero in data documents - copy diff tests to validate documents and create a separate file

**Comment by rumyantseva** [comment]
We need to decide about command documents validation - where to call from etc
