### ISSUE TITLE
Migrate FerretDB and envtool to Kong

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1156]
Just like #1103, but for other binaries.

Migrating FerretDB will allow us to provide environment variables for configuration in addition to flags.

- [x] #1190
- [ ] #1184

**Comment by noisersup** [comment]
@AlekSi Should we left everything as it is (all values are specified by flags), or should we move some of them as a fields?

**Comment by AlekSi** [comment]
All flags should stay flags (and environment variables). No arguments / commands should be added.
