### ISSUE TITLE
Configure repo settings with files

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1172]
It is time-consuming to sync our settings, like labels, branch protection rules, etc., across repositories. There is also no good log for those changes.

It would be better to manage settings using files in git. Two known options for that are:
* https://github.com/repository-settings/app
* https://github.com/github/safe-settings

Maybe there is something else. We should use an existing tool, not make our own, ~as much as some of us want to~.

**Comment by rustiever** [comment]
Hi @AlekSi, can i take up this if you don't mind ? Also i would appreciate some help as i'm pretty new to this project.

**Comment by AlekSi** [comment]
Sure, please grab it. I don't think this issue requires some specific knowledge about FerretDB, tbh, by we have some contributing documentation [there](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md).

**Comment by rustiever** [comment]
I'm finding difficult this issue

**Comment by AlekSi** [comment]
Could I help you somehow? What did you try? What did not work?

**Comment by syasyayas** [comment]
Hi @AlekSi, this issue seems to be dead, so can I take it?

**Comment by AlekSi** [comment]
@syasyayas sure, thank you!
