### ISSUE TITLE
Use composite GitHub Action for Go setup

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#122]
We have some steps that are shared between jobs, workflows, and repositories. For example: https://github.com/FerretDB/FerretDB/blob/ef352172586ee74b69dcfeb15c4a39f201fc270f/.github/workflows/go.yml#L31-L51

It seems that [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) would allow us to DRY our workflows. Let's try to extract those steps into a common "setup Go" action.

**Comment by klokar** [comment]
@AlekSi Can I work on this improvement?

**Comment by AlekSi** [comment]
Sure thing!
