### ISSUE TITLE
Switch from `markdownlint-cli` to `markdownlint-cli2`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1250]
### What should be done?

We should switch from https://github.com/igorshubovych/markdownlint-cli to https://github.com/DavidAnson/markdownlint-cli2 because it should be faster.

### Where?

* https://github.com/FerretDB/FerretDB/blob/main/build/deps/markdownlint.Dockerfile
* https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml
* https://github.com/FerretDB/FerretDB/blob/main/.textlintignore
* https://github.com/FerretDB/FerretDB/blob/main/.markdownlint.yml

**Comment by AlekSi** [comment]
I don't think the formatting should change. Everything should work as before, just faster.

**Comment by AlekSi** [comment]
@codingmickey any news?

**Comment by codingmickey** [comment]
@AlekSi sorry for late response, was caught up in exams
