### ISSUE TITLE
Move `tjson` into `internal/handlers/tigris/tjson`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1252]
### What should be done?

To make `tigris` handler looks more like `pg` handler, let's move `tjson` package into `internal/handlers/tigris/tjson`.

We should update:
* code location;
* code comments;
* documentation comments;
* CONTRIBUTING.md;
* `golangci-lint`'s `depguard` rules;
* etc.

### Where?

Search for "tjson" and check everything.

**Comment by rumyantseva** [comment]
Blocked by #943, to be taken after #943 is done.
