### ISSUE TITLE
Clean-up `sjson` fuzzing

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1273]
It should have different logic for cases when document is valid (using `types.Document`'s validation) and when it is not.

**Comment by quasilyte** [comment]
The referring comment looks like this:

> Temporary hack, should be removed once we improve our validation.

Is there any extra context? What exactly should be improved in terms of validation?

It looks like sjson doesn't do any extra validation of its own. Let's suppose we know that the document data is invalid (as reported by ValidateData). Should the marshaling of this document fail in this case (so we want to require a non-nil error)?

**Comment by AlekSi** [comment]
`*types.Document` is used for both protocol documents and data documents; `ValidateData` check that document is a valid data document. For example, `{"$set": {"_id": 1}}` is a valid protocol document but not a valid data document. `sjson` should be used only for data documents, so I guess marshaling should return an error for invalid data documents.

In general, our validation story is not great (it is spread over too many places), but that's a problem for another day

**Comment by rumyantseva** [comment]
DoD:
- There shouldn't be TODOs mentioning this issue in the code (we don't link closed issues)
- Review comments need to be addressed
