### ISSUE TITLE
Allow dashes (`-`) in collection names

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1280]
### What should be done?

Currently, we reject collection names with dashes (`-`). We should allow them because they are common in real-life apps.

We should update:
* [x] code;
* [x] tests;
* [ ] `testutil.CollectionName` helper;
* [x] diff tests in the dance repo;
* [x] documentation.

**Comment by noisersup** [comment]
What should be updated inside `CollectionName` helper?

**Comment by AlekSi** [comment]
See #1325. But for now – nothing, we are waiting for Tigris to support dashes

**Comment by rumyantseva** [comment]
TODO:
- finish the draft about dashes - https://github.com/FerretDB/FerretDB/pull/1325/files
- check if we don't need anything in dance tests (add/delete necessary things if needed)
