### ISSUE TITLE
Make `checkConnection` less mean

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#130]
[`checkConnection` method](https://github.com/FerretDB/FerretDB/blob/5a28907d689e3203a6947db7cb8c3486e6f3f63b/internal/pg/pool.go#L75) checks server encoding, collate, ctype, etc. It should be fine with `en_US.UTF-8` spelling. See [this discussion](https://github.com/FerretDB/FerretDB/discussions/129).

Some research should be done on how PostgreSQL normalizes those values, but the code change should be easy.

**Comment by klokar** [comment]
@AlekSi Can I take this?

**Comment by AlekSi** [comment]
Sure!
