### ISSUE TITLE
Remove support for nested arrays

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1305]
Out data validation should reject documents that contain arrays immediately within arrays.
* `{"foo": [1, [2]]}` – should be rejected;
* `{"foo": [ 1, {"bar": [2]} ]}` – should be allowed.

DoD:

- [x] Implement the check in data validation function
- [x] Write unit tests
- [x] Some integration tests in ferrretdb will start failing because there are nested arrays there, such tests need to be removed
- [ ] If it's easy to remove some nested-arrays-related logic (e.g. some code is not in use), feel free to remove it. 
- [x] Update `diff.md`
- [ ] Write dance diff tests

**Comment by rumyantseva** [comment]
Blocked by #1235 for now.
