### ISSUE TITLE
Add documentation on embedded documents and dot notation support for arrays

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#1310]
### What should be done?

Add a section on document queries, embedded documents, array queries, and Dot notation support for arrays. 

* [x] add section for dot notations in the document section
* [x] retrieve documents arrays using dot notation
* [x] update documents arrays using dot notation
* [x] query an embedded document using dot notation
* [x] update an embedded document using dot notation

**Comment by AlekSi** [comment]
> Dot notation support for arrays

Not only for arrays – dot notation is used by objects too
