### ISSUE TITLE
Improve the way of storing data about collections

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1347]
### What should be done?

Currently, we store information about all the collections in the row of the settings table. To simplify code, improve performance, and have fewer locks per operation, we should store the list of collections in a separate table, where one collection is represented by one row. With that, when we want to create settings for a new collection or delete settings for an existing one, we won't need to request the whole list and don't have to lock everything.

### Implementation details

We should reuse the same approach as we already use when work with PostgreSQL in other places (for example, the function `pgdb.InsertDocument` to insert documents into the settings table. It might be possible that such functions need to be refactored and/or extended. For example, if `insert ... on conflict do nothing` is needed, we need to extend `pgdb.InsertDocument` to support it.

### Necessary refactoring

How we deal with the settings table needs to be refactored.
There should be only three functions in `settings.go` (the signatures are provided as a starting point and might be changed if necessary):

#### addSettingsIfNotExists - to be used when collection needs to be created
```go
// addSettingsIfNotExists returns settings (table name) for the given database and collection.
// If such settings don't exist, it creates them.
func addSettingsIfNotExists(ctx context.Context, tx pgx.Tx, db, collection string) (string, error) 
```

#### getSettings - to be used when collection needs to be queried
```go
// getSettings returns settings (table name) for the given database and collection.
// If such settings don't exist, it returns an error.
func getSettings(ctx context.Context, tx pgx.Tx, db, collection string) (string, error)
```

#### removeSettings - to be used when collection needs to be deleted
```go
// removeSettings removes settings for the given database and collection.
// If such settings don't exist, it doesn't return an error.
func removeSettings(ctx context.Context, tx pgx.Tx, db, collection string) error
```

The functions should be as simple as possible and mustn't return unnecessary errors. For example, `createSettingsIfNotExist` mustn't return `AlreadyExists` or `removeSettings` mustn't return `NotExists`. 

### Unique constraint 
The field of `_jsonb` column representing the collection name in the settings table should have a unique constraint.
With that, we can use something like `INSERT INTO settings(_jsonb) (_jsonb = '{"collection": "hello", ...}') ON CONFLICT (_jsonb->>'collection') DO NOTHING` and keep the code of `addSettingsIfNotExists` simple. 

#### Other places in the code to check

We expect that the implementation of this task will improve performance as currently, settings-related functions (e.g. `getSettingsTable`) are called in every single operator. Check the places where the issue number is mentioned.

In particular in the test `TestUpdateFieldCurrentDate` we have `maxDifference := time.Duration(4 * time.Minute)`. After implementing the current task we expect that `maxDifference` could be moved back to `3 * time.Minute` (or even lower). If it's not enough, create a separate issue to investigate this particular problem with tests performance.

**Comment by AlekSi** [comment]
> The columns representing the collection name and table name

What columns?

**Comment by rumyantseva** [comment]
@AlekSi I rephrased the sentence, so hopefully, it's more clear. PTAL.
