### ISSUE TITLE
Example build failed

### ISSUE THREAD

**Issue by wangagui** [FerretDB/FerretDB#138]
I want my first experience of ferretDB,and I follow the steps of the quickStart,I get the error:
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/31622604/145363661-94fe9e28-04f4-4b56-b85e-4e6cb8ead4f5.png">

**Comment by AlekSi** [comment]
I updated an example to remove `--silent` flag; please pull and try again – the real error should be visible now. Probably, that was a temporary NPM registry problem; it works for me now.

**Comment by AlekSi** [comment]
@wangagui Does it work for you now?
