### ISSUE TITLE
Create unique index for `_id` automatically

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1384]
### Versions

November 9, 2022

for example, https://github.com/FerretDB/FerretDB/commit/9e34c247112d8d2bc03f260a49a04a6b500284cf

### What did you do?

Call `db.pcs.insertOne({"_id": "foo", "value": "bar"})` twice

### What did you expect to see?

The second attempt to insert entry with the same value in the `_id` field should return an error.

```
test> db.pcs.insertOne({"_id": "foo", "value": "bar"})
{ acknowledged: true, insertedId: 'foo' }
test> db.pcs.insertOne({"_id": "foo", "value": "bar"})
 E11000 duplicate key error collection: test.pcs index: _id_ dup key: { _id: "foo" }
```

### What did you see instead?

Both entries were inserted:

```
test> db.pcs.insertOne({"_id": "foo", "value": "bar"})
{ acknowledged: true, insertedId: 'foo' }
test> db.pcs.insertOne({"_id": "foo", "value": "bar"})
{ acknowledged: true, insertedId: 'foo' }
test> db.pcs.find();
[ { _id: 'foo', value: 'bar' }, { _id: 'foo', value: 'bar' } ]
```

P.S. This is how it works for Postgres. For Tigris it returns an error, however, the error is not correct (we should return a proper error, but an internal error is returned instead).

DoD:
- See also: TODOs in the code
- Create index
- Not enforce id uniqueness in Go code (indexes should be enough for it) - lazyerror is good enough for now
- List indexes should return - just returning _id index is enough (no need to query metadata yet)

```[tasklist]
### Tasks
- [ ] #2044
```

**Comment by Fashander** [comment]
We should update this once this task is completed - https://docs.ferretdb.io/understanding_ferretdb/#indexing
