### ISSUE TITLE
When create collection in Tigris, use `only create` option

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1395]
### What should be done?

Currently, in `msg_create` we call `CreateOrUpdate` method that can update collection in the case of parallel requests. Tigris API supports ["only create"](https://github.com/tigrisdata/tigris-api/blob/main/server/v1/api.proto#L511) option which we can use to handle collection creation correctly.

The task requires [at least 1.0.0-beta.11 ](https://github.com/tigrisdata/tigris-client-go/releases/tag/v1.0.0-beta.11)of Tigris client.

Example:

```go
db.CreateOrUpdateCollection(ctx, "c1", Schema(sch), &driver.CreateCollectionOptions{OnlyCreate: true})
```

**Comment by AlekSi** [comment]
I also found this gem:

```go
// setupCollection setups a single collection for all compatible providers, if they are present.
func setupCollection(tb testing.TB, ctx context.Context, client *mongo.Client, opts *SetupOpts) *mongo.Collection {

// ...

		// if validators are set, create collection with them (otherwise collection will be created on first insert)
		if validators := provider.Validators(*handlerF, collectionName); len(validators) > 0 {
			var copts options.CreateCollectionOptions
			for key, value := range validators {
				copts.SetValidator(bson.D{{key, value}})
			}

			require.NoError(tb, database.CreateCollection(ctx, collectionName, &copts))
		}

```

`setupCollection` should create a single collection, but that code tries to create multiple of them.

**Comment by rumyantseva** [comment]
@AlekSi what would be your approach to fixing it? Should we have a separate setup for Tigris (in case of Tigris we can't use the same collection for different providers), should we modify this function to return the same collection for Postgres but multiple collections for Tigris, or should we do something else?

**Comment by AlekSi** [comment]
> should we modify this function to return the same collection for Postgres but multiple collections for Tigris

That would break all tests.

Other than that, I don’t know.

Another bug: SetValidator replaces the previous value, so that `for range` loop over validators is not correct too

**Comment by rumyantseva** [comment]
test
