### ISSUE TITLE
Add commands compatibility table to docs

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1399]
We should expand https://docs.ferretdb.io/Reference/supported_commands/ with information about all MongoDB and FerretDB commands, with all input arguments. Search for existing issues or create new ones and add TODOs as you go.

Please send a few PRs, not one huge PR, and not one PR per command.

We don't document output arguments yet.

https://github.com/FerretDB/FerretDB/blob/main/website/docs/reference/supported_commands.md

**Comment by b1ron** [comment]
Links to MongoDB database commands.

1. [Aggregation Commands](https://www.mongodb.com/docs/manual/reference/command/#aggregation-commands)
2. [Geospatial Commands](https://www.mongodb.com/docs/manual/reference/command/#geospatial-commands)
3. [Query and Write Operation Commands](https://www.mongodb.com/docs/manual/reference/command/#query-and-write-operation-commands)
4. [Query Plan Cache Commands](https://www.mongodb.com/docs/manual/reference/command/#query-plan-cache-commands)
5. [Authentication Commands](https://www.mongodb.com/docs/manual/reference/command/#database-operations)
6. [User Management Commands](https://www.mongodb.com/docs/manual/reference/command/#user-management-commands)
7. [Role Management Commands](https://www.mongodb.com/docs/manual/reference/command/#role-management-commands)
8. [Replication Commands](https://www.mongodb.com/docs/manual/reference/command/#replication-commands)
9. [Sharding Commands](https://www.mongodb.com/docs/manual/reference/command/#sharding-commands)
10. [Session Commands](https://www.mongodb.com/docs/manual/reference/command/#session-commands)
11. [Administration Commands](https://www.mongodb.com/docs/manual/reference/command/#administration-commands)
12. [Diagnostic Commands](https://www.mongodb.com/docs/manual/reference/command/#diagnostic-commands)
13. [Free Monitoring Commands](https://www.mongodb.com/docs/manual/reference/command/#free-monitoring-commands)
14. [Auditing Commands](https://www.mongodb.com/docs/manual/reference/command/#auditing-commands)
