### ISSUE TITLE
Could we pass the `msg.Document()` into the message handler?

### ISSUE THREAD

**Issue by mmyj** [FerretDB/FerretDB#143]
https://github.com/FerretDB/FerretDB/blob/bb0d0fef1aac1ca460f271342948fe7351cbf74d/internal/handlers/handler.go#L147
https://github.com/FerretDB/FerretDB/blob/bb0d0fef1aac1ca460f271342948fe7351cbf74d/internal/handlers/shared/msg_dropdatabase.go#L30

Hello,
Many message handlers will invoke `document, err := msg.Document()` again,  could we pass `document` from `Handler.handleOpMsg` ?

**Comment by AlekSi** [comment]
Probably. I have more ideas more refactoring, but let's re-evaluate them a bit later.

**Comment by AlekSi** [comment]
Let's keep it open as reminder

**Comment by mmyj** [comment]
> Let's keep it open as reminder

OK.
