### ISSUE TITLE
Implement `createUser` command

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1491]
### What should be done?

We should implement the basic [`createUser` command](https://www.mongodb.com/docs/manual/reference/command/createUser/).

We should store the following information in the `system.users` collection in the `admin` database:

```
{
  _id: "<database name>.<username>",
  userID: types.Binary{Subtype: types.BinaryUUID, B: <UUID>},
  user: "<username>",
  credentials: {}
}
```

We should accept the following `createUser` arguments:
* `$db` – ignore for now;
* `createUser`;
* `pwd` – ignore for now;
* `customData` – ignore non-default value for now;
* `roles` – ignore for now;
* `digestPassword` – should be `true` or absent/null;
* `writeConcern` – ignore;
* `authenticationRestrictions` – ignore;
* `mechanisms` – ignore for now;
* `comment` – ignore for now.

We should test that data is inserted using the regular `find` command.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/handler

### Definition of Done

- handler updated;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by kropidlowsky** [comment]
@AlekSi can I work on this one?

**Comment by AlekSi** [comment]
@kropidlowsky I'm afraid that's not possible at the moment. While we could create new users in PostgreSQL with `CREATE ROLE`, the underlying issue is that we want to have our own credentials database, but the details are unclear yet.

**Comment by AlekSi** [comment]
@henvic Let's start by running FerretDB in [`diff-proxy` mode](https://docs.ferretdb.io/configuration/operation-modes/) with `task run-proxy` and observe what `mongosh` sends for [`db.createUser`](https://www.mongodb.com/docs/manual/reference/method/db.createUser/)
