### ISSUE TITLE
Implement `renameCollection` command

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1517]
https://www.mongodb.com/docs/v6.0/reference/command/renameCollection/

`renameCollection` should be implemented for all corner cases. 

- we shouldn't rename PostgreSQL table, just change the _id in metadata.
- we should be able to create new collection with the old name after rename.  
- do not change the deterministic names of collections on simple inserts (don't randomize hashes)
- adding `-1/2/3...` after table name might be solution for conflicting inserts, although if we extend the length of PostgreSQL table after rename, we need to test is there any way to exceed the max length of PostgreSQL table name (for example by providing large collection name.

DoD:
- [x] `renameCollection` command implemented (`writeConcern`, `comment`, and `dropTarget` fields are not in scope)
- [x] existing test that creates collection `foo` with some data, renames to `bar`, creates new `foo` collection with different data, and checks that `foo` and `bar` are two different collections.
- [x] existing test that creates  `foo` and `bar` collections, and tries rename `foo` to `bar` (`bar` already exists)
- [x] existing tests for renaming non-existent db
- [x] test some concurrent renaming (e.g. attempt to rename various collections to the same new name) 

Cross-database rename is not in the scope, see https://github.com/FerretDB/FerretDB/issues/2563

**Comment by pavel-odintsov** [comment]
We noticed absence of this command too:
```
 {
   "Checksum": 0,
   "FlagBits": 0,
   "Sections": [
     {
       "Document": {
         "$k": [
           "ok",
           "errmsg",
           "code",
           "codeName"
         ],
         "ok": {
           "$f": 0
         },
         "errmsg": "no such command: 'renameCollection'",
         "code": 59,
         "codeName": "CommandNotFound"
       },
       "Kind": 0
     }
   ]
 }
```
