### ISSUE TITLE
Query `Find` does not return error on invalid value of `$size` operator

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1539]
### Versions

0.6.2

### What did you do?

To attempt to add a compat test, queried `collection.Find` with negative size filter `bson.D{{"v", bson.D{{"$size", -1}}}}` on each Provider in shareddata. The scalar values do not return error.

Example:
```
test> docs =[ { _id: 'double', v: 42.13 }, { _id: 'double-whole', v: 42 }, { _id: 'double-zero', v: 0 }, { _id: 'double-max', v: 1.7976931348623157e+308 }, { _id: 'double-smallest', v: 1.7976931348623157e+308 }]  
[
  { _id: 'double', v: 42.13 },
  { _id: 'double-whole', v: 42 },
  { _id: 'double-zero', v: 0 },
  { _id: 'double-max', v: 1.7976931348623157e+308 },
  { _id: 'double-smallest', v: 1.7976931348623157e+308 }
]
test> db.foo.insertMany(docs)
{
  acknowledged: true,
  insertedIds: {
    '0': 'double',
    '1': 'double-whole',
    '2': 'double-zero',
    '3': 'double-max',
    '4': 'double-smallest'
  }
}
test>  db.foo.find({ "v": { "$size": -1 } })

test> exit
```

### What did you expect to see?

Same as compat response of `Failed to parse $size. Expected a non-negative number in: $size: -1`.

### What did you see instead?

No error.

**Comment by AlekSi** [comment]
@chilagrow @b1ron Please send a PR that adds `build/mongosh/test.js.example` file with a test script with assertions for that issue. It will be useful as an example.
