### ISSUE TITLE
Skip documentation build if no docs where changed

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#1589]
### What should be done?

We can speed up CI runs if we will skip the documentation build if no documentation files were changed.

### How?

It can be done by creating another workflow and job with the same names; see
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by AlekSi** [comment]
The solution proposed by GitHub is bad and does not really work with a way we skip and require checks. And the issues itself is not really a problem; Vercel is.

**Comment by AlekSi** [comment]
To expand on that: if PR is sent that changes both code and documentation, both workflows will run; the empty one will succeed first and hide potential errors in the other one.
