### ISSUE TITLE
Add `InTransactionRetry` helper

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1618]
### Final Design Deicsion

- [x] Retry parameters `maxRetries`, `delay` are constants
- [x] Context should only be checked in `inTransaction` (no need to check it in `InTransactioRetry`)
- [x] `ctxutil.Sleep(ctx, delay)` should be used for delays between attempts
- [x] `transactionConflictError` should wrap the original error
- [ ] ~`lazyerror` should be used for errors that are not expected / couldn't be processed~ `inTransaction` already wraps everything in `lazyError`.

---

### Initital Proposal (draft, might not compile)

Implement  `InTransactionRetry` function that would use `InTransaction` with the given retry in case the transaction failed.

**Details:** In principle, we need to retry the transaction only if there is a `pgerrcode.UniqueViolation`, `pgerrcode.DuplicateObject`, or a similar error. 

We can define a special error to be returned in such cases. For example, an error could be something like:

```go
// errTransactionConflict is returned when one of the queries in the transaction returned an error because
// of an unexpected conflict. The caller could retry such a transaction.
var errTransactionConflict = fmt.Errorf("transaction can't continue due to a conflict")
```

And then `InTransactionRetry` would be something like:

```go
func (pgPool *Pool) InTransactionRetry(ctx context.Context, f func(pgx.Tx) error, maxRetries int, delay time.Duration) (err error) {
	for retry := 0; retry < maxRetries; retry++ {

		// TODO: Maybe check if context is done  

		err := pgPool.InTransaction(ctx, f)

		switch {
		case err == nil:
			return nil
		case errors.Is(err, errTransactionConflict):
			time.Sleep(delay)
		default:
			return err
		}
	}
}
```

With that, the places where we check for pg errors could be like:

```go
	switch pgErr.Code {
	case pgerrcode.UniqueViolation, pgerrcode.DuplicateObject:
		// https://www.postgresql.org/message-id/CA+TgmoZAdYVtwBfp1FL2sMZbiHCWT4UPrzRLNnX1Nb30Ku3-gg@mail.gmail.com
		return errTransactionConflict
	default:
		return lazyerrors.Error(err)
	}
```

### Definition of done

- [x] Implement `InTransactionRetry`
- [x] Modify at least one handler (for example, `msg_insert`) to use `InTransactionRetry` in case of a pg conflict for `CreateCollectionIfNotExist`
- [x] Find places where we should use `InTransactionRetry` and create issue for them

**Comment by w84thesun** [comment]
Looks good! Do we need this to create schemas and collections, or are there is other potential usages intended?

**Comment by rumyantseva** [comment]
@w84thesun schemas and collections are the cases we have now, yes. Plus there are also some statistics-related queries (e.g. when we query the size of a table and the table is deleted from a concurrent request). I hope we won't have more cases :)

**Comment by chilagrow** [comment]
Thanks for this! Is timeout something we would want to consider for retry?

**Comment by rumyantseva** [comment]
I update the code example a little bit to mention context.

**Comment by chilagrow** [comment]
Yeah it's just about context cancel, yep sounds good :+1:

**Comment by rumyantseva** [comment]
@AlekSi please check if implementation proposal looks reasonable to you

**Comment by AlekSi** [comment]
> `maxRetries int, delay time.Duration`

That forces the caller to think about those parameters every time. I think they should be constants.

> `(err error)`

The named result is not being used.

> // TODO: Maybe check if context is done 

That's already done by `InTransaction`

> `time.Sleep(delay)`

`ctxutil.Sleep(ctx, delay)`

> `return err`

That probably should be wrapped with lazyerror.

```
case pgerrcode.UniqueViolation, pgerrcode.DuplicateObject:
		return errTransactionConflict
```

I think we lose information about the original error that is useful. So we either should log it everywhere or make a new error _type_ that wraps the original error instead of the new sentinel error value.

Finally, `InTransactionRetry` function doesn't have a `return` after the loop. It will not compile.
