### ISSUE TITLE
Check crc32 checksums in the `wire` package

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1626]
### What should be done?

`OP_MSG` packets may include crc32c checksum that we are not verifying or sending yet. Let's do that.

### Where?

https://github.com/FerretDB/FerretDB/blob/73761a7a4365415ad493af172b0a89aedda15f44/internal/wire/op_msg.go

**Comment by kropidlowsky** [comment]
I would like to work on it

**Comment by adetunjii** [comment]
Hi @AlekSi, can I work on this issue?

**Comment by rumyantseva** [comment]
@adetunjii thank you! I assigned you.
