### ISSUE TITLE
Validate maximum nested document/array depth

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1639]
### What should be done?

Just like MongoDB, we should disallow documents and arrays that exceed the maximum nested object depth.

For now, let's do that for incoming documents only in `bson` and/or `wire` packages, or just in validation in `types` package.

See references to this issue in code.

DoD:
- add a simple compat test (check that FerretDB returns an error when MongoDB does, the error doesn't need to be the same)
- @noisersup: create a follow-up issue to make the errors equal and to cover all the leftovers if any (e.g. dance tests if needed)

**Comment by arthurgavazza** [comment]
Hey, I wanna start contributing to the project can I pick this up?

**Comment by noisersup** [comment]
@arthurgavazza Thank you for your interest in contributing to FerretDB! If you have any questions or need any assistance I will be more than happy to help :)

**Comment by arthurgavazza** [comment]
Thank you! I actually have a few questions.
1. Should I add the validation logic in this file ? https://github.com/FerretDB/FerretDB/blob/main/internal/types/document_validation.go and apply it in internal/bson/document.go?
 2. Is there any built in method for checking object depths or I could add my own?

**Comment by noisersup** [comment]
> Should I add the validation logic in this file ? https://github.com/FerretDB/FerretDB/blob/main/internal/types/document_validation.go and apply it in internal/bson/document.go?

 The `internal/types/document_validation.go` validates `internal/types.Document` struct which is our internal representation of a document. With this type we do most of the data processing, comparison, filtering, etc. 

Currently we want to do this check only for incoming documents, right before they are parsed and processed. To do so we need to do changes inside `internal/bson.Document`. 

The `internal/bson` package is responsible for converting/interpreting incoming bytes from mongodb wire connection into specific types. So we need to modify `bson.Document.ReadFrom` to validate the depth of documents. There are some TODOs related to this issue here: [1](https://github.com/FerretDB/FerretDB/blob/main/internal/bson/document.go#L184), [2](https://github.com/FerretDB/FerretDB/blob/main/internal/bson/document.go#L31), [3](https://github.com/FerretDB/FerretDB/blob/main/internal/bson/document.go#L199).

> Is there any built in method for checking object depths or I could add my own?

2. Afaik we don't have any, feel free to add it if needed.

**Comment by noisersup** [comment]
The idea behind the check on `bson.Document` level was that `bson.Documents`'s `readFrom` function, reads data to parse from the reader, so we don't need to store whole document in memory to validate if document has correct amount of nesting. As `readFrom` is called recursively on nested documents we would need to pass the nest level as an argument or inside the `bson.Document` struct.

There might be some complicated things here so we could instead do this check on the `types.Document` level in the `document_validation.go`. The downside of that is the fact that `types.Document` will be already stored in memory in order to validate it, but it's a good starting point for this issue and we could focus on validation on the `bson.Document` level later :)

Feel free to choose preferred approach.

**Comment by b1ron** [comment]
I was also looking into this, to avoid too many stack frames you could try an iterative approach. But you'd need a way to drop levels, a BSON object iterator or something.

**Comment by arthurgavazza** [comment]
@b1ron @noisersup I think a BFS approach on types.Document would be easier for me to deal with right now, as a beginner, but with some extra help I could try the bson.Document approach. 
Regarding the bson.Document approach, what's the ideia? In what moment should I add the nesting level to the struct so I could check when traversing it?

**Comment by noisersup** [comment]
The ReadFrom function goes byte by byte through the stream of data sent by mongo client.
The stream contains document with values that are preceeded by tag that specify the type of the following value.

On the line 182 there's a switch statement that checks the tag, if the tag is equal to tagDocument (0x03) we expect bytes after it
to be a nested document. We create another bson.Document for it and do recursive call to it's ReadFrom to perform the same operation.

In summary, if user inserts the document that is nested 3 times, the ReadFrom will be called recurively 3 times.

To count the depth of nested document we need to somehow provide it with the depth of it's parent.
The simplest idea is to make ReadFrom function take the depth as an argument:

```go
// ReadFrom implements bsontype interface.
func (doc *Document) ReadFrom(r *bufio.Reader, depth int) error {
	// ...
		case tagDocument:
			// TODO check max nesting https://github.com/FerretDB/FerretDB/issues/1639

			var v Document
			if err := v.ReadFrom(bufr, depth+1); err != nil {
				return lazyerrors.Errorf("bson.Document.ReadFrom (embedded document): %w", err)
			}
```

Although it's not possible, as ReadFrom implements [bsontype interface](https://github.com/FerretDB/FerretDB/blob/main/internal/bson/bson.go#L59-L65), which is implemented by all other types that doesn't require to store depth.
For example, there's no point to provide the depth for int32Type.ReadFrom.

The other solution for this problem might be storing the depth inside the `bson.Document` struct:

```go
// Document represents BSON Document type.
type Document struct {
	fields []field
	depth int
}
```

So when you call the ReadFrom inside the `tagDocument` case we would set it like that:

```go
// ReadFrom implements bsontype interface.
func (doc *Document) ReadFrom(r *bufio.Reader) error {
	// ...
		case tagDocument:
			// TODO check max nesting https://github.com/FerretDB/FerretDB/issues/1639

			var v Document
			v.depth = doc.depth+1

			if err := v.ReadFrom(bufr); err != nil {
				return lazyerrors.Errorf("bson.Document.ReadFrom (embedded document): %w", err)
			}
```

At least that's how I see it right now, maybe there's a better solution to this problem

**Comment by arthurgavazza** [comment]
Thank you for the explanation, it helped me a lot! I'll try the solution you mentioned.

**Comment by arthurgavazza** [comment]
@noisersup I'm working on the recursive solution and it's working, but now a found a small problem. maxNesting is declared as a const at the top of the bson/document.go file. I modified that value locally just for testing, but I need a way to switch that value in the testing environment. Should I use an environment variable for that? I would do it the following way, but if there's a better solution please let me know. 
thanks in advance
```
var (
	maxNesting = getMaxNesting()
)

func getMaxNesting() int {
	if t, _ := strconv.ParseBool(os.Getenv("CI")); t  {
		return 1
	}
	return 100
}



```

**Comment by b1ron** [comment]
@arthurgavazza not sure why you would want to change that value, but please elaborate. I assume it's for validating other maxNesting values.

I think we should generate complex documents to see if that breaks exceeds max depth etc.

@noisersup chime in here too. I could be way off with my understanding of the above.

**Comment by arthurgavazza** [comment]
> @arthurgavazza not sure why you would want to change that value, but please elaborate. I assume it's for validating other maxNesting values.
> 
> 
> 
> I think we should generate complex documents to see if that breaks exceeds max depth etc.
> 
> 
> 
> @noisersup chime in here too. I could be way off with my understanding of the above.

I wanted to change that to avoid creating complex test data with more than 100 levels of nesting. But if that's ok There's no need for the maxNesting to change. Thanks for the answer. Without that change I need a complex document for the unit tests.  Is there a tool used for generating the hex files?

**Comment by noisersup** [comment]
@arthurgavazza I guess that unit tests are relevant only if we choose the `types.Document` approach. Converting documents to binary for unit tests seems a bit overcomplicated so I would suggest to skip it and write a simple integration test that will insert nested document.

There might be some differences in returned error that will be addressed in the future, so feel free to ping me if I can help with writing those :)

**Comment by arthurgavazza** [comment]
I didn't have the time to work on this yesterday, but I'll try to finish everything today and create a PR. Should I create the integration test in this file? https://github.com/FerretDB/FerretDB/blob/main/integration/create_test.go
Thanks @noisersup I would appreciate the help. Is there a communication channel where I can ping you, so I don't flood the issue with questions?

**Comment by noisersup** [comment]
> Should I create the integration test in this file? https://github.com/FerretDB/FerretDB/blob/main/integration/create_test.go

I believe we could place this test in https://github.com/FerretDB/FerretDB/blob/main/integration/basic_test.go

> Is there a communication channel where I can ping you

Sure! Feel free to join the [FerretDB community slack](https://join.slack.com/t/ferretdb/shared_invite/zt-zqe9hj8g-ZcMG3~5Cs5u9uuOPnZB8~A).

**Comment by noisersup** [comment]
@arthurgavazza If there's anything I can help with please let me know!

**Comment by arthurgavazza** [comment]
Thanks a lot! I've been very busy with working and didn't have the time to continue working on this issue on the last few weeks. I'll continue working on it tomorrow. I'll probably need some help with the integration tests!

**Comment by noisersup** [comment]
@arthurgavazza Just a gentle reminder about the task we discussed. If you need any support with the integration tests, please don't hesitate to reach out. Your contributions are greatly appreciated!

**Comment by arthurgavazza** [comment]
Sorry for taking this long, I've been very busy with my job. I'll continue working on this issue later today. Can I reach you on slack to help me with the integration tests?

**Comment by noisersup** [comment]
Yes sure!

**Comment by noisersup** [comment]
@arthurgavazza Are you still interested about this issue? :)

**Comment by kropidlowsky** [comment]
Hi @AlekSi,

Can I work on this issue? :raised_hand:

**Comment by kropidlowsky** [comment]
Hi @noisersup ,

I am working on integration test.
I would like to create a help function which would create recursively nested map like this:
`map[0:map[1:map[2:map[3:map[4:<nil>]]]]]` and to create `bson.M` based on it

Base on conversation from above I could see the integration test itself should be located here https://github.com/FerretDB/FerretDB/blob/main/integration/basic_test.go .

Where would it be good to create the help function to create nested maps?
I suppose it might be useful for other test cases (not only integration once) :sweat_smile:

Thanks in advance!

**Comment by noisersup** [comment]
@kropidlowsky As the helper function will be used only for integration/compat tests I would suggest to place in `integration/helpers.go` file :)

**Comment by AlekSi** [comment]
See also #2957

**Comment by noisersup** [comment]
I see some inconsistency with our architecture. We have this [bson.Document](https://github.com/FerretDB/FerretDB/pull/2882/files#diff-dcc9c2fef05d3bf1db426456e5644f24e5b477c2689968392b725d8d15cc9687R42-R46) struct which is under the Document interface so we can convert `bson.Document` into the `types.Document`. We plan to remove this interface and remove this layer of abstraction. For `bson.arrayType` we don't have the interface, and the `arrayType` just wraps `types.Array` type so we can "convert" between `bson` and `types` with just a type assertion.

Although in this PR we want to count nested objects on the `bson` level, which requires storing the nesting value somewhere in struct (something that we implement in `bson.Document`), we cannot do the same thing on array. We might create some common interface between array and document that is created specifically for nesting validation, but it seems too complicated. My question is - What do we want to achieve in the `bson` package? If we want to move such validation on this level I believe we might have some fields that are not needed on the `types` level, hence we cannot expect the `types` and `bson` representations of objects to be the same.
