### ISSUE TITLE
Compat test on tigris handler on $pop fails

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1677]
### Versions

0.7.1

### What did you do?

Added compat test on `$pop`

```
		"Pop": {
			update:        bson.D{{"$pop", bson.D{{"v", 1}}}},
		},
		"PopFirst": {
			update:        bson.D{{"$pop", bson.D{{"v", -1}}}},
		},
```

### What did you expect to see?

Same as compat and test to pass

### What did you see instead?

Error was seen `"Path 'v' contains an element of non-array type 'object'"`

**Comment by rumyantseva** [comment]
As we don't support arrays on Tigris at the moment, we can't really support `$pop` correctly. So, Let's skip this task for now.

**Comment by rumyantseva** [comment]
This test case works after Tigris arrays are enabled, see https://github.com/FerretDB/FerretDB/pull/1819/files.
 
We can close this issue after merging  #1819.

**Comment by rumyantseva** [comment]
I close this issue as the tests will be enabled in #1834, and we don't need this separate issue.
