### ISSUE TITLE
Document CLI flags and environment variables

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1706]
### What should be done?

Our documentation should provide more information than just `--help` flag.

Most importantly:
* the `--mode` flag requires some explanation in user documentation, not only in CONTRIBUTING.md;
* TLS flags should be explained.

_Related: https://ferretdb.slack.com/archives/C049W6E01E0/p1672187174464469_

**Comment by chilagrow** [comment]
Slack conversation related to this https://ferretdb.slack.com/archives/C049W6E01E0/p1672187174464469
