### ISSUE TITLE
Implement projection positional `$` operator

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1709]
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/projection/positional/#mongodb-projection-proj.-

The most work would be interfacing filtering and projection. For example, if projection is applied to `[42, 43, 44]` and filter is `{$gt: 42}`, [FilterDocument](https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/filter.go#L37) returns boolean result. The result does not indicate that `43` and `44` is the value matched the filter. However since projection returns first element of array that matched the condition which is `[43]`, we need to get that information. 

DoD:
- Take one element from array e.g. `db.values.find({v: {$gt: 42}}, {"v.$": 1})` - The example is tested with `task env-data` and should work for our [shareddata](https://github.com/FerretDB/FerretDB/tree/main/integration/shareddata)

Documentation:
- update supported commands doc
- create a new issue to write documentation about this feature (for the techwriter)

**Comment by rumyantseva** [comment]
Possible way: split a task into a few if we can return `Unimplemented` for some parts of it (e.g. dot notation).
