### ISSUE TITLE
Fix inserts of documents without `_id`s

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1714]
### What should be done?

When an empty document `bson.D{}` is inserted through `collection.InsertOne()` or `collection.InsertMany()`, the driver itself sets a new unique `_id` for such a document.

However, if such a document is inserted through `db.RunCommand()`, a unique `_id` is not set. 

In this case, FerretDB behaves differently than MongoDB: MongoDB inserts a doc and assigns an `_id`, and FerretDB returns an error.

We need to fix it.

### Where?

See the issue mentioned in the skipped `InsertEmpty` test - https://github.com/FerretDB/FerretDB/pull/1673/files. Remove "skipped" and run the test to see the difference between MongoDB and FerretDB.

### Definition of Done

- compatibility test unskipped.

**Comment by rumyantseva** [comment]
@AlekSi please specify the expected behavior.

**Comment by AlekSi** [comment]
FerretDB should generate an ID itself. That's similar to how `update` and `findAndModify` handlers do that.

**Comment by kropidlowsky** [comment]
@AlekSi Can I work on this one?

**Comment by AlekSi** [comment]
Sure!
