### ISSUE TITLE
Migrate to `pgx/v5`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1717]
### What should be done?

We should migrate to `github.com/jackc/pgx/v5` to stay current.
See https://github.com/jackc/pgx/blob/master/CHANGELOG.md

### Where?

Everywhere.

### Definition of Done

* `github.com/jackc/pgx/v4`, `github.com/jackc/pgtype`, `github.com/jackc/pgconn`, and `github.com/jackc/pgproto3` packages should not be present in any `go.mod` files.
* Those old packages should be added to `depguard` linter configuration.

**Comment by craigpastro** [comment]
I can probably handle this! Mind if I give it a shot?

**Comment by AlekSi** [comment]
@craigpastro Sure!

**Comment by AlekSi** [comment]
@craigpastro would you be interested in #2389?

**Comment by AlekSi** [comment]
@craigpastro please leave a comment on that issue so I could assign it to you. I guess GitHub doesn't allow that without interaction to prevent spam
