### ISSUE TITLE
Use exponential backoff with jitter

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1720]
### What should be done?

We should use exponential backoff with jitter in places where we wait for something.

See https://aws.amazon.com/ru/blogs/architecture/exponential-backoff-and-jitter/

### Where?

Places that use `ctxutil.Sleep`, `time.Sleep`, `context.WithTimeout`, etc.

### Definition of Done

- no new external dependency;
- unit test for math added;
- spot refactorings done.

**Comment by j0holo** [comment]
Hey @AlekSi I would like to try my hands on this issue.

I have a few questions after reading the linked blog post.

1. How high should the backoff cap be? 500ms, 1s, 60s?
2. Is there a preference between _full jitter_ and _decorrelated jitter_ for FerretDB?
3. Should the attempt count be tied to the context or a global attempt count?

**Comment by AlekSi** [comment]
1. Let’s make it a constant with a value of 1 second. We could tweak it in a single place later.
2. No preference :)
3. There should not be any global variables.

Thank you!

**Comment by AlekSi** [comment]
I think we have a bug in the current code, or at least code comment is incorrect. It says "The minimum duration is at least 100 milliseconds", but we return a random number in [0; lowestValue) range, that could be even zero: https://github.com/FerretDB/FerretDB/actions/runs/4886789241/jobs/8722599105?pr=2564

**Comment by j0holo** [comment]
That is strange, because 100*2^0 (first try) = 100. math.Min should then select the lowest of the two numbers. 1000ms (1s is used in the test) or a minimum of 100ms (the base value).
