### ISSUE TITLE
Querying for an embedded field in array does not behave correctly

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1724]
### Versions

v0.7.1-29-gaf17fa7-dirty

### What did you do?

See repro script in #1722.

### What did you expect to see?

1 document returned.

### What did you see instead?

0 documents and an assertion.

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go1.19.3 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 20.10.16
```

### DoD

That should be supported by the common Go filtering code. Pushdown for such filters is not in the scope.

- [ ] Add a test data item to `Composites` to support `{a: [{}, {b: 1}]}` example (object -> array -> object)
- [ ] Use `ArrayDocuments`, it has this particular case
- [ ] Run existent test and see if smth needs to be modified because of the new test data item
- [ ] Add compat tests for find, count, findAndModify, update, delete for filter `{'a.b': 1}`
- [ ] If needed, create new issue for problems irrelevant to the current issue
- [ ] Update user docs (dot notation)
- [ ] It may also fix #1828, check it
- [ ] Don't push down queries that have dot notation

**Comment by rumyantseva** [comment]
More examples (it's allowed to use `foo.bar` for arrays in queries, but not in update statements)

```
db.foo.insert({"foo":[{"bar": "hello"},{"bar": "world"}]})

db.foo.find({"foo.bar": "world"})
[
  {
    _id: ObjectId("63d958d2a0546f881e906f1e"),
    foo: [ { bar: 'hello' }, { bar: 'world' } ]
  }
]

db.foo.updateMany({"foo.bar": "hello"},{$set: {"foo.bar": "world"}})
Cannot create field 'bar' in element {foo: [ { bar: "hello" }, { bar: "world" } ]}

db.foo.updateMany({"foo.bar": "hello"},{$set: {"foo.0.bar": "world"}})
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 1,
  modifiedCount: 1,
  upsertedCount: 0
}

```

**Comment by AlekSi** [comment]
Let's wait for Tigris to support `foo.0.bar` access
