### ISSUE TITLE
Support `getMore` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1733]
### What should be done?

https://www.mongodb.com/docs/manual/reference/command/getMore/

- [x] Do not consume all documents in `find`: #2933
- [x] Do not consume all documents in `aggregate`
- [ ] Refactor tests (https://github.com/FerretDB/FerretDB/pull/2929/files#r1246365875)

Test script: #2761

**Comment by w84thesun** [comment]
What has been done so far:
* `getMore` handlers added
* sequential ID generated for new cursors
* cursor stored within `ConnInfo` structure
* cursor carries documents iterator and a transaction

**Comment by AlekSi** [comment]
Reopening for tests refactoring

**Comment by AlekSi** [comment]
Closing because it is _almost_ done :)
