### ISSUE TITLE
Replace should not sort keys

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1736]
MongoDB doesn't sort data for both upsert and non-upsert updates without any operator, but FerretDB [does](https://github.com/FerretDB/FerretDB/pull/1735), we need to fix that.

Fixing this issue should not be complicated, we just need to remove the [sort function call ](https://github.com/FerretDB/FerretDB/blob/3e28163606eedc26d5a4dd9e1213671577d672b1/internal/handlers/common/update.go#L121) and check if there was any reason behind it. We also need to create test cases for this and integrate them into compatibility tests if possible.

For update's `$set` and probably other update operator both MongoDB and FerretDB sorts the data before insert.

There is an issue with using the update command from the mongo-go-driver or mongosh, as it requires providing an atomic operator such as $set. However, it is possible to reproduce this issue by using the replaceOne command. The test case is provided in the comments.

Testing things via `mongo-test` might be blocked by #1850 but unnecessary. I've provided temporary fix that make running `mongo-test` possible in comments.

### DoD
- [ ] Make FerretDB to not sort documents on replace operations
- [ ] Create test cases for that

### Versions

v0.8.0

### What did you do?

See repro in https://github.com/FerretDB/FerretDB/pull/1735

### What did you expect to see?

The order of keys unchanged. 

### What did you see instead?

That the keys were sorted.

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go1.19.3 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 20.10.16
```

**Comment by rumyantseva** [comment]
TODO for preparation: check similar cases (e.g. update, not only upsert)

**Comment by noisersup** [comment]
Replace test with upsert:
```go
func TestReplace(t *testing.T) {
	setup.SkipForTigris(t)

	t.Parallel()
	ctx, collection := setup.Setup(t, shareddata.Scalars)

	expected := bson.D{{"_id", int32(1)}, {"c", int32(1)}, {"b", int32(2)}, {"a", int32(3)}}

	_, err := collection.ReplaceOne(ctx, bson.D{{"_id", 1}}, expected, options.Replace().SetUpsert(true))
	require.NoError(t, err)

	res := collection.FindOne(ctx, bson.D{{"_id", 1}})

	var actual bson.D
	require.NoError(t, res.Decode(&actual))

	assert.Equal(t, expected, actual)
}

```

**Comment by noisersup** [comment]
To run `mongo-test` task you can temporary replace tls arguments and just connect to `task run` instance
```
 mongo-test:
     desc: "Run legacy MongoDB shell (`mongo`) with test script"
     cmds:
       - >
         docker compose run --rm legacy-mongo-shell
-        --tlsCertificateKeyFile /etc/certs/server.pem
-        --tlsCAFile /etc/certs/rootCA.pem
-        --tls
-        'mongodb://username:password@host.docker.internal:27017/?authMechanism=PLAIN'
+        'mongodb://host.docker.internal:27017/?heartbeatFrequencyMS=300000'
         /legacy-mongo-shell/test.js

``

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/pull/1946#discussion_r1104026810
