### ISSUE TITLE
Inserting large `int64` on tigris returns schema validation failure

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1749]
### What should be done?

Added few big positive and negative number to `Int64s` dataset, they are verge of overflow but not overflow, tigris does not insert them and returned schema validation failure.
```
		"int64-max-overflow-verge": 9.223372036854776832e+18,
		"int64-min-overflow-verge": -9.223372036854776832e+18,
```

Also attempted to add overflow numbers too, they also got the same schema validation failure. This is more expected given they are not int64.
```
		"int64-max-overflow":       9.223372036854776833e+18,
		"int64-min-overflow":       -9.223372036854776833e+18,
```
This error was received
```
                Error:          Received unexpected error:
                                bulk write exception: write errors: [json schema validation failed for field 'v' reason '9223372036854776000 is not valid 'int64'']
                Test:           TestQueryEvaluationCompatMod
                Messages:       Int64s: handler "tigris", collection
```

### Where?

https://github.com/FerretDB/FerretDB/blob/049f456aab3a18c85d7d2ac6c3bb136145fe4877/integration/shareddata/scalars.go#L281

### Definition of Done

- unit tests added;
- integration tests added;
- compatibility tests added;
- spot refactorings done;
- user documentation updated;
- something else?

**Comment by rumyantseva** [comment]
If the field is defined in Tigris correctly, it works. See the demo here: https://github.com/FerretDB/tigris-experiments/blob/fbf4198bc30eb5a201f1246797c3bab5ee3ffbe7/main.go.

I think the problem is that we define the wrong schema for Tigris collection in the given case.

**Comment by chilagrow** [comment]
Closing since it wasn't actually an issue
