### ISSUE TITLE
Implement `logout` command

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1750]
### What should be done?

https://www.mongodb.com/docs/manual/reference/command/logout/

We should implement that command despite it being deprecated (it's needed for [tests](https://github.com/mongodb/mongo/blob/r6.0.3/jstests/core/auth2.js)).

It should be implemented in the common handler, with other handlers using a common implementation.
It should call `ConnInfo.SetAuth("", "")` to remove authentication information.

### Where?

- https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/handlers.go
- https://github.com/FerretDB/FerretDB/tree/main/internal/handlers/common
- https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/msg_listcommands.go
- https://github.com/FerretDB/FerretDB/tree/main/integration

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated.

**Comment by kropidlowsky** [comment]
@AlekSi Can I work on this one??

**Comment by AlekSi** [comment]
Sure!
