### ISSUE TITLE
Better file extensions for test certificates

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1758]
Currently, all the certificates in the `build/certs` directory have `*.pem` extension.

This is quite confusing, and I suggest renaming it to more convenient names with `*.crt` extensions for certificates and `*.key` extensions for keys. Quite often, only combination of `cert` and `key` has `*.pem` extension.

Things to change:
- [Makefile](https://github.com/FerretDB/FerretDB/blob/main/build/certs/Makefile).
- Rename existing files to the correct names.
- Try calling `make` to ensure it generates correct names.
- Check filename occurrences in the source code to ensure we use correct (new) names everywhere.

DoD:
- Tests pass

**Comment by AlekSi** [comment]
> This is quite confusing, and I suggest renaming it to more convenient names with `*.crt` extensions for certificates and `*.key` extensions for keys. Only PEM format (combination of `cert` and `key`) should have `*.pem` extension.

All those files are in [PEM format](https://www.rfc-editor.org/rfc/rfc7468). And it is not clear if you propose to change names or extensions. Please update title/description.

**Comment by rumyantseva** [comment]
Ok, then I think it's not so important. I updated the text but we can close the issue.
