### ISSUE TITLE
Test error messages for update compat tests

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#1772]
### What should be done?

in `testUpdateCompat` we should test more than just error codes for writeErrors. We expect to have some failing cases afterwards (especially for `$rename` operator), every of them should be fixed. Smaller differences should be covered with `altMessage` field, which is also in the scope of this issue. As in some integration tests - if `altMessage != ""`, we should compare it's content with target's error.

## DoD
- [ ] Comparing `writeError` messages in `testUpdateCompat` helper.
- [ ] Implementing `altMsg` string field in `updateCompatTestCase`
- [ ] Fixing error differnces (especially in `$rename`)

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/issues/2345#issuecomment-1494035888

Please leave it open for now
