### ISSUE TITLE
`distinct` for array -> object -> array doesn't work correctly

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1828]
### Versions

Current main

### What did you do?

```
db.pampam.insert({
    _id: 'array-documents-nested',
    v: [
      { foo: [ { bar: 'hello' }, { bar: 'world' } ] }
    ]
  })

db.pampam.distinct("v.0.foo")
db.pampam.distinct("v.foo")
```

Check other places where dot notation was used.

Also, see #1724.

### What did you expect to see?

Both `db.pampam.distinct("v.0.foo")` and `db.pampam.distinct("v.foo")` should give the same response:

```
[ { bar: 'hello' }, { bar: 'world' } ]
```

### What did you see instead?

`db.pampam.distinct("v.foo")` gives an empty response

**Comment by rumyantseva** [comment]
Similar use case with dot notation: https://github.com/FerretDB/FerretDB/issues/1828

**Comment by rumyantseva** [comment]
Estimation is removed because it should be covered in #1724 (which is already M).

**Comment by AlekSi** [comment]
Let's wait for Tigris to support `foo.0.bar` access

**Comment by AlekSi** [comment]
It works now
