### ISSUE TITLE
Add Markdown linter / formatter for tables

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1846]
###  Goal

Everyone formats tables the same way, so no merge conflicts when two people format the same table in parallel PRs.

### What should be done?

`davidanson/markdownlint-cli2` does not support linting / formatting of Markdown tables. We should add another linter / formatter that could ensure that out tables in documentation use the same style.

Maybe our existing Prettier supports that already. If yes, we probably should use it.

One possible option is https://github.com/remarkjs/remark-lint.

Ideally, we want the linter not only to complain but format too.

Idea: check if there is a linter for docusaurus tables.

### Where?

Our build system and `task docs-fmt`.

### Definition of Done

- tool is packaged as dep if needed and added;
- CI passes;
- manual testing performed.

**Comment by KrishnaSindhur** [comment]
i can pick this
