### ISSUE TITLE
Understand Sessions

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1858]
### What should be done?

Refs #1833.

- [x] Read and understand [Driver Sessions Specification](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#driver-sessions-specification)
- [x] Read and understand [Server Sessions](https://www.mongodb.com/docs/manual/reference/server-sessions/#server-sessions)
- [x] Read and understand [Client Sessions](https://www.mongodb.com/docs/manual/release-notes/3.6/#client-sessions)
- [x] Write and run [Prose tests](https://github.com/mongodb/specifications/tree/master/source/sessions/tests#id3) to understand spec better
    - [prose test 8](https://github.com/b1ron/hello-mongodb/blob/f2e8ea581d59bdc79fa258001ff8f18f9908b484/tests/prose8_test.go)
    - [prose test 9](https://github.com/b1ron/hello-mongodb/blob/f2e8ea581d59bdc79fa258001ff8f18f9908b484/tests/prose9_test.go)

**Comment by b1ron** [comment]
Transactions are quite complex so maybe that needs its own issue. Would it be a bit cheeky to use incorporate `mtest` in our integration tests? It uses internal packages which we cannot use AFAIK. [This](https://github.com/mongodb/mongo-go-driver/blob/b1e7aa5b82b06ebfc32b035757cef43ac03e8869/mongo/integration/sessions_test.go#L630) is an example of a useful function to avail of. @w84thesun thoughts?

**Comment by noisersup** [comment]
Removed transactions from the scope

**Comment by b1ron** [comment]
## Summary

Below is a somewhat brief summary of relevant information on server sessions specific to causal consistency. I will not mention transactions here at all. When I use the term session it is implied I am talking about explicit causally consistent sessions unless mentioned otherwise.

Server sessions provide the framework for causal consistency. Applications use [client sessions](https://www.mongodb.com/docs/manual/release-notes/3.6/#std-label-3.6-client-sessions) to interface with server sessions.

Causal consistency is a way to guarantee that operations that logically depend on one another are performed in a consistent order, and clients observe results that are consistent with the causal relationships. Except in a rare case which I will touch on later.

Client sessions only guarantee causal consistency for [specific read and write concerns](https://www.mongodb.com/docs/manual/core/causal-consistency-read-write-concerns/).

When a client starts a session and issues a sequence of operations it will send a session ID with each command. The associated client session tracks the [`clusterTime`](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#clustertime) and [`operationTime`](https://github.com/mongodb/mongo-go-driver/blob/88c138b00c2caa6bc20a4371ea9653d0e9a17cc9/x/mongo/driver/session/client_session.go#L245-L263). A client session will retrieve the cluster time by examining all responses from the server and will advance the operation time and the cluster time. It will only send the highest seen cluster time in a subsequent command.

The above time-stamping technique prevents a client session to return results that correspond to an earlier state of the data.

A client session may also chose to manually advance the cluster time and the operation time to that of another session to ensure that it is causally consistent with that other session.
