### ISSUE TITLE
when authMechanism is NOT "PLAIN" we get error MongoServerError: Unsupported mechanism 'PLAIN'

### ISSUE THREAD

**Issue by Turkish** [FerretDB/FerretDB#1876]
### Versions

0.8.1

### What did you do?

try to connect with mongosh without specifying the authMechanism option. The default being SCRAM-SHA-1.

### What did you expect to see?

I expected to see MongoServerError:  Unsupported mechanism 'SCRAM-SHA-1' 

### What did you see instead?

MongoServerError: Unsupported mechanism 'PLAIN'

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Go:
- Git:
- Deployment:Docker
- Deployment details:
```

**Comment by AlekSi** [comment]
Thank you! That issue will be fixed in 0.9.0 release later today
