### ISSUE TITLE
Enforce new authentication

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1877]
### What should be done?

When new authentication is enabled (by a flag or environment variable), it should be checked at the beginning of every command handler, not in the backend.
When new authentication is not enabled, it should be checked by backends as before.

With #3784 implemented, we should also add integration tests (for new authentication only).

Commands that do not require authentication are:
- `hello`
- `ping`
- `isMaster`
- `whatsmyuri`
- `buildInfo`
- `authenticate`
- `connectionStatus`
- `saslStart` 
- `saslContinue`
- `logout`

### Where?

Handler, backends.

### Definition of Done

- handler updated;
- all backends updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- **[user documentation](https://docs.ferretdb.io/security/authentication/) updated**.

**Comment by b1ron** [comment]
Commands that do not require authentication are:

- `hello`
- `ping`
- `whatsmyuri`
- `buildInfo`
- `authenticate`
- `connectionStatus`
- `isMaster`
