### ISSUE TITLE
Add subtests for compat query tests

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1906]
### What should be done?

All query compat tests runs in a single test, this makes it difficult for running a single test with goland test tool (?). Having sub tests would make debugging easier.

### Where?

https://github.com/FerretDB/FerretDB/blob/d6506f74b960ae1889aff843144d438a4d09c0bf/integration/query_compat_test.go#L154

### Definition of Done

- compat test for query updated.
- something else?

**Comment by chilagrow** [comment]
@w84thesun does this sound sensible for your need?

**Comment by AlekSi** [comment]
I'm pretty sure it is possible to run subtests in GoLand. For example, the first thing I found: https://www.jetbrains.com/go/guide/tips/run-test-in-table-test/

**Comment by AlekSi** [comment]
Done in #2054
