### ISSUE TITLE
Allow empty strings pushdown for Tigris

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#1940]
### What should be done?

After the proper fix (see references to this issue in code), we should be able to remove the additional check for empty strings in Tigris `BuildFilter` method.

- [ ] Update skipped test
- [ ] Remove empty field check

**Comment by AlekSi** [comment]
> After the proper fix (see references to this issue in code)

It seems to be fixed already: https://github.com/FerretDB/tigris-experiments/pull/12#issuecomment-1445916481
