### ISSUE TITLE
Document query pushdown

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1956]
### What should be done?

Let's document what query pushdown is and how it works.

It could be a simple page for docs.ferretdb.io that mentions basic things and links our blog post about query pushdowns.

It might make sense to mention what we already pushdown and what not (e.g. the state of operators like `$eq`, `$nin` etc). 

The thread with some more context: https://ferretdb.slack.com/archives/C02NWN1K3MJ/p1676277971105489

**Comment by noisersup** [comment]
A tiny reminder for us in the future that we can reuse our blogpost drafts for this one!
