### ISSUE TITLE
Add `buildEnvironment` and `debug` to `buildInfo` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#199]
We already have basic `buildInfo` command implementation, but it misses `buildEnvironment ` and `debug` response field.
For `buildEnvironment`, let's use the result of `runtime/debug.BuildInfo.Settings` field.
For `debug`, let's set it to `true` if FerretDB is built with race detector (buildinfo contains `-race=true`) or test coverage enabled (buildinfo contains `-tags=` line with `testcover` tag).

**Comment by GinGin3203** [comment]
Hey @AlekSi mind if I take this one?

**Comment by AlekSi** [comment]
Sure. Updated description a bit.
