### ISSUE TITLE
Handle unordered `insert` with implicit transaction

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#200]
When inserting documents with `ordered` set to `true` (which should be set as a default value), insert documents one-by-one in seperate transactions, skip invalid documents (for example, with _id values that are already present) and return errors just for them.

With `ordered` set to false, attempt to insert all documents in one transaction.

See https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/

**Comment by ekalinin** [comment]
Please, correct me if I'm wrong, but it looks like MongoDB works oppositely at the moment.

From [insert's doc](https://docs.mongodb.com/manual/reference/method/db.collection.insert/#mongodb-method-db.collection.insert):

> If true, perform an ordered insert of the documents in the array, and if an error occurs with one of documents, MongoDB will return without processing the remaining documents in the array.
> If false, perform an unordered insert, and if an error occurs with one of documents, continue processing the remaining documents in the array.

From [insertMany's doc](https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/#error-handling):

> Excluding Write Concern errors, ordered operations stop after an error, while unordered operations continue to process any remaining write operations in the queue.

Or did I miss something?

**Comment by AlekSi** [comment]
The documentation is a bit confusing. I will write an integration test to see how MongoDB behaves.

**Comment by AlekSi** [comment]
I added tests: https://github.com/FerretDB/dance/blob/main/tests/ferret/core_test.go In short, an unordered insert saves all valid documents, while an ordered insert stops on the first error while still saving previous documents. Both cases do not fit all-or-nothing PostgreSQL transactions.

In theory, we could optimize the performance of the happy path: insert all documents in a single implicit transaction; in case of error, retry inserts one by one. But that sounds weird.

@pboros WDYT?

**Comment by AlekSi** [comment]
It looks like we could use [`ON CONFLICT`](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) `INSERT` clause to ignore some errors like duplicate IDs, but that would not work for some other errors (but what are they?)

**Comment by noisersup** [comment]
As agreed on a call this one is moved to #940.
