### ISSUE TITLE
Improve `find`/`getMore` `batchSize`/`singleBatch` handling

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2005]
### What should be done?

Those methods handle corner cases (unset `batchSize`, 0 value, float value, etc) differently. See https://www.mongodb.com/community/forums/t/mis-understanding-batchsize/169713/2

We should test all combinations.

DOD:
- [ ] `batchSize` accepts float value.
- [ ] cursor returns number of documents set by `batchSize`.
- [ ] when `batchSize` is unset, cursor returns default `batchSize` 101 documents in `firstBatch`.
- [ ] when `batchSize` is unset, cursor returns remaining documents in `secondBatch`.
- [ ] calling `getMore` using `cursorID` gets more documents.
- [x] driver sets  `singleBatch` for negative `limit(-1)` on `find`, no matter the `batchSize`
- [ ] See issue number added in https://github.com/FerretDB/FerretDB/pull/2825

**Comment by kropidlowsky** [comment]
Hi @AlekSi,

Can I work on this one?

**Comment by AlekSi** [comment]
@kropidlowsky Unfortunately, we are in the process of moving and changing the surrounding code, so that's not the best issue to work on right now

**Comment by AlekSi** [comment]
For example: https://github.com/FerretDB/FerretDB/blob/d38ab72dcb0ff0a9cafd8c81050713211669b94a/internal/handlers/common/getmore.go#L60-L64
