### ISSUE TITLE
Support `SCRAM-SHA-1` authentication mechanism

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2012]
### What should be done?

* https://www.mongodb.com/docs/manual/core/security-scram/

**Comment by Neustradamus** [comment]
@AlekSi: SCRAM-SHA-1 is needed too, do not forget!

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/FerretDB/FerretDB/issues/2012
- https://github.com/FerretDB/FerretDB/issues/3784
- https://github.com/FerretDB/FerretDB/pull/3904
- https://github.com/FerretDB/FerretDB/issues/3938
- https://github.com/FerretDB/FerretDB/pull/3970
- https://github.com/FerretDB/FerretDB/pull/3989
