### ISSUE TITLE
Implement the `$sum` aggregation operator

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2013]
After #2226. 

https://www.mongodb.com/docs/v6.0/reference/operator/aggregation/sum/

DoD:
- [x] only for `$group` stage (as everything else is not implemented yet)
- [x] consider overflow cases
- [x] regular test cases: `$v` already includes non-mixed (only numeric) and mixed cases (e.g. numeric + non-numeric, arrays etc)
- [x] constant test case: (`{ $sum: 1 }`)

**Comment by rumyantseva** [comment]
A possible approach: when provide a test case, sort first and then sum. E.g. sort might be set by abs value (from min to max).

**Comment by chilagrow** [comment]
I used skip edge case approach. For sorting with abs value, that would probably the way we want to solve it! But that has to be implemented internally.
