### ISSUE TITLE
Format index names in PG, so the length limit is not reached

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2044]
With table names like `TestInsertCompat-InsertUnorderedOneError-InsertMany_St_4c6d95fa` the "default" index name could be something like `TestInsertCompat-InsertUnorderedOneError-InsertMany_St_4c6d95fa_field`, and then we reach the limit of index name. In such case, PG automatically truncates it, and it produces the same name for everything.

We should find a way to create indexes for long table names. 
One possible option is not format index names in a similar way to how we format collection->table names, so we ensure that the index name is not too long.

Metadata to consider storing:

- v
- key
- name
- unique

**Comment by AlekSi** [comment]
It is a part of #1384
