### ISSUE TITLE
Fix invalid namespace error

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#2065]
Please update title and description.

---

### Versions

v0.9.2

### What did you do?

See references to this issue.

### What did you expect to see?

Tests pass.

### What did you see instead?

Tests are skipped.

### Environment

```markdown
https://github.com/FerretDB/FerretDB/actions/runs/4287706440/jobs/7468887085
```

**Comment by chilagrow** [comment]
This is for tigris handler right @w84thesun ?
