### ISSUE TITLE
Update PRs to use `test.js` file only

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2070]
Revert changes in `test.example.js`, resolve merge conflicts.
 
* FerretDB/FerretDB#1735
* FerretDB/FerretDB#1741
* FerretDB/FerretDB#1743
* FerretDB/FerretDB#1854
* FerretDB/FerretDB#1988

**Comment by AlekSi** [comment]
This task _is_ about resolving merge conflicts.

We need those PRs to be conflict-free. We could keep them as drafts or even close them after conflicts are resolved. Once the issues they reproduce are being worked on, we could re-open and re-wind them with the "Update branch" button to be up-to-date to demonstrate the issue again.

**Comment by b1ron** [comment]
I resolved all merge conflicts. I have effectively reverted all `test.js` files to their original state. I will close them as well.

**Comment by AlekSi** [comment]
All those PRs are empty now:
* https://github.com/FerretDB/FerretDB/pull/1735/files
* https://github.com/FerretDB/FerretDB/pull/1741/files
* https://github.com/FerretDB/FerretDB/pull/1743/files
* https://github.com/FerretDB/FerretDB/pull/1854/files
* https://github.com/FerretDB/FerretDB/pull/1988/files
