### ISSUE TITLE
Improve fuzzing with recorded seed data

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2100]
### What should be done?

`task test-unit` might be surprisingly slow due to a lot of files in the `tmp/records` directory accumulated by integration tests.

We should make the following improvements:
* store recorded files in nested directories and files matching their SHA-256 hashes without timestamps and random values (for example, given hash `abcdef[...]`, store file in `tmp/records/ab/abcdef[...].bin`);
* make `loadRecords` load up to random 1000 files.

### Where?

* https://github.com/FerretDB/FerretDB/blob/main/internal/clientconn/conn.go
* https://github.com/FerretDB/FerretDB/blob/main/internal/wire/records_test.go

### Definition of Done

- unit tests updated;
- spot refactorings done.

**Comment by AlekSi** [comment]
@fenogentov Could we help you with something?

**Comment by fenogentov** [comment]
> @fenogentov Could we help you with something?

Yes. I need help 
I can't get data in folder /records
