### ISSUE TITLE
Support dot notation in sorting

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2101]
_See the comments for implementation details_

### Versions

0.9.2

### What did you do?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/sort_documents.go#L57

Sorting currently does not handle dot notation.

Example: this won't work
```
[{"$sort": {"v.foo": 1}]
```

DOD:
* add test case `v.0` for each command
* add test case `v.foo` for each command

### What did you expect to see?

Dot notation is used for sorting

### What did you see instead?

See the link above

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Go:
- Git:
- Deployment:
- Deployment details:
```

**Comment by rumyantseva** [comment]
Fixed in the following parts of code:
- `aggregation`
- `find`
- `findAndModify`
