### ISSUE TITLE
Add coveralls.io integration

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2106]
There are issues with the current state of codecov.io (see comments). So let's add integration with https://coveralls.io. The current integration with codecov.io should stay.

Let's use https://github.com/marketplace/actions/coveralls-github-action v2 on GitHub Actions. Let's _not_ use https://github.com/mattn/goveralls or other third-party integrations.

`flag-name` parameter should be set – that's the main reason we want to try Coveralls

DoD:
- coveralls-github-action  is in use

**Comment by noisersup** [comment]
@rumyantseva PTAL

**Comment by AlekSi** [comment]
Could you also describe how that's different from what we have now?

**Comment by noisersup** [comment]
We upload coverage information from both `integration-{handler}.txt` files and `cover.txt` file which stores coverage from unit tests.

In scenario, when some place in code is covered by unit tests, but not the integration one, we don't get any notification about that, and presumably we could introduce new bugs.

**Comment by AlekSi** [comment]
Well, we do use different flags for unit and integration tests:
* https://github.com/FerretDB/FerretDB/blob/a14c1a996f5cef898bd1f81636c0f550d9dfcc18/.github/workflows/go.yml#L111
* https://github.com/FerretDB/FerretDB/blob/a14c1a996f5cef898bd1f81636c0f550d9dfcc18/.github/workflows/integration.yml#L87
* https://app.codecov.io/gh/FerretDB/FerretDB/flags

**Comment by AlekSi** [comment]
Ah, it seems that codecov.io now requires additional YAML configuration to make use of them; previously, they were used automatically. https://docs.codecov.com/docs/flags#step-2-flag-management-in-yaml

**Comment by AlekSi** [comment]
https://youtu.be/ZYEsHHohgqo?t=252 – there was an ability to enable/disable flags by clicking, but I can't find it now 🤯

**Comment by AlekSi** [comment]
https://codecov.canny.io/customer-requests/p/view-source-with-flags
