### ISSUE TITLE
Aggregation pipeline result is not deterministic order 

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2117]
### What should be done?

Aggregation pipeline tests are added in https://github.com/FerretDB/FerretDB/pull/2099

Compat and Target returns documents in different order. They are not sorted by `_id`. The possibility is that they may be the order of documents being added. If this is the case, our integration test setup should always add documents in the same order. Currently order is indeterminate https://github.com/FerretDB/FerretDB/blob/main/integration/shareddata/shareddata.go#L180

Example of difference in order for `bson.D{{"$match", bson.D{{"v", 42}}}},`
```
Compat Order
        	            	expected: [
        	            	    "_id": "array-numbers-asc",
        	            	    "_id": "array-composite",
        	            	    "_id": "array-three",
        	            	    "_id": "array",
        	            	    "_id": "array-three-reverse",
        	            	]
Target Order
        	            	actual  : [
        	            	    "_id": "array",
        	            	    "_id": "array-three-reverse",
        	            	    "_id": "array-numbers-asc",
        	            	    "_id": "array-composite",
        	            	    "_id": "array-three",
        	            	]
```

### Where?

https://github.com/FerretDB/FerretDB/blob/main/integration/shareddata/shareddata.go#L180

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
Let's fix it by adding `$sort` right now
