### ISSUE TITLE
Achieve compatibility with FastNetMon

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2161]
https://github.com/pavel-odintsov/fastnetmon

```[tasklist]
### Tasks
- [ ] #2164
- [ ] #1517
- [ ] #2387
- [ ] #2760
- [ ] #2340
```

**Comment by AlekSi** [comment]
@pavel-odintsov Another option could be to use [MongoDB URI](https://www.mongodb.com/docs/manual/reference/connection-string/) instead of multiple arguments

**Comment by AlekSi** [comment]
@pavel-odintsov Another option could be to use [MongoDB URI](https://www.mongodb.com/docs/manual/reference/connection-string/) instead of multiple arguments

**Comment by pavel-odintsov** [comment]
I agree that it may offer more flexibility but we control environment from our installation app in almost never customers need to change it.

**Comment by ptrfarkas** [comment]
@pavel-odintsov let us know if you were able to release and test it, we are interested in the result. Thank you!

**Comment by AlekSi** [comment]
I think we could claim full compatibility (and tell everyone about it) after we implement the basic SQLite support + `renameCollection` for that backend

**Comment by AlekSi** [comment]
@pavel-odintsov Are there some FastNetMon integration tests that use an real MongoDB / FerretDB instance? Then, we could run them to ensure that we don't regress.

**Comment by yu-re-ka** [comment]
I don't see a way to use sqlite backend with fastnetmon advanced because fastnetmon advanced has no (documented) option to disable authentication, while the sqlite backend does not support authentication.

**Comment by AlekSi** [comment]
@yu-re-ka @pavel-odintsov please tell us more :)

@b1ron PTAL

**Comment by yu-re-ka** [comment]
The only information I have is this documentation ;)
https://fastnetmon.com/docs-fnm-advanced/mongodb-integration-with-fastnetmon-advanced/

**Comment by pavel-odintsov** [comment]
Hello!

Please check this guide
https://fastnetmon.com/using-fastnetmon-advanced-with-ferretdb-and-sqlite-backend-instead-of-mongodb/

You can use our official installer to deploy it that way:

wget https://install.fastnetmon.com/installer -Oinstaller
sudo chmod +x installer
sudo ./installer -ferretdb

After that you can just upgrade FerretDB daemon.

**Comment by yu-re-ka** [comment]
Ohhhh fancy! So the solution is to set mongodb_username to an empty string. thank you.

**Comment by pavel-odintsov** [comment]
Hello!

Yes, right. You may need to upgrade daemon to latest version as we added
this option not long time ago.
