### ISSUE TITLE
Build `arm/v7` `.deb` and `.rpm` packages and binaries

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2171]
### What should be done?

After #2170 and goreleaser/nfpm#719, building packages and binaries for this architecture should be easy.

### Where?

Taskfile, CI configuration, release checklist, etc.

### Definition of Done

Those packages are provided.

**Comment by pavel-odintsov** [comment]
That will be great thing to have as we have native ARM64 builds and will be nice to switch them away from MongoDB too.

**Comment by pavel-odintsov** [comment]
May I kindly ask about progress with ARM64? Would love to be early adopter. We plan to use it on Graviton.

**Comment by AlekSi** [comment]
@pavel-odintsov It is tricky for us to provide `.deb` and `.rpm` packages for multiple architectures right now. In the meantime, you could extract binaries from our [multi-arch Docker images](https://github.com/FerretDB/FerretDB/pkgs/container/ferretdb/131145454?tag=latest).

**Comment by AlekSi** [comment]
Ok, I think we can do it now :)

**Comment by pavel-odintsov** [comment]
Great news! We will be happy to test it right after as we are finishing
ARM64 support.

**Comment by AlekSi** [comment]
The next release will ship with `arm64` binaries and packages. See the preview artifacts there: https://github.com/FerretDB/FerretDB/actions/runs/6378917049

---

This issue now tracks `arm/v7` binaries and packages.

**Comment by pavel-odintsov** [comment]
Awesome. Thank you very much!

**Comment by AlekSi** [comment]
`arm/v7` binaries and packages will be available in the next release
