### ISSUE TITLE
Aggregation tests for `$group` to return deterministic order in compat and target

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2184]
### What should be done?

In `$group` aggregation Scalars dataset is skipped because aggregation grouped by value (`{"_id", "$v"}`) groups numbers of different types, and this causes output `_id` to be different number type between compat and target.

```
bson.D{{"$group", bson.D{
					{"_id", "$v"},
				}}},
```

It could be due to compat and target uses different order of insertion of documents.

### Where?

See the issue number in the code

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
The simplest option could be to never change _id in tests so we could always sort by it

**Comment by AlekSi** [comment]
Alternatively, sort by _id before doing grouping

**Comment by chilagrow** [comment]
This issue is completed
