### ISSUE TITLE
`distinct` returns invalid error type

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2231]
After #2529

### Versions

commit.txt: 8667e7e215bc3b9327eb76d735499f74ba1f2952
branch.txt: main
version.txt: v0.9.3-15-g8667e7e2

### What did you do?

See repro in https://github.com/FerretDB/FerretDB/pull/2230.

### What did you expect to see?

```
> t.runCommand("distinct", {"key": {a: 1}})
{
	"ok" : 0,
	"errmsg" : "BSON field 'distinct.key' is the wrong type 'object', expected type 'string'",
	"code" : 14,
	"codeName" : "TypeMismatch"
}
```

### What did you see instead?

```
> t.runCommand("distinct", {"key": {a: 1}})
{
	"ok" : 0,
	"errmsg" : "required parameter \"key\" has type *types.Document (expected string)",
	"code" : 2,
	"codeName" : "BadValue"
}
```

---

As #2481 demonstrates, we can't just change an error type in `GetRequiredParam` helper – some commands return `ErrTypeMismatch` while others return `ErrBadValue`.

Ideally, we should avoid adding _yet another_ similar-but-not-identical helper with a vague name. Maybe we could just™ add a parameter to that existing function.

DoD:
- check if new way to extract params fixed this problem, check for TODOs, add a test.

**Comment by chilagrow** [comment]
This is already fixed, see passing test script
https://github.com/FerretDB/FerretDB/pull/2230
https://github.com/FerretDB/FerretDB/actions/runs/5043694772
