### ISSUE TITLE
Allow query param is be of type `null` in `distinct` command

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2236]
### Versions

commit.txt: https://github.com/FerretDB/FerretDB/commit/8667e7e215bc3b9327eb76d735499f74ba1f2952
branch.txt: main
version.txt: v0.9.3-15-g8667e7e2

### What did you do?

See repro in https://github.com/FerretDB/FerretDB/pull/2235.

### What did you expect to see?

`null` to be treated as an empty document in the query.

### What did you see instead?

```
uncaught exception: Error: command failed: {
        "ok" : 0,
        "errmsg" : "BSON field 'query' is the wrong type 'null', expected type 'object'",
        "code" : 14,
        "codeName" : "TypeMismatch"
} with original command request: { "distinct" : "allow_null", "key" : "a", "query" : null }
```

### Implementation

In `GetDistinctParams`, we should use `GetOptionalNullParam` instead of `GetOptionalParam` for `query`. And add tests.

**Comment by rumyantseva** [comment]
@b1ron I unassigned the issue from you because it needs clarification what should be done.
