### ISSUE TITLE
Document `createIndexes` command

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2271]
### What should be done?

Things to mention:

- `createIndexes` called for a non-existent collection will create the collection, and the given indexes;
- `createIndexes` called for a non-existent field creates index for this field;
- attempt to call `createIndexes` for an index that already exists (when the name and the key are equal) will return index name but will not create a duplicate index.
- attempt to call `createIndexes` for same name and different keys or same keys but different names will return an error.

**Comment by AlekSi** [comment]
Why we want that to be documented and where?
