### ISSUE TITLE
bulk write exception: write errors

### ISSUE THREAD

**Issue by Nyx2022** [FerretDB/FerretDB#2279]
### Versions

0.9.3

### What did you do?

migrate mongo to ferretDB

### What did you expect to see?

work well

### What did you see instead?

as written in  doc,ferret will auto create collection when i write to a unexist one ,but i call *mongo.Collection.InsertMany to write data to ferretdb,it occurs the error:
bulk write exception: write errors: [Invalid namespace: XXX.xxxxx]

also if i use navicat connect ferretdb as mongo,and create collection ,it will occur as follow
![image](https://user-images.githubusercontent.com/51039208/227476928-9c743a8a-136f-4ca5-bbef-a45b999d4310.png)

### Environment

```markdown
- OS: Windows
- Architecture: X64
- Version: 0.9.3
- Deployment: Docker or Golang Embed
- Deployment details:
```

**Comment by AlekSi** [comment]
@Nyx2022 Please try with `ghcr.io/ferretdb/ferretdb-dev:main` image – it is likely already fixed in the `main` branch. If not,  please provide request and response from FerretDB logs.

**Comment by Nyx2022** [comment]
> 

i tried ghcr.io/ferretdb/ferretdb-dev:main,it occurs the error:
(InternalError) [msg_find.go:38 pg.(*Handler).MsgFind] [pg.go:130 pg.(*Handler).DBPool] pgdb.NewPool: failed to connect to `host=127.0.0.1 user=root database=ferretdb`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)

**Comment by Nyx2022** [comment]
> @Nyx2022 Please try with `ghcr.io/ferretdb/ferretdb-dev:main` image – it is likely already fixed in the `main` branch. If not, please provide request and response from FerretDB logs.

https://github.com/FerretDB/FerretDB/issues/2279#issuecomment-1482490159

**Comment by Nyx2022** [comment]
> > @Nyx2022 Please try with `ghcr.io/ferretdb/ferretdb-dev:main` image – it is likely already fixed in the `main` branch. If not, please provide request and response from FerretDB logs.
> 
> i tried ghcr.io/ferretdb/ferretdb-dev:main , howerver, it also has the error bulk write exception: write errors: [Invalid namespace: XXX.xxxxx]
> 
> where can i get FerretDB logs in docker

perhaps igotthe reason,i found ferretdb has a default database named "public",but i donot use it,i create another datatbase in navicat,so the error above occured,wish ferretdb can solve this problem

**Comment by AlekSi** [comment]
It is hard to tell what is going on without knowing the database name and having logs.

You could get Docker container logs with [`docker logs`](https://docs.docker.com/engine/reference/commandline/logs/).
