### ISSUE TITLE
Performance should be enhanced

### ISSUE THREAD

**Issue by Nyx2022** [FerretDB/FerretDB#2289]
### What should be done?

As a comparison。in windows,i store same data in a collection in mongo and ferretdb,the count is 490000+,i will get oen document from this collection. the mongo gwt result immediately,but the ferretdb will cost 10-12s

so i think ferretdb should enhance the performance or speed by sql optimize or other methods,thank u

**Comment by AlekSi** [comment]
We are working on improving the performance of FerretDB, but this issue is too generic to be actionable.
