### ISSUE TITLE
Collection Name shou not more than 120 chars

### ISSUE THREAD

**Issue by Nyx2022** [FerretDB/FerretDB#2290]
### Versions

0.9.3

### What did you do?

create a collection with name that length is more than 120 chars

### What did you expect to see?

work well

### What did you see instead?

get one error
![image](https://user-images.githubusercontent.com/51039208/227676079-c3995a13-4cba-457f-9802-a2b5b259136b.png)

### Environment

```markdown
- OS: windows
- Architecture: x64
- Version: 0.9.3
- Deployment: go embed
- Deployment details:
```

**Comment by AlekSi** [comment]
It is already fixed in the main branch that will be released as v0.9.4 today:

```
public> db.hjvhjgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggi.insertOne({})
{
  acknowledged: true,
  insertedId: ObjectId("64216582c435834409f1f8a5")
}
```
