### ISSUE TITLE
Projection with `_id` returns all fields

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2299]
### Versions

commit.txt: a06bd4bf1832bceed7189cff07d788cdb11e2155
version.txt: v0.9.4-1-ga06bd4bf

### What did you do?

See repro in #2298.

### What did you expect to see?

2 documents returned with just the `_id` field.

### What did you see instead?

All fields.

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go version go1.20 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 23.0.1
```

**Comment by AlekSi** [comment]
> See repro in https://github.com/FerretDB/FerretDB/pull/2298.

That PR should be re-opened and updated to check that this issue is indeed fixed
