### ISSUE TITLE
Improve embedded package documentation

### ISSUE THREAD

**Issue by egplat** [FerretDB/FerretDB#2326]
We should update code comments. See https://github.com/FerretDB/FerretDB/issues/2326#issuecomment-1496910188.

---

### Versions

0.9.3

### What did you do?

```
f, err := ferretdb.New(&ferretdb.Config{
		Listener: ferretdb.ListenerConfig{
			TCP: "127.0.0.1:17027",
		},
		Handler:       "pg",
		PostgreSQLURL: "postgres://127.0.0.1:5432/ferretdb", // ferretdb 对齐PostgreSQL的数据库
	})
	if err != nil {
		log.Fatal(err)
	}

ctx, cancel := context.WithCancel(context.Background())
uri := f.MongoDBURI()
fmt.Println(uri)
```

I created an instance of FerretDB using the code above, but did not run `FerretDB.Run()`. Then I tried to get the MongoDB uri, which caused the program to block at `<-l.tcpListenerReady` and ultimately resulted in a deadlock.

### What did you expect to see?

Not running FerretDB.Run() and then obtaining the MongoDB uri will not lead to a deadlock.

### What did you see instead?

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
https://github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).TCPAddr(...)
        /internal/clientconn/listener.go:321
https://github.com/FerretDB/FerretDB/ferretdb.(*FerretDB).MongoDBURI(0x1057920d8?)
        /ferretdb/ferretdb.go:186 +0xdc

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Deployment:
- Deployment details:
```

**Comment by AlekSi** [comment]
Unfortunately, starting embedded FerretDB with a `Run` method is required. For example, when the TCP address is `127.0.0.1:0`, we should first begin listening on a TCP socket to know the allocated port number. And we don't want to make `Run` sometimes required and sometimes not.

But I think we could explain it better in code comments / [documentation](https://pkg.go.dev/github.com/FerretDB/FerretDB/ferretdb). Could you send a PR?

**Comment by egplat** [comment]
收到！

**Comment by princejha95** [comment]
Will pick this up.

**Comment by egplat** [comment]
收到！

**Comment by princejha95** [comment]
> Unfortunately, starting embedded FerretDB with a `Run` method is required. For example, when the TCP address is `127.0.0.1:0`, we should first begin listening on a TCP socket to know the allocated port number. And we don't want to make `Run` sometimes required and sometimes not.
> 
> But I think we could explain it better in code comments / [documentation](https://pkg.go.dev/github.com/FerretDB/FerretDB/ferretdb). Could you send a PR?

On top of what @AlekSi mentioned, mongoDB URI is formed using the listener's address and in order to get that, listener has to be instantiated which is done by FerretDB.Run() method which implies the necessity of running it before getting mongo DB URI.

Please correct me if my understanding is wrong.

Thanks

**Comment by AlekSi** [comment]
That's correct
