### ISSUE TITLE
Do not check error messages in compatibility tests

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2345]
### What should be done?

We should update all our compatibility tests to _not_ compare error messages. `altMessage` and other similar things should not be present in compat tests. Additionally, let's add comments to `testXXXCompat` helpers where we compare error types, codes, and names, explicitly mentioning that we don't compare messages (i.e., we did not forget).

### Where?

Compat tests.

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by AlekSi** [comment]
Compat tests don't check error messages by design – that will make them much more dependent on the data, but we introduced compat tests to depend on the data less, not more.

Instead of checking error messages, let's add comments explaining that we don't do that explicitly.
