### ISSUE TITLE
Merge `aggregation.getPathValue()` and `common.getDocumentsAtSuffix()`

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2348]
### What should be done?

We introduced `getPathValue` handle array with index dot notation differently from `getDocumentsAtSuffix`. We should standardise them into one function with options

**types.GetByPath(...)**
We initially had one way to find by path with dot notation, it can only return one value because array is not iterated.
https://github.com/FerretDB/FerretDB/blob/9d75840bea854c84b766c9a8de0266439a394934/internal/types/document.go#L313
We introduced two more functions to iterates on array. They are different from `GetByPath(...)` because they can return multiple values with exception on `getPathValue(...)` with `IgnoreArrays` flag which doesn't look into array.

**types.getPathValue(...)**

https://github.com/FerretDB/FerretDB/blob/9536babb87ab2873de3383c684b837d30db49a75/internal/handlers/common/aggregations/expression.go#L199
used by `$group` stage, `$sum` accumulator and `$type` operator
`IgnoreArrays` flag used by `$unwind` stage. It disable array notations like `foo.bar` to access array items like `foo: [{bar:42}]`.

**types.getDocumentsAtSuffix(...)**
https://github.com/FerretDB/FerretDB/blob/c6eccb44f5838bf98f485ef2e5fb4e793c26dbca/internal/handlers/common/filter.go#L194
used by `distinct` and filtering documents.

**Differences**

|docs|path|`GetByPath(`|`getPathValue(`|`IgnoreArrays` |`getDocumentsAtSuffix(`|
|--|--|--|--|--|--|
|`{}`|`foo.bar`|`Err`|`[]`|`[]`|`[]`|
|`{foo: {bar: 1}}`|`foo.bar`|`1`|`[1]`|`[1]`|`[{bar: 1}]`|
|`{}`|`foo.0.bar`|`Err`|`[]`|`[]`|`[]`|
|`{foo: [{bar: 1}]}`|`foo.0.bar`|`1`|`[]`|`[]`|`[{bar: 1}]`|
|`{foo: [{bar: 1}, {bar: 2}]}`|`foo.bar`|`Err`|`[1,2]`|`[]`|`[{bar: 1}, {bar: 2}]`|

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/aggregations/expression.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/filter.go
### Definition of Done

- spot refactorings done;
- add unit tests for the new merged function, so we can reduce documentation and cover those in unit tests
- Merge `getPathValue` and `getDocumentsAtSuffix` and move it to somewhere accessible, in a separate package
- New function returns minimal response, something like `(suffix string, []any)` with `"bar", [1, 2]` for the last example
- Make it configurable for using *array notation* (i.e. `foo.bar`) and *array index notation* (i.e. `foo.0.bar`)
- Make new function work in `filter.go`, will require refactoring
- Make new function work in `expression.go`
- Don't touch `types.GetByPath(...)`, it will be too large for this issue. But welcome to make new function usable for it

**Comment by AlekSi** [comment]
Could we drop `IgnoreArrays`?
