### ISSUE TITLE
Add more tests for `$collStats` aggregation stage

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2349]
### What should be done?

Add tests for the following requests:
- `db.values.aggregate([{$count:"before"},{$collStats:{count:{}, storageStats:{}}},{$count:"after"}])`
- `db.values.aggregate([{$collStats:{count:{}, storageStats:{}}},{$count:"after"}])`

Also, check TODOs with the issue number for other possible cases, the error code is currently not correct.

### Where?

`integration/aggregate_stats_compat_test.go`
See also TODOs in the code.

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
The reference to this issue is still in the code

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/blob/eb63b1101f3fe9b51011f19ec50cd48dfbcf6713/internal/handlers/pg/msg_aggregate.go#L189

**Comment by chilagrow** [comment]
Thanks @AlekSi, I didn't touch pg handlers and also didn't remove todo's under pg handlers :sweat_smile: It goes for other issues as well. I can clean them all up :+1:
