### ISSUE TITLE
Refactor `common/aggregation`

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2356]
### What should be done?

Our aggregation framework will grow, so we should refactor it and make it more consistent before moving forward:

* move aggregation stages to `aggregations/stages`;
* move aggregation accamulators/operators to `aggregations/operators`;
* remove suffixes from names (for example, `groupStage` should become just `group` because it will be in `aggregations/stages` already);
* see what else could be refactored on the spot.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/handlers/common/aggregations

### Definition of Done

- `aggregations/stages` and `aggregations/operators` are present;
- spot refactorings done.

**Comment by AlekSi** [comment]
I don't think refactoring is ever a good first issue – that requires some prior experience with a code base to understand what is a good refactoring
