### ISSUE TITLE
The `listDatabases` command has a `totalSize` discrepancy

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2374]
### Versions

commit.txt: https://github.com/FerretDB/FerretDB/commit/37f0565eb9fef3ca1008631fd9617e6bdee29c0f
branch.txt: main
version.txt: v1.0.0-6-g37f0565e

### What did you do?

Given the output from the `listDatabases` command, tried to ensure that the total size reported is the sum of the individual db sizes.

### How can we reproduce it?

See repro #2375.

### What did you expect to see?

That the sum of all sizes on disk is equal to the total reported size.

### What did you see instead?

Different sizes.

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go version go1.20 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 23.0.3
```

**Comment by AlekSi** [comment]
That was fixed some time ago
