### ISSUE TITLE
Document squash&push in contributing guidelines

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2427]
### What should be done?

Currently, we say this in PROCESS.md:

https://github.com/FerretDB/FerretDB/blob/5adf466b7fefa0b709370356ea4db9bb882b3a51/.github/PROCESS.md?plain=1#L87-L90

But at least that bit is important for all contributors because squashes and force-pushes make reviews harder for us. I think we should move that information (and maybe something else that is important for everyone) to CONTRIBUTING.md.

**Comment by j0holo** [comment]
Maybe it is also a good idea to add the `task fmt` and `task lint` in the CONTRIBUTING.md file.

**Comment by AuruTus** [comment]
Looks like a good start point. Can assign this to me?

**Comment by AlekSi** [comment]
> Maybe it is also a good idea to add the `task fmt` and `task lint` in the CONTRIBUTING.md file.

We specifically document only `task all` because we don't want to mention many other important targets run by that command.

**Comment by AlekSi** [comment]
@AuruTus Done!

**Comment by j0holo** [comment]
But `task all` fails locally, because package.txt is missing. So if you don't want to document individual tasks it is only fair to fix `task all`.

**Comment by AuruTus** [comment]
> But `task all` fails locally, because package.txt is missing. So if you don't want to document individual tasks it is only fair to fix `task all`.
I happened to read the PR and see this comment, and it looks like a small bug. Seems I can work around it at present when local testing.
https://github.com/FerretDB/FerretDB/pull/2419#issuecomment-1507271111

**Comment by AlekSi** [comment]
> But task all fails locally, because package.txt is missing.

That should be fixed now
