### ISSUE TITLE
Add linter for checking blog posts

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2432]
### What should be done?

Our [blog](https://blog.ferretdb.io) uses the Docusaurus engine. All blog posts are stored in the `website/blog` directory as Markdown files. In addition to existing Markdown linters and Docusaurus checks, we want to introduce a new linter to check a few things about our blogging process.

Let's start by checking that all files in the `website/blog` directory start with some data in `YYYY-MM-DD` format, followed by `-`, "slug", and `.md` extension. The "slug" is a part of the URL path for that blog post. That same slug also should be present in the file itself in the frontmatter section.

Let's create a new linter in `tools/checkdocs` directory. It should be written in Go, not use external dependencies, not try to parse Markdown "properly" (regular expressions with `bufio.Scanner` will do just fine), and check filenames and slugs as written above. That linter should run in `docs-fmt` Taskfile target.

### Where?

`tools/checkdocs` directory.

### Definition of Done

Linter exists and works.

**Comment by AuruTus** [comment]
I have interest in it. Can assign me it later?

**Comment by raeidish** [comment]
Hi i'm intrested in this pr, could you assign it to me @AlekSi ?
