### ISSUE TITLE
Pushdown simplest sorting with `ORDER BY`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2438]
### What should be done?

Currently, we rely on our Go code to sort documents the same way MongoDB does because PostgreSQL and other backends don't sort them the same way. But that requires us to fetch all documents before we can sort them, and that kills performance. Let's start investigating what we could do about that.

Let's add a new flag `--test-enable-sorting-pushdown` that would pushdown `ORDER BY field ASC/DESC` query part if:
* the command is either `find` or `aggregate`;
* `find`'s command `projection` parameter is empty;
* there is only one field name, and it does not use a dot notation.

If pushdown was performed, we should skip sorting with the Go code.

That flag should also be added to integration tests. No new automated tests or CI configurations are necessary.

### Where?

`pgdb`.

### Definition of Done

- PostgreSQL handler updated;
- spot refactorings done;
- tested manually.

**Comment by AlekSi** [comment]
> That flag should also be added to integration tests.

That part wasn't done

**Comment by rumyantseva** [comment]
DoD: we only pass the flag, some tests are expected to fail, we don't process the flag in the tests.
