### ISSUE TITLE
`findAndModify` returns `CommandError` on updating document

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2440]
### What should be done?

In [UpdateDocument](https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/update.go#L36
), `findAndModify` returns `WriteError` instead of `CommandError` upon updating document which results in error. This is different from `update` command which returns `WriteError`.

* `findAndModify` command returns `CommandError`
* `update` command keeps returning `WriteError`

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/update.go#L36

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
Is that the same as #1903?

**Comment by chilagrow** [comment]
> Is that the same as #1903?

@AlekSi Yes I think they are the same.

**Comment by AlekSi** [comment]
Duplicate of #1903
