### ISSUE TITLE
`findAndModify` should not allow upsert on existing `_id`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2461]
### Versions

1.0.0

### What did you do?

`findAndModify` with `upsert: true` option uses `_id` from update parameter, if that `_id` already exists, it should returns error.

```
test> db.bar.insertOne({_id:"exists"})
{ acknowledged: true, insertedId: 'exists' }
test> db.bar.find()
[ { _id: 'exists' } ]
test> db.bar.findOneAndUpdate({_id:"not_exists"}, {$set: {_id:"exists"}}, {upsert:true})

test> db.bar.find()
[ { _id: 'exists' } ]
```

See more https://ferretdb.slack.com/archives/C04N81C6DSA/p1681749856431469?thread_ts=1676551658.876839&cid=C04N81C6DSA

### How can we reproduce it?

https://github.com/FerretDB/FerretDB/pull/2460

### What did you expect to see?

It should returns error indicating `_id` is a duplicate. 

### What did you see instead?

FerretDB uses `_id` from update parameter and uses it to update the collection.

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Deployment:
- Deployment details:
```

**Comment by AlekSi** [comment]
Test script in #2460 fails

**Comment by chilagrow** [comment]
> Test script in #2460 fails

@AlekSi see https://github.com/FerretDB/FerretDB/pull/2507#issuecomment-1522729151. In short, js driver which runs test script returns `WriteError`, `mongosh` and go driver return `CommandError`.

**Comment by AlekSi** [comment]
Sorry, but I think your analysis and conclusion contradict the stated facts. Take another look at the diff output:


```diff
         "ok": {
-          "$f": 1
+          "$f": 0
         },
-        "writeErrors": [
-          {
-            "$k": [
-              "code",
-              "errmsg"
-            ],
-            "code": 66,
-            "errmsg": "Performing an update on the path '_id' would modify the immutable field '_id'"
-          }
-        ]
+        "errmsg": "Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id'",
+        "code": 66,
+        "codeName": "ImmutableField"
```

It is clearly visible that FerretDB wraps returned error into `writeErrors` array while MongoDB does not.

It is even more noticeable if you read full FerretDB and MongoDB responses just above the diff. From my local run:

```
2023-05-02T09:58:45.463+0400	DEBUG	// 127.0.0.1:62455 -> 127.0.0.1:27017 	clientconn/conn.go:557	Response message:
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "ok",
          "writeErrors"
        ],
        "ok": {
          "$f": 1
        },
        "writeErrors": [
          {
            "$k": [
              "code",
              "errmsg"
            ],
            "code": 66,
            "errmsg": "Performing an update on the path '_id' would modify the immutable field '_id'"
          }
        ]
      },
      "Kind": 0
    }
  ]
}
```

```
2023-05-02T09:58:45.464+0400	WARN	// 127.0.0.1:62455 -> 127.0.0.1:27017 	clientconn/conn.go:557	Proxy response message:
{
  "Checksum": 2914705681,
  "FlagBits": 1,
  "Sections": [
    {
      "Document": {
        "$k": [
          "ok",
          "errmsg",
          "code",
          "codeName"
        ],
        "ok": {
          "$f": 0
        },
        "errmsg": "Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id'",
        "code": 66,
        "codeName": "ImmutableField"
      },
      "Kind": 0
    }
  ]
}
```

There is no `writeErrors` field in the MongoDB response. It is clearly a bug in FerretDB. It is even a known bug: see #1903 and #2440.

> compat tests with go driver confirms that it is fixed

Now that's the most interesting part. It seems that our test helpers for comparing/matching errors seem too smart for their own good and happily compare errors of different kinds. Could you please investigate that and create a new issue with a good description?

**Comment by chilagrow** [comment]
@AlekSi, thanks for detailing this :pray:. Yes it's visible that FerretDB is still returning `WriteError`. I didn't find the cause yet so I created an investigation issue https://github.com/FerretDB/FerretDB/issues/2545

**Comment by AlekSi** [comment]
@chilagrow Let's use existing #1903 for that part

**Comment by chilagrow** [comment]
:+1: let me merge them.

**Comment by AlekSi** [comment]
But we need to create a new issue (or just edit #2545) for fixing helpers themselves. Once we do that, we might notice that other commands and tests are broken too; that's why those two issues should be separate

**Comment by chilagrow** [comment]
For investigation and fixing findAndModify error, reusing https://github.com/FerretDB/FerretDB/issues/1903
For fixing test helper https://github.com/FerretDB/FerretDB/issues/2545

**Comment by AlekSi** [comment]
Ok, then this one is done

**Comment by chilagrow** [comment]
@AlekSi indeed it was my error https://github.com/FerretDB/FerretDB/pull/2546 :see_no_evil:
