### ISSUE TITLE
Move `handlers/pg/pjson` to `handlers/sjson`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2495]
### What should be done?

It makes sense for PostgreSQL, SQLite, and other future SQL-based databases with no idiosyncratic JSON support to share how BSON documents are stored. Let's move `pjson` out of `pg` handler and rename it. Let's also update all documentation and comments (and fix package documentation formatting where tabs and spaces are mixed). Let's not do other refactorings because moving and refactoring a lot of code in the same issue/PR is typically hard to review.

### Where?

* https://github.com/FerretDB/FerretDB/tree/main/internal/handlers/pg/pjson
* https://github.com/FerretDB/FerretDB/tree/main/internal/handlers
* search for all references to "pjson"

### Definition of Done

- code moved;
- all comments and docs updated.

**Comment by craigpastro** [comment]
👋 Mind if I take this too? Could probably use help to update the comments though.

**Comment by rumyantseva** [comment]
Hey @craigpastro, sorry for the long delay. Yes, please, feel free to take it, and thank you for your contribution!

**Comment by craigpastro** [comment]
Thanks, @rumyantseva!
