### ISSUE TITLE
Speed up integration test by using `UNLOGGED` table option for postgresql

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2509]
### What should be done?

The integration tests are slow due to insertion of test data. For our integration test only, we could use `UNLOGGED` table to make it faster.

postgresql documentation implies unlogged table would make writing faster. See https://www.postgresql.org/docs/current/sql-createtable.html

> Data written to unlogged tables is not written to the write-ahead log (see [Chapter 30](https://www.postgresql.org/docs/current/wal.html)), which makes them considerably faster than ordinary tables.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/integration

### Definition of Done

- integration/compatibility tests added/updated;

**Comment by AlekSi** [comment]
It does not work. Just updated #1507 to mention that.
