### ISSUE TITLE
Support all comparison query operators

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#251]
Support all query comparison operators for all data types.

- [x] $eq
- [x] $gt
- [x] $gte
- [x] $lt
- [x] $lte
- [ ] $in
- [x] $ne
- [x] $nin

**Comment by ribaraka** [comment]
I would like to work on this one.

**Comment by AlekSi** [comment]
I propose to do everything end-to-end (implementation, tests, integration tests) for one operator (for example, `$eq`), then do the rest.

**Comment by ribaraka** [comment]
got it. I will create seperate PRs for each operator.

**Comment by AlekSi** [comment]
Sure, that's a good idea. But I propose is to do and _merge_ one PR first, then start with the rest. Otherwise, you would have to change several PRs after each review cycle and do more busy work in the end.

**Comment by ribaraka** [comment]
Agreed. I'm going to do one PR after each merge.
