### ISSUE TITLE
Perform `insertMany` in a single transaction

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2510]
### What should be done?

Currently we perform insertion of multiple documents by calling `insertDocument` function multiple times. The function creates transaction for each document.

Let's try to perform all of the inserts in a single transaction. That might remove some overhead related to the transaction and potentially decrease the insert time.

Merging everything into single transaction will break compatibility, as on error - PostgreSQL will "undo" all previous inserts, while MongoDB won't. In such scenarios we should perform insertions once again, but in separate transactions.

Let's start by introducing simple insertion benchmark in separate PR. It will allow us to check if there's any performance gain after second PR with the actual change.

## Where
`pgdb` package

## DoD
- [x] Benchmark for `insertMany` created
- [x] Inserts of many documents are performed in a single transaction
- [x] If any of documents failed on insert, insertion is performed once again in separate transactions
- [x] Benchmarks results are compared.

**Comment by raeidish** [comment]
i was thinking i could create the benchmarks for this issue if you assign me

**Comment by rumyantseva** [comment]
@raeidish, thank you! I assigned the issue to you.

**Comment by AlekSi** [comment]
@raeidish let's start with benchmark

**Comment by raeidish** [comment]
I did a small 100 run comparison with the single transaction in my pr #2532 @AlekSi 
```
multi transaction dataframe
           t         ns/op          b/op     allocs/op  Unnamed: 5
count  100.0  1.000000e+02  1.000000e+02     100.00000         0.0
mean     1.0  1.646118e+09  8.888174e+07  712132.40000         NaN
std      0.0  5.599875e+08  2.465086e+07    1919.36662         NaN
min      1.0  1.074819e+09  8.076238e+07  710592.00000         NaN
25%      1.0  1.180916e+09  8.085442e+07  710640.00000         NaN
50%      1.0  1.525016e+09  8.102464e+07  710919.50000         NaN
75%      1.0  1.926923e+09  8.177099e+07  714091.50000         NaN
max      1.0  3.578464e+09  2.348509e+08  716356.00000         NaN

single transaction dataframe
           t         ns/op          B/op     allocs/op  Unnamed: 5
count  100.0  1.000000e+02  1.000000e+02     100.00000         0.0
mean     1.0  1.367961e+09  8.907059e+07  714686.97000         NaN
std      0.0  2.320472e+08  2.462966e+07    2023.39435         NaN
min      1.0  1.085949e+09  8.097029e+07  713217.00000         NaN
25%      1.0  1.188787e+09  8.105036e+07  713276.00000         NaN
50%      1.0  1.298693e+09  8.116747e+07  713433.50000         NaN
75%      1.0  1.500782e+09  8.200157e+07  716906.00000         NaN
max      1.0  2.074677e+09  2.350337e+08  718979.00000         NaN

multi_avg: 1646117953.680000
single_avg: 1367961369.290000
difference: -278156584.390000

diff/multi_avg: -0.168977
```

**Comment by AlekSi** [comment]
@raeidish could you please run results through `bin/benchstat`?

**Comment by AlekSi** [comment]
`benchstat` should be used with two files: `bin/benchstat before.txt after.txt`

**Comment by raeidish** [comment]
@AlekSi ah sorry!

```
goos: linux
goarch: amd64
pkg: github.com/FerretDB/FerretDB/integration
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
                             │ multi_transaction │      single_transaction       │
                             │      sec/op       │    sec/op     vs base         │
InsertMany/InsertMany-D10-12       1654.6m ± 10%   774.6m ± 18%  -53.18% (n=100)

                             │ multi_transaction │      single_transaction      │
                             │       B/op        │     B/op      vs base        │
InsertMany/InsertMany-D10-12        77.51Mi ± 1%   74.45Mi ± 0%  -3.95% (n=100)

                             │ multi_transaction │     single_transaction      │
                             │     allocs/op     │  allocs/op   vs base        │
InsertMany/InsertMany-D10-12         707.2k ± 0%   672.5k ± 0%  -4.91% (n=100)

```
