### ISSUE TITLE
Query performance is very slow

### ISSUE THREAD

**Issue by zhanglei04** [FerretDB/FerretDB#2517]
### Versions

ferretdb v1.0.0 ，  use postgresql

### What did you do?

After inserting 3000 pieces of data and creating indexes, it takes over 20 seconds to perform a full table query through the MongoDB client connected to FerretDB. This is too slow. How can we optimize it? Is it normal for the query to be very slow?

### What did you expect to see?

query fast

### What did you see instead?

slow

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Deployment:
- Deployment details:
```

**Comment by zhanglei04** [comment]
我用的数据库时 postgresql， count查询非常慢

The database I used was very slow for postgresql, count queries

**Comment by AlekSi** [comment]
Could you describe your data, index, and query in more detail? We will not be able to help without this information.

**Comment by zhanglei04** [comment]
There are over 4,000 pieces of data。

**Comment by zhanglei04** [comment]
Create an index for the field companyId；
select count(*) from tablename is not used to query the total number;

**Comment by AlekSi** [comment]
Sorry, but we could not help without knowing more about your data and queries. Could you provide a dump with `mongoexport`? Could you provide FerretDB logs with queries?
