### ISSUE TITLE
Handle path collisions for multiple update operators

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2539]
### Versions

commit.txt: cf0328f6dbb715471908563b62f9ab7c50e77a7d
branch.txt: main
version.txt: v1.0.0-83-gcf0328f6

### What did you do?

See repro in #2538.

### How can we reproduce it?

See above.

### What did you expect to see?

Successful update operation.

### What did you see instead?

```
"Updating the path 'a.0.c' would create a conflict at 'a.0.c'"
```

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go1.19.3 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 23.0.3
```

**Comment by AlekSi** [comment]
Test script passes, moved to Done
