### ISSUE TITLE
Implement `shell` subcommands in `envtool`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2548]
### What should be done?

We switched from Makefiles to [Taskfiles](https://taskfile.dev) for several reasons, including making things easier for contributors on Windows. Unfortunately, sometimes we need to run some Unix-specific shell commands; for example, for creating and removing directories. Let's add those commands to `envtool` to make our Taskfiles more cross-platform.

Let's add `envtool shell` subcommand with two sub-subcommands:
- `envtool shell mkdir <dir/path1> <dir/path2> ...` should create given directories using `os.MkdirAll` (similar to `mkdir -p` on Unix).
- `envtool shell rmdir <dir/path1> <file/path2> ...` should remove given directories and files using `os.RemoveAll` (similar to `rm -fr` on Unix).

The path separator should always be `/`; we should convert it to `\` on Windows if that's needed.

We should update our Taskfiles to use those commands.

### Where?

- https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml
- https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

- `envtool` updated;
- `Taskfile.yml` updated.

**Comment by kropidlowsky** [comment]
Can I work on this one?

**Comment by AlekSi** [comment]
Sure!
