### ISSUE TITLE
Add proper CLI to `envtool`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2550]
### What should be done?

We want to add some functionality to `envtool` (see #2547, #2548). But before we can do that, we should allow it to be extended with subcommands.

Let's move existing functionality into `envtool setup` [kong](github.com/alecthomas/kong) subcommand.

### Where?

- https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool
- https://github.com/FerretDB/FerretDB/blob/93e6981b7c1f6c20a17dec60d4d85984d3af9ec9/Taskfile.yml#L96

### Definition of Done

- `envtool setup` works;
- `task env-up` works as before;
- spot refactorings done.

**Comment by kropidlowsky** [comment]
Hi @AlekSi,

Can I work on this one?

**Comment by AlekSi** [comment]
Sure!

**Comment by noisersup** [comment]
@kropidlowsky If you are stuck with something, or just have any questions, feel free to ask here or in our slack community!
