### ISSUE TITLE
Support all bitwise query operators

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#256]
Support all query comparison operators for all data types.

- [x] $bitsAllClear
- [x] $bitsAllSet
- [x] $bitsAnyClear
- [x] $bitsAnySet

**Comment by OpenSauce** [comment]
I'll pick this up @AlekSi

**Comment by AlekSi** [comment]
I propose to do everything end-to-end (implementation, tests, integration tests) for one operator (for example, `$bitsAllClear`), then do the rest.

**Comment by OpenSauce** [comment]
@AlekSi Sounds like a plan my friend!

**Comment by w84thesun** [comment]
I'll pick it
