### ISSUE TITLE
Do check error messages in non-compat integration tests

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2599]
### What should be done?

In #2345, we removed all checks for error messages in compat tests. We still want to check error messages in tricky cases, and that should be in non-compat integration tests. We also want our tests be consistent. Right now, they have small differences here and there; in particular, some tests include `altMessage` in their test cases, and some don't.

Let's add `altMessage` to all non-compat table-driven tests that check errors and use it. Let's also try to add at least one test case to tests that don't use it yet (if possible).

For consistency, also check how an expected error is called. It should be called `err`, not `expectedErr` or something.

Feel free to send a few PRs if it makes it simpler to review/discuss things.

### Where?

Integration tests.

### Definition of Done

- Rewrite `insertRunCommandCompatTestCase`, currently it contains `altErrorMsg`, but it shouldn't. Write separate non-compat table tests to check errors for `insert` command.
- Rewrite `TestIndexesDropRunCommand`, currently it contains `altErrorMsg`. Write separate non-compat table tests to check errors for `drop indexes` command.
- Check that expected error fields in table test structures are called `err`, not `expectedErr` or something else.
- Identify non-compatible integration tests with expected errors and ensure `altMessage` is in struct definition for them. Example of tests where `altMessage` needs to be added: `TestDistinctErrors`, `TestQueryArrayDotNotation`.
- Whenever `altMessage` is introduced, attempt to create a test case where it can be utilized. If not possible due to identical errors, include `altMessage` in the struct definition for potential future use.
- Do other spot refactoring if needed.

**Comment by rumyantseva** [comment]
> Let's add altMessage to all non-compat table-driven tests and use it. Let's also try to add at least one test case to tests that don't use it yet.

What if the original message is the same as `altMessage`? Should we really add `altMessage` to _all_ table-driven non-compat tests? I think we have quite a lot of cases where the messages are equal.

**Comment by AlekSi** [comment]
> What if the original message is the same as altMessage? 

`if tc.altMessage != ""`

> Should we really add altMessage to all table-driven non-compat tests?

Yes.

---

The underlying issue is that all compat tests and non-compat table-driven tests are slightly different for no good reason, and those differences propagate because we create new tests by copy and pasting existing inconsistent tests. They should become more consistent, not less.
