### ISSUE TITLE
pymongo.errors.ConfigurationError when trying to create a table

### ISSUE THREAD

**Issue by PlatonB** [FerretDB/FerretDB#2605]
### FerretDB version

version: v1.1.0
commit: 3344cbb98bb744dd044bcf2d51fe9ab65db22f0b
branch: unknown
dirty: true
package: deb
debugBuild: false

### Backend

psql (PostgreSQL) 15.2 (Ubuntu 15.2-1)

### Environment

- OS: Ubuntu 23.04
- Deployment: DEB
- Deployment details:

### What did you do?

1. `sudo systemctl enable postgresql`
2. `ferretdb`
3. `python3` (in another tab of the terminal)
```
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymongo import MongoClient
>>> client = MongoClient('mongodb://127.0.0.1:27017/')
>>> db_obj = client['test_postgres_db']
>>> coll_obj = db_obj.create_collection('test_postgres_table')
```

### What did you expect to see?

The official Readme [declares](https://github.com/FerretDB/FerretDB#scope-and-current-state) FerretDB to be compatible with MongoDB drivers. Consequently, I expect PyMongo to work seamlessly with FerretDB.

### What did you see instead?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pymongo/database.py", line 412, in create_collection
    name in self.list_collection_names(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/database.py", line 863, in list_collection_names
    for result in self.list_collections(session=session, **kwargs)]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/database.py", line 825, in list_collections
    return self.__client._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1460, in _retryable_read
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 233, in _select_servers_loop
    self._description.check_compatible()
  File "/usr/lib/python3/dist-packages/pymongo/topology_description.py", line 125, in check_compatible
    raise ConfigurationError(self._incompatible_err)
pymongo.errors.ConfigurationError: Server at 127.0.0.1:27017 requires wire version 13, but this version of PyMongo only supports up to 9.
>>>
```

**Comment by PlatonB** [comment]
P.S. Perhaps it is indirectly useful information to solve problem described above. When trying to create DB using MongoDB Compass, the following error occurs:
```
[msg_create.go:37 pg.(*Handler).MsgCreate] [pg.go:138 pg.(*Handler).DBPool] pgdb.checkConnection: failed to connect to `host=127.0.0.1 user=platon database=ferretdb`: failed SASL auth (FATAL: password authentication failed for user "platon" (SQLSTATE 28P01))
```

**Comment by AlekSi** [comment]
> Server at 127.0.0.1:27017 requires wire version 13, but this version of PyMongo only supports up to 9

What version of `pymongo` do you use?

**Comment by PlatonB** [comment]
@AlekSi PyMongo 4.3.3.

**Comment by AlekSi** [comment]
@b1ron could you reproduce a problem with https://github.com/FerretDB/python-example ?

**Comment by b1ron** [comment]
I cannot reproduce the issue with PyMongo 4.3.3.

I can only reproduce it with PyMongo 3.11.0 as this version only supports the write protocol version up to 9.

@PlatonB to confirm what version you are using could you please run the below command:

```
python3 -c "import pymongo; print(pymongo.version); print(pymongo.has_c())"
```

**Comment by AlekSi** [comment]
@PlatonB

**Comment by PlatonB** [comment]
@AlekSi Indeed, due to my inattention I installed PyMongo 3.11 instead of the current version. It is necessary to use `pip install pymongo --break-system-packages` instead of `sudo apt install python3-pymongo`.

After installing the latest version, the error from #2625 began to be output (`password authentication failed`).
