### ISSUE TITLE
Indexes are created incorrectly for nested fields

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2606]
### FerretDB version

1.1.0

### Backend

PostgreSQL

### Environment

- OS: MacOS
- Deployment: `task run`

### What did you do?

```
db.c.createIndex({"foo.bar": 1})
```

### What did you expect to see?

Index is created for a nested field foo -> bar

### What did you see instead?

Index is created for a field "foo.bar" which is not correct, also such fields with dots are not possible at all.

**Comment by wqhhust** [comment]
I'd like to try on this, but one question: when I create a document, create an index in mongosh, why I didn't find the table in postgresql?
![image](https://github.com/FerretDB/FerretDB/assets/5955201/8fec9217-e169-44e2-a64b-6d22287543ca)
I am using "task psql" to connect to the postgresl.
![image](https://github.com/FerretDB/FerretDB/assets/5955201/e4899b41-c1d8-41c7-8660-16738098004c)

**Comment by rumyantseva** [comment]
@wqhhust FerretDB databases are translated into PostgreSQL schemas, so you need to use `test` PG schema in the database `ferretdb`. 

So the command to call tables will be ` \dt test.*` - to show the relations in the `test` schema.

Also, it's possible to call something like `set search_path to test` to tell psql that I want to work in the `test` schema.

```
ferretdb=# \dt test.*
                    List of relations
 Schema |            Name             | Type  |  Owner
--------+-----------------------------+-------+----------
 test   | _ferretdb_database_metadata | table | username
 test   | sales_869c16b7              | table | username
(2 rows)

ferretdb=# set search_path to test;
SET

ferretdb=# \dt
                    List of relations
 Schema |            Name             | Type  |  Owner
--------+-----------------------------+-------+----------
 test   | _ferretdb_database_metadata | table | username
 test   | sales_869c16b7              | table | username
(2 rows)
```

**Comment by wqhhust** [comment]
thx, please check https://github.com/FerretDB/FerretDB/pull/2637

 the following is the index definition after the change
![image](https://github.com/FerretDB/FerretDB/assets/5955201/0a620bf2-d454-4f23-994a-30aa52ceca79)
