### ISSUE TITLE
Implement `envtool shell read` subcommand

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2615]
### What should be done?

It should read the given file and print its content to stdout.

Then use it instead of `cat` command in the Taskfiles.

### Where?

* https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml
* https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

* envtool updated;
* Taskfile.yml updated.

**Comment by wqhhust** [comment]
I'd like to try this.

**Comment by AlekSi** [comment]
@wqhhust 👍

**Comment by rumyantseva** [comment]
@wqhhust thank you for contributing! So, the command works, and we merged the main PR. There is one more thing we didn't do - we didn't add tests for this new subcommand. Would you mind sending one more PR with some simple tests to check how this new subcommand works? The file with tests is `cmd/envtool/envtool_test.go`. A similar approach to the other tests in this file should be enough.

**Comment by wqhhust** [comment]
@rumyantseva Sure, I'd like to do it. Can we do it in this way： run the command "go run ./cmd/envtool shell read somefile > resultfile" and then compare whether somefile has the same content as resultfile. Or do you have better solution?
