### ISSUE TITLE
Add supported aggregations to the `buildInfo` output

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2650]
### What should be done?

We should return a sorted list of supported aggregation pipeline stages in the `buildInfo` output:

```json
{
	"ferretdbFeatures": {
		"aggregationStages": [
			"$collStats",
			"$count",
			// ...
		]
	},
	// ...
}
```

Let's either export `internal/handlers/common/aggregations/stages.stages` variable or add a function to return a sort list of stages to that package. Then, let's use that variable/function in `MsgBuildInfo`. And add/update integration tests.

### Where?

* https://github.com/FerretDB/FerretDB/blob/1d81e46de0ee0712a5dcb1694a2f65ea82f35976/internal/handlers/common/aggregations/stages/stages.go#L29-L30
* https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/msg_buildinfo.go
* https://github.com/FerretDB/FerretDB/blob/1d81e46de0ee0712a5dcb1694a2f65ea82f35976/integration/commands_administration_test.go#L545

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by kropidlowsky** [comment]
@AlekSi Can I work on this one?

**Comment by AlekSi** [comment]
@kropidlowsky Sure, thank you!

**Comment by AlekSi** [comment]
@kropidlowsky any news?
