### ISSUE TITLE
Implement `$type` aggregation operator

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2678]
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/aggregation/type/

Currently we have a stub for `$type` operator so it just needs an implementation.
The `commonparam` package offers the `AliasFromType` function which can be used for the operator either.

#2635 might be helpful, there's a basic implementation there and couple of test cases.

As `$type` differentiate between unset and Null, we should probably modify `expression.Evaluate` to return nil and not `Null` for non-existent paths. Some changes in code will be needed to handle function calls in a different way.

As we currently don't support standard operators anywhere, let's add basic operators support in the `$project` stage. Other stages will be covered in #2679 after implementing `$type`.

### DoD
- `$type` operator is supported
- recursive operator calls in `$type` are supported (for example `{$type:{$type:42}}`)
- dot notation is supported and tested properly (arrays, and array indexes should be also tested)
- compat tests implemented.

**Comment by AlekSi** [comment]
> The `sjson` package offers the `GetTypeOfValue` function which can be used for the operator either.

`sjson` is on a completely separate layer, though. What you probably need is `TypeCode` / `AliasFromType`. Please check that `GetTypeOfValue` is not used where it should not be.

**Comment by noisersup** [comment]
Yep just run `TestGetTypeOfValue` against `AliasFromType` and it seems that it returns exact same values. Will send PR that removes `GetTypeOfValue` in a moment.
