### ISSUE TITLE
Implement `$sum` aggregation standard operator

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2680]
After https://github.com/FerretDB/FerretDB/issues/2679

### What should be done?

Currently we support `$sum` as accumulation operator, although while being used in other stages it [behaves differently](https://www.mongodb.com/docs/manual/reference/operator/aggregation/sum/#syntax).

Let's introduce `$sum` operator, that will work only in supported stages mentioned in documentation.
Please also validate if it's possible to use `$sum` in any other non-accumulator stage that is not mentioned in supported list.
As it should work in `$project` stage, let's also check if it works in `find` projection. 

DOD:
* `$sum` operator accepts other operators, examples: 
`db.Composites.aggregate([{ $project: { sumsum: {$sum: { $sum: "$v" } } } }])`
`db.Composites.aggregate([{ $project: { sumtype: {$sum: { $type: "$v" } } } }])`;
* Return error on other unimplemented operators to `$sum`; 
* Use `$sum` operator for aggregation projection;
* Use `$sum` operator for query projection;
* Use `$sum` operator for `$group` stage `_id` expression

**Comment by chilagrow** [comment]
`$sum` should work on projection for both query and aggregation, also it should work in stages too.

aggregate project
```
test> db.Composites.aggregate([{ $project: { sum: { $sum: "$v" } } }, {$skip: 12}])
[
  { _id: 'array-null', sum: 0 },
  { _id: 'array-three', sum: 42 },
  { _id: 'array-three-reverse', sum: 42 },
  { _id: 'array-composite', sum: 125.13 }
]
```
query projection
```
test> db.Composites.find().projection({sum: {$sum: "$v"}}).skip(12)
[
  { _id: 'array-null', sum: 0 },
  { _id: 'array-three', sum: 42 },
  { _id: 'array-three-reverse', sum: 42 },
  { _id: 'array-composite', sum: 125.13 }
]
```
