### ISSUE TITLE
Implement `NewAccumulator` internal errors

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2689]
### What should be done?

Like for `NewOperator` we should create internal error type with error codes for `NewAccumulator` function. It will allow us
to introduce stage specific error messages by using switch statement outside of function.

### Where?

- `accumulators` package
- `stages` package

### Definition of Done

- `accumulators.go` refactorings done;
- `CommandError`s are created on the stage level;

**Comment by chilagrow** [comment]
This issue seems not necessary, see more https://ferretdb.slack.com/archives/C02NWN1K3MJ/p1686042611472089

**Comment by chilagrow** [comment]
Closing this issue because accumulators return the same error code and error message from `NewAccumulator` function. For this case there isn't a need for Internal Error.
