### ISSUE TITLE
Implement `envtool tests shard` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2692]
### What should be done?

We want to make CI faster by splitting integration tests into multiple parallel GitHub Actions jobs. Currently, we split them by handler (PostgreSQL, SQLite, etc), but we could also split tests of one handler. For example, we could run `go test -run=^(TestOne|BenchmarkTwo)$` in one job, `go test -run=^(ExampleThree|FuzzFour)$` in another, etc. But we don't want to update our CI configurations every time we add or remove a top-level integration test.

Let's implement `envtool tests shard` command. It would output the value of the `-run` flag that we would then pass to `go test`. For example:

```
$ envtool tests shard -index=0 -total=2

^(TestOne|BenchmarkTwo)$

$ envtool tests shard -index=1 -total=2

^(ExampleThree|FuzzFour)$
```

It then could be used as `go test -run=$(envtool tests shard -index=0 -total=2)`.

A list of test functions could be received using `go test -list=.` command. `envtool tests shard` should call it in the `integartion` directory, split output into lines, sort them, then iterate over them and split them into multiple shards.

This task is only about implementing that command and testing it manually. CI integration is not in the scope.

### Where?

- https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

- `envtool tests shard -index=0 -total=2` command works;
- there are some basic tests that actually run `go test -list=.` and shard results in place.

**Comment by AlekSi** [comment]
@kropidlowsky PTAL

**Comment by kropidlowsky** [comment]
@AlekSi Could you please assign it to me?
