### ISSUE TITLE
listIndexes should also show index options

### ISSUE THREAD

**Issue by dev-wealthpilot** [FerretDB/FerretDB#2719]
### FerretDB version

version: v1.2.1
commit: 25e3cdfa32838c8efdaf5e68e2fc5b46806b1748
branch: unknown
dirty: true
package: docker
debugBuild: false

### Backend

PostgreSQL 15.3

### Environment

- OS: Debian
- Deployment: Docker using ghcr.io/ferretdb/ferretdb
- Deployment details: Docker version 20.10.24+dfsg1, build 297e128

### What did you do?

I tried to replace mongo with ferretdb in a java project that uses [Mongock](https://mongock.io/)  to initialize the database. Mongock creates a collection called "mongockLock"  and adds a unique index to the "key" field using this command:
`'{"createIndexes": "mongockLock", "indexes": [{"key": {"key": 1}, "name": "key_1", "unique": true}], "writeConcern": {"w": "majority", "j": true}, "$db": "XXX"}'`

Mongock then uses listIndexes to ensure that the index has been created correctly. This validation fails, because the output of listIndexes does not contain the "unique: true" option 

### What did you expect to see?

```
db.runCommand({ listIndexes: "mongockLock", cursor: { batchSize: 5 } } )
{
  cursor: {
    id: Long("0"),
    ns: 'marketplace.mongockLock',
    firstBatch: [
      { v: 2, key: { _id: 1 }, name: '_id_' },
      { v: 2, key: { key: 1 }, name: 'key_1', unique: true }
    ]
  },
  ok: 1
}
```

### What did you see instead?

```
db.runCommand({ listIndexes: "mongockLock", cursor: { batchSize: 5 } } )
{
  cursor: {
    id: Long("0"),
    ns: 'marketplace.mongockLock',
    firstBatch: [
      { v: 2, key: { _id: 1 }, name: '_id_' },
      { v: 2, key: { key: 1 }, name: 'key_1' }
    ]
  },
  ok: 1
}
```

**Comment by AlekSi** [comment]
Unique indexes are not supported yet, but will be soon; see #2045.

**Comment by rumyantseva** [comment]
@adetunjii thanks for the update! We want to release this issue before the end of June, so please let me know if you need any assistance or if you don't have the capacity for this issue.

**Comment by dev-wealthpilot** [comment]
with the introduction of unique indexes in 1.4.0 release the response has changed:
```
db.runCommand({ listIndexes: "mongockLock", cursor: { batchSize: 5 } } )
{
  cursor: {
    id: Long("0"),
    ns: 'marketplace.mongockLock',
    firstBatch: [
      { v: 2, key: { _id: 1 }, name: '_id_' },
      { v: 2, key: { key: 1 }, name: 'key_1', unique: false }
    ]
  },
  ok: 1
}
```

it now says "unique: **false**" . 

postgresql logs show that the index is correctly created as unique index: `CREATE UNIQUE INDEX IF NOT EXISTS `...

**Comment by rumyantseva** [comment]
@dev-wealthpilot thank you for reporting this! We will take a look.

**Comment by dev-wealthpilot** [comment]
error was on my side this time, I did not clean up the postgresql database before trying the 1.4.0 release.
`listIndexes`  now works as expected.
