### ISSUE TITLE
Make linter for checking that linked issues are open

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2733]
### What should be done?

We have a linter that checks comments like `// TODO https://github.com/FerretDB/FerretDB/issues/<number>` in our Go code: https://github.com/FerretDB/FerretDB/tree/main/tools/checkcomments

It should also check if those issues are still open. Doing that is a bit tricky: the tool runs once for each Go package (not project or Go module) and generates so many requests (many of which are for the same issues) that we easily go over GitHub's rate limit. We should keep cache check results in a temporary file and coordinate multiple invocations using [`lockedfile`](https://github.com/rogpeppe/go-internal/tree/master/lockedfile).

Additionally (and in a separate PR), we should check those issue links in string constants like in
```go
skip: "https://github.com/FerretDB/FerretDB/issues/1522"
```

### Where?

https://github.com/FerretDB/FerretDB/tree/main/tools/checkcomments

### Definition of Done

* Linter does not check the same issue twice for one `task lint` invocation.
* String constants in Go code are checked.

**Comment by chilagrow** [comment]
How shall we add comment for TODO? Currently comments can be anywhere and look like these
```
// TODO Use all providers after fixing $sort problem:  https://github.com/FerretDB/FerretDB/issues/2276.
```
or
```
// TODO we should still set HeaderB and BodyB
// https://github.com/FerretDB/FerretDB/issues/1636
```

For the proposed linter, we can do like this?
```
// <comment>
// TODO <link>
```

**Comment by KrishnaSindhur** [comment]
If its still open i can work on this

**Comment by AlekSi** [comment]
I think we should go with
```go
// <comment>
// TODO https://github.com/FerretDB/FerretDB/issues/<number>
```

We don't need anything fancy for parsing code (`bufio.Scanner` or a regular expression will do), but for extracting URLs from Go strings, we would need to parse Go code. Luckily, there is an example already: https://github.com/FerretDB/FerretDB/tree/main/tools/checkswitch

**Comment by AlekSi** [comment]
@KrishnaSindhur any news? Could we help you somehow?

**Comment by KrishnaSindhur** [comment]
I am on it will push draft PR soon

**Comment by KrishnaSindhur** [comment]
@AlekSi but there is so many other patterns like 
`single comment
// TODO https://github.com/FerretDB/FerretDB/issues/2291
or like this 
// TODO <comment>
// https://github.com/FerretDB/FerretDB/issues/2291
or 
<comment>
// TODO fix the issue ... https://github.com/FerretDB/FerretDB/issues/2291`

**Comment by KrishnaSindhur** [comment]
single comment
`// TODO https://github.com/FerretDB/FerretDB/issues/2291`
or like this 
`// TODO <comment>`
`// https://github.com/FerretDB/FerretDB/issues/2291`
or 
`<comment>`
`// TODO fix the issue ... `

**Comment by AlekSi** [comment]
@KrishnaSindhur I don't think we should do everything in one PR

**Comment by AlekSi** [comment]
@KrishnaSindhur The first PR is merged! Feel free to continue working on this issue (in particular, checking that the issue is still open should be relatively easy), #3112, or any other issue – just let us know

**Comment by KrishnaSindhur** [comment]
ok sure
