### ISSUE TITLE
Fix free monitoring tests for MongoDB 6.0.6

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2735]
### What should be done?

The free monitoring is no longer available. To reproduce it, make sure to run `task env-pull` to get the 6.0.6 version of mongodb. see #2727. `setFreeMonitoring` seems to function fine, but `getFreeMonitoringStatus` response has deprecated message and `state` is always `disabled`, although it contains `debug` document indicating actual state. Tests should check `debug.state` instead of just `state`.

Example of `disabled` response from MongoDB
```
admin> db.runCommand({setFreeMonitoring: 1, action: "disable"})
{ ok: 1 }
admin> db.runCommand({getFreeMonitoringStatus: 1})
{
  state: 'disabled',
  message: "Free monitoring is deprecated, refer to 'debug' field for actual status",
  debug: {
    state: 'disabled',
    message: 'Free monitoring has been deprecated and is not available for new MongoDB Community instances. For more information on monitoring alternatives, please see https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    url: 'https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    userReminder: 'Free Monitoring URL:\n' +
      'https://cloud.mongodb.com/freemonitoring/cluster/C3RNC7GDDCOCALYKJHFSGTKIU4YWAZQM'
  },
  ok: 1
}
```
Example of `enabled` response from MongoDB
```
admin> db.runCommand({setFreeMonitoring: 1, action: "enable"})
{ ok: 1 }
admin> db.runCommand({getFreeMonitoringStatus: 1})
{
  state: 'disabled',
  message: "Free monitoring is deprecated, refer to 'debug' field for actual status",
  debug: {
    state: 'enabled',
    message: 'Free monitoring has been deprecated and is not available for new MongoDB Community instances. For more information on monitoring alternatives, please see https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    url: 'https://www.mongodb.com/docs/manual/administration/free-monitoring/',
    userReminder: 'Free Monitoring URL:\n' +
      'https://cloud.mongodb.com/freemonitoring/cluster/C3RNC7GDDCOCALYKJHFSGTKIU4YWAZQM'
  },
  ok: 1
}
```

### Where?

https://github.com/FerretDB/FerretDB/blob/439ec96798e5790ffe61bae03cace6c5333839e5/integration/commands_freemonitoring_test.go#L65-L69

https://github.com/FerretDB/FerretDB/blob/439ec96798e5790ffe61bae03cace6c5333839e5/integration/commands_freemonitoring_test.go#L70-L74

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by jeremyphua** [comment]
Hello! Can I have a go at this? Thanks in advance!
