### ISSUE TITLE
Fix `findAndModify` tests for MongoDB 6.0.6

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2736]
### What should be done?

`findAndModify` now allow query to containing `$` prefixed key, as long as they not predefined keys.
To reproduce it, make sure to run task env-pull to get the 6.0.6 version of mongodb. see https://github.com/FerretDB/FerretDB/pull/2727

In MongoDB 6.0.6 using `$invalid` in the query is now allowed, and it actually sets the `_id` with document containing `$` prefixed `$invalid` key.
```
test> db.values.findAndModify({query: {"_id": {key: {$invalid: "val"}}}, upsert: true, update: {v: "replaced"}})
null
test> db.values.find({"_id": {key: {$invalid: "val"}}})
[
  { _id: { key: { '$invalid': 'val' } }, v: 'replaced' }
]
```
Actually even using valid key such as `$eq` succeeds. 

FerretDB does not support key with `$` prefix so let's remove the test https://github.com/FerretDB/FerretDB/blob/main/website/docs/diff.md?plain=1#L19

### Where?

https://github.com/FerretDB/FerretDB/blob/439ec96798e5790ffe61bae03cace6c5333839e5/integration/findandmodify_compat_test.go#L115-L117

https://github.com/FerretDB/FerretDB/blob/439ec96798e5790ffe61bae03cace6c5333839e5/integration/findandmodify_compat_test.go#L122-L124

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
"What should be done?" section describes the current state but not what should be done. What should be done to resolve that issue?

**Comment by chilagrow** [comment]
This was not fixed, reopening.
