### ISSUE TITLE
Allow `$set` to work with `_id` field when `upsert` is performed

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2741]
### FerretDB version

`v1.2.0`

### Backend

PostgreSQL

### Environment

- OS: MacOS
- Deployment: dev

### What did you do?

While experimenting with upsert, I noticed that FerretDB has a different behavior than MongoDB.

More specifically, MongoDB allows `$set` to work with `_id` field when upsert is performed, but FerretDB doesn't (see below).

Test script https://github.com/FerretDB/FerretDB/pull/2743

### What did you expect to see?

```
db.col.find()

test> db.col.findAndModify({query: {"non-existent": {$exists: false}}, upsert: true, update: {$set: {_id: "hello"}}})
null

test> db.col.find()
[ { _id: 'hello' } ]
```

### What did you see instead?

```
test> db.col.find()

test> db.col.findAndModify({query: {"non-existent": {$exists: false}}, upsert: true, update: {$set: {_id: "hello"}}})
MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'

test> db.col.find()
```

### DoD

- Check TODOs in the code

**Comment by AlekSi** [comment]
Please send a PR with a test script

**Comment by rumyantseva** [comment]
Added a test script PR: https://github.com/FerretDB/FerretDB/pull/2743

**Comment by ujibang** [comment]
any news on this? this breaks compatibility with RESTHeart
