### ISSUE TITLE
Implement `renameCollection` for SQLite

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2760]
### What should be done?

SQLite backend and handler should support `renameCollection` command.

Collection renaming should not rename the underlying table; only the metadata should be updated.

`CollectionCreate` method should also be updated to treat a hash as a number and increment it until the selected table name is available.

### Where?

See references to this issue.

### Definition of Done

- handler updated;
- integration/compatibility tests enabled and pass;
- no references to this issue are left.

**Comment by kropidlowsky** [comment]
Hi @AlekSi,

Can I work on this one? :smiley:

**Comment by AlekSi** [comment]
@kropidlowsky Sure! Please start with a separate small PR for the `CollectionCreate` method

**Comment by chilagrow** [comment]
I'm starting to work on this
