### ISSUE TITLE
Handle `batchSizes` correctly

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2762]
### FerretDB version

Refs #79.

package.txt: docker-local
commit.txt: 4a69d977535fc0a67e523095b4ddb22cf26d9079
branch.txt: batchsizes
version.txt: v1.2.0-32-g4a69d977-dirty

### Backend

PostgreSQL

### Environment

- OS: Ubuntu 22.10 x86_64
- Deployment: v1.2.0-32-g4a69d977-dirty
- Deployment details: 23.0.3

### What did you do?

See repro in #2761

### What did you expect to see?

Cursors using the batch size correctly.

### What did you see instead?

Cursor returning all documents regardless of a batch size.

**Comment by AlekSi** [comment]
Duplicate of #1733
