### ISSUE TITLE
Support `listIndexes` command

### ISSUE THREAD

**Issue by zhouyuansheng0618** [FerretDB/FerretDB#278]
Implement `listIndexes` command stub that returns valid empty results in the same format as MongoDB.

Ignore `cursor` and `comment` fields.

https://www.mongodb.com/docs/manual/reference/command/listIndexes/

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated (results for compat/target might be different):
   - collection doesn't exist;
   - existing collection; 
- spot refactorings done;
- user documentation updated.

**Comment by AlekSi** [comment]
Yes, indexes are not supported yet. That's tracked as #78.

**Comment by zhouyuansheng0618** [comment]
Will it be updated later 
My English is poor, thank you for understanding

**Comment by AlekSi** [comment]
Yes, we plan to add support for indexes and other features needed by typical applications that use pymongo and other MongoDB drivers.
No worries :)

**Comment by zhouyuansheng0618** [comment]
Currently switching from mongodb to FerretDB
The problem can't be solved
When can you release a version

**Comment by AlekSi** [comment]
It might be a bit early to switch to FerretDB right now. We plan to add support for indexes in several months. Our roadmap is there: https://github.com/orgs/FerretDB/projects/2/views/1

**Comment by zhouyuansheng0618** [comment]
Good thank you
