### ISSUE TITLE
Process collection name parameter in tags

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#2786]
### What should be done?

Right now when we pass a parameters structure to the ExtractParams function we expect that the command field would contain a collection name. That's not true for several commands.
For example, the dataSize command should accept a namespace in the format database.collection.

```js
db.runCommand(
    {
         dataSize: "database.collection"
    }
)
```
The explain command expects the command document to be passed as the command parameter.

```js
db.runCommand(
    {
        explain: {
        "update": {...}
        }
    }
)
```

In order to process above mentioned commands we should add a tag that would specify that the field should contain a collection name.

### Where?

internal/handlers/commonparams/extract_params.go
internal/handlers/common

### Definition of Done
- add the `collection` tag to the `tagOptions`;
- use the `collection` tag to process the collection name in `ExtractParams`;
- update the following commands to use that tag: `count`, `delete`, `distinct`, `find`, `findAndModify`, `insert`, `update`;
- replace the `collection` field with the command name in above mentioned commands;
- unit tests added/updated - check the new tag `collection`;
- spot refactorings were done;

**Comment by AlekSi** [comment]
@adetunjii sure, thank you!
