### ISSUE TITLE
Error updating a document passing its same id with the $set operator

### ISSUE THREAD

**Issue by mkjsix** [FerretDB/FerretDB#2803]
We probably need to move that validation closer to the actual update.

The original issue is below.

---

### FerretDB version

1.2.1

### Backend

PostgreSQL

### Environment

- OS: Mac OS
- Deployment: Docker using ghcr.io/ferretdb/all-in-one:1.2.1 image
- Deployment details: Docker desktop Version 4.20.0 (109717)

### What did you do?

With MongoDB it is possibile to update a document by passing the id, but this gives an error with FerretDB.

For example, here is a mongo shell session against MongoDB 6

```shell
foo [direct: primary] test> db.coll.insertOne({_id:1})
{ acknowledged: true, insertedId: 1 }
foo [direct: primary] test> db.coll.updateOne({_id:1},{$set:{_id:1,a:1}})
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 1,
  modifiedCount: 1,
  upsertedCount: 0
}

foo [direct: primary] test> db.coll.find()
[ { _id: 1, a: 1 } ]
foo [direct: primary] test> db.coll.updateOne({_id:1},{$set:{_id:2,a:1}})
MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'
foo [direct: primary] test> db.coll.updateOne({_id:1},{$set:{_id:1,a:1}})
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 1,
  modifiedCount: 0,
  upsertedCount: 0
}
```

MongoDB raises an error if one tries to update the immutable _id, but it allows one to execute the script if the _id is the same.

With FerretDB the behavior is different. As you can see, FerretDB raises an error even when the _id is the same:

```shell
test> db.test.insertOne({_id:1})
{ acknowledged: true, insertedId: 1 }
test> db.test.updateOne({_id:1},{$set:{_id:1,a:1}})
MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'
```

### What did you expect to see?

We expect no error when updating a document using a command like `db.coll.updateOne({_id:1},{$set:{_id:1,a:1}})` 

### What did you see instead?

The following error is raised: 

```
MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'
```

**Comment by ujibang** [comment]
any news on this? this breaks compatibility with RESTHeart

**Comment by AlekSi** [comment]
We are going to work on that soon.

**Comment by AlekSi** [comment]
@ujibang could you please create a PR with a [test script](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md#reporting-a-bug)?

**Comment by ujibang** [comment]
Hi @AlekSi 

is this PR https://github.com/FerretDB/FerretDB/pull/3136 what you needed?
