### ISSUE TITLE
Invalid validation for `_id` field

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2804]
### FerretDB version

v1.8.0

### Backend

Any.

### Environment

Does not matter.

### What did you do?

```js
db.test.insertOne({_id: 1, v: {_id: ["foo", "bar"]}})`
```

### What did you expect to see?

```js
{ acknowledged: true, insertedId: 1 }
```

### What did you see instead?

```
MongoServerError: The '_id' value cannot be of type array
```

---

Our validation for the `_id` field incorrectly checks nested documents. Only the top-level `_id` field should be checked. See references to this issue in tests.

**Comment by rpavlik** [comment]
Is this related to the fact that connect-mongo works with e.g. 0.9.3 but not with 1.3.0? (It now complains about invalid setting of _id and I'm not doing that anywhere in  my application code)

**Comment by AlekSi** [comment]
@rpavlik I updated the description. Does it look similar to your problem?

**Comment by slavabobik** [comment]
Hi! Can I grab this issue?

**Comment by AlekSi** [comment]
@slavabobik sorry, we missed that 😬 Sure!

**Comment by slavabobik** [comment]
@AlekSi no worrier, in my previous message I forgot to mention you, my bad 😃

**Comment by AlekSi** [comment]
@slavabobik any news? Anything we could help you with?

**Comment by slavabobik** [comment]
@AlekSi I just need a little bit more time, approximately 2-3 days

**Comment by slavabobik** [comment]
@AlekSi I've opened the PR https://github.com/FerretDB/FerretDB/pull/3523

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/pull/3523#discussion_r1356662153

**Comment by slavabobik** [comment]
@AlekSi as I see, you reopened the issue, do I missed(or break) something? I could fix quickly :)
