### ISSUE TITLE
Do not require AMD64v2

### ISSUE THREAD

**Issue by Junnplus** [FerretDB/FerretDB#281]
https://github.com/FerretDB/FerretDB/blob/3b9bea69f2b953dbadd251c77acc1bd19c35335c/Makefile#L104

**Comment by AlekSi** [comment]
Currently, there is no platform-dependent code at all. What architecture do you need?

**Comment by Junnplus** [comment]
@AlekSi I try to run it with docker, but the ferretdb fails to start.
```
# docker logs 7bfe19b42238
This program can only be run on AMD64 processors with v2 microarchitecture support.
```

**Comment by AlekSi** [comment]
You can remove `GOAMD64=v2` and do the local build.
We will remove it in the next release.

**Comment by Junnplus** [comment]
Yes, I remove `GOAMD64=v2` and it can build success.
Can i make PR to fix it ?

**Comment by AlekSi** [comment]
Sure!
