### ISSUE TITLE
Add guidelines for keywords and tags

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#2847]
### What should be done?

We don't currently have guidelines for tags and keywords for our blog.

- Keywords should be content-specific and SEO-related, so long tailed keyword are okay as long as it's related to content and helps search engine discovery. [Research current Docusaurus applications on this]
- Tags are case-sensitive in docusaurus, so a `FerretDB` and `ferretdb` are organized separately. View here https://blog.ferretdb.io/tags/
- All keywords and tags should be small-case
- All tags should be in the plural form, e.g. `document database` is best written as `document databases`. (This depends, as long as it's not present in the list of tags in whatever form)
- Hyphens should be disregarded, e.g. `mongodb-compatible database` should be written as `mongodb compatible database`
- List out all currently used tags, and any newly added tag should be added to the contribution guideline. Let's also establish a set of commonly used tags based on our content direction.

**Comment by AlekSi** [comment]
@Fashander I think we should update out guidelines: not all details present in the issue description were added to the text. For example, "tags should be small-case" become "tags are case-sensitive" which is not the same.
