### ISSUE TITLE
Cleanup stale cursors

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2862]
### What should be done?

We should close and delete cursors that were not `getMore`'d until the end. And add metrics.

TBD

### Where?

See references to this issue.

TBD

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by chilagrow** [comment]
Could we delete cursors based on this issue https://github.com/FerretDB/FerretDB/issues/1808?

**Comment by AlekSi** [comment]
Merged into #2864
