### ISSUE TITLE
Do not `ConsumeValues` in the `$group` aggregation stage

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2863]
### What should be done?

https://github.com/FerretDB/FerretDB/blob/4d40b2b2174c99e3ce3c25d8ec2817a24b1b93d4/internal/handlers/common/aggregations/stages/group.go#L120

But in the end, we iterator over that slice:
https://github.com/FerretDB/FerretDB/blob/4d40b2b2174c99e3ce3c25d8ec2817a24b1b93d4/internal/handlers/common/aggregations/stages/group.go#L220-L221

So we should not use `iterator.ConsumeValues` there.

### Where?

See above.

### Definition of Done

- all handlers updated;
- spot refactorings done.

No test changes are expected.

**Comment by adetunjii** [comment]
Can I take up this issue?

**Comment by AlekSi** [comment]
@adetunjii sure!

**Comment by adetunjii** [comment]
To clarify, we want move `iterator.ConsumeValues` to `groupDocuments()` and consume the values directly from the iterator there right?
