### ISSUE TITLE
Support `maxPoolSize` and `minPoolSize` connection option

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2906]
### What should be done?

https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.maxPoolSize
https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.minPoolSize

See the issue number addressed in the skipped test added by the PR https://github.com/FerretDB/FerretDB/pull/2878

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/clientconn

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by AlekSi** [comment]
Those driver/client options are not visible to FerretDB
