### ISSUE TITLE
Add more metrics for `*sql.DB`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2909]
### What should be done?

We have code that converts `*sql.DB` pool statistics into Prometheus metrics, but it misses some. We should add missing metrics with [good names](https://prometheus.io/docs/practices/naming/).

### Where?

https://github.com/FerretDB/FerretDB/blob/57d71489b27b172f82ffbc0cf589debe83bc4f9b/internal/util/fsql/metrics.go#L74-L75

### Definition of Done

- metrics added.

**Comment by slavabobik** [comment]
Hi! Can I grab this issue?

**Comment by AlekSi** [comment]
Sure, thank you!

**Comment by slavabobik** [comment]
Hi @AlekSi! I've added missed metrics, but could you please help me? I would like to ensure that all of this metrics properly  exists, but I can't see none of them in the output of the command `curl 127.0.0.1:8088/debug/metrics`.

My steps:
- task env-up
- task run-sqlite
- curl 127.0.0.1:8088/debug/metrics

After these steps, `curl` returns output without any of them.

**Comment by slavabobik** [comment]
Thank you! I found interesting behaviour(it's may be only on my side)

My steps:
- task env-up
- task run-sqlite
- curl 127.0.0.1:8088/debug/metrics - response without metrics, as expected
- task mongosh & db.test.insertOne({})

After I hit insert command, it blocks. I run quick debug session, and as I can see it [block on that line](https://github.com/FerretDB/FerretDB/blob/main/internal/backends/sqlite/metadata/registry.go#L234)

Other queries like `count` or `find` works perfectly. If it only on my side, may be I missed some steps to setup env

**Comment by AlekSi** [comment]
🤦 

https://github.com/FerretDB/FerretDB/blob/36ce153cd313996826ba8492f6b58cfe2849bc07/internal/backends/sqlite/metadata/registry.go#L353-L354

Please change `defer r.rw.RLock()` to `defer r.rw.RUnlock()` in your PR. And thank you!

**Comment by slavabobik** [comment]
Thank you, I'm glad I could help! Now it's work perfectly and all metrics presented as expected: 
```
 curl -s 127.0.0.1:8088/debug/metrics | grep '^ferretdb_sqldb'
ferretdb_sqldb_idle{db="test"} 1
ferretdb_sqldb_in_use{db="test"} 0
ferretdb_sqldb_max_idle_closed_total{db="test"} 0
ferretdb_sqldb_max_idle_time_closed_total{db="test"} 0
ferretdb_sqldb_max_lifetime_closed_total{db="test"} 0
ferretdb_sqldb_open{db="test"} 1
ferretdb_sqldb_open_max{db="test"} 0
ferretdb_sqldb_wait_count_total{db="test"} 0
ferretdb_sqldb_wait_duration_seconds_total{db="test"} 0
```

And metrics in case I set single connection:
```
 curl -s 127.0.0.1:8088/debug/metrics | grep '^ferretdb_sqldb'
ferretdb_sqldb_idle{db="test"} 0
ferretdb_sqldb_in_use{db="test"} 1
ferretdb_sqldb_max_idle_closed_total{db="test"} 0
ferretdb_sqldb_max_idle_time_closed_total{db="test"} 0
ferretdb_sqldb_max_lifetime_closed_total{db="test"} 0
ferretdb_sqldb_open{db="test"} 1
ferretdb_sqldb_open_max{db="test"} 1
ferretdb_sqldb_wait_count_total{db="test"} 23133
ferretdb_sqldb_wait_duration_seconds_total{db="test"} 89.623568833
```
