### ISSUE TITLE
Fix parallel collection creation in SQLite

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2923]
### What should be done?

After enabling cursors in #2864 the `TestCollectionName` test started to fail because of database lock (`SQLITE_BUSY`).

### Where?

TBD

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?
TBD

**Comment by AlekSi** [comment]
Duplicate of #2747
