### ISSUE TITLE
Verify that client metadata document has not been mutated

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2989]
### FerretDB version

v1.5.0-1-gcbd9e06a

### Backend

PostgreSQL

### Environment

- OS: Ubuntu 22.10 x86_64
- Deployment: v1.5.0-1
- Deployment details: 23.0.3

### What did you do?

See test script at #3068.

We should verify that a `isMaster` or `hello` request fails if it contains client metadata, and it is not first:

```
> db.runCommand({"hello": 1, "client": {"application": "foobar"}});
{
        "ok" : 0,
        "errmsg" : "The client metadata document may only be sent in the first hello",
        "code" : 186,
        "codeName" : "ClientMetadataCannotBeMutated"
}
>
```

### What did you expect to see?

See above.

### What did you see instead?

```
> db.runCommand({"hello": 1, "client": {"application": "foobar"}});
{
        "isWritablePrimary" : true,
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 100000,
        "localTime" : ISODate("2023-07-05T17:12:33.036Z"),
        "connectionId" : 42,
        "minWireVersion" : 0,
        "maxWireVersion" : 17,
        "readOnly" : false,
        "ok" : 1
}
> 
```

**Comment by AlekSi** [comment]
@b1ron is client metadata documented somewhere?

**Comment by b1ron** [comment]
@AlekSi indeed, it's a URI [option](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.appName).

**Comment by kropidlowsky** [comment]
@AlekSi 

Sure, I can!
