### ISSUE TITLE
Dropping an index should not wait for cursors

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#3005]
### FerretDB version

v1.5.0-1-gcbd9e06a

### Backend

PostgreSQL

### Environment

- OS: Ubuntu 22.10 x86_64
- Deployment: v1.5.0-1
- Deployment details: 23.0.3

### What did you do?

I am too not sure what's happening here exactly but it seems an open cursor will prevent drop indexes from acquiring an exclusive lock on the table. The below message is also logged after some time has passed:

```
LOG: skipping analyze of "block_forever_d2f00f6f" --- lock not available
```

On MongoDB if a cursor's waiting on documents and an interleaving drop index happens that dropped an index depended on by the query, the next `getMore` will get a `QueryPlanKilled` error.

See repro #3004.

### What did you expect to see?

not to block, show dbs does not work but some commands do I suspect one's that are able to acquire a lock. 

### What did you see instead?

It just blocks forever

**Comment by AlekSi** [comment]
That seems to be fixed now
