### ISSUE TITLE
Document new authentication (including SQLite support)

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3008]
### What should be done?

We should document our new experimentation authentication support, including setup flags.

### Where?

Docs.

### Definition of Done

- Documentation updated.

**Comment by muety** [comment]
Am I right in understanding that currently there is no way to do authentication with SQLite whatsoever? That is, when creating to separate databases for two different applications, there is no way of preventing one app from accessing the other's data?

**Comment by muety** [comment]
Second option sounds harder, but also more sensible, because would give us (a) SQLite authentication and (b) a couple more supported commands in addition. Looking forward to having this! Missing SQLite authentication is the only thing that currently keeps me from switching to Ferret for my apps.

**Comment by AlekSi** [comment]
v1.22 support authentication for SQLite via a new experimental flag: https://blog.ferretdb.io/new-ferretdb-v122-user-setup-feature/
What's left is community testing and documentation.

**Comment by Fashander** [comment]
I'm picking this up. Mainly, we need to update these pages:

- https://docs.ferretdb.io/security/authentication/
- https://docs.ferretdb.io/quickstart-guide/docker/ (SQLite authentication now available via experimental new flag)

**Comment by AlekSi** [comment]
It will be out in 1.23 later today!
