### ISSUE TITLE
Implement `nameOnly` for `listCollections` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#301]
`listCollections` command should support `nameOnly` parameter. See references to this issue in the source code.

**Comment by GrandShow** [comment]
I would like to work on this one.

**Comment by AlekSi** [comment]
I did the quick hack to unblock v0.0.6 release, but we still need to implement `nameOnly` and `authorizedCollections` parameters properly.

**Comment by AlekSi** [comment]
We forgot to do it for `listCollections` command

**Comment by kropidlowsky** [comment]
I would like to work on it
