### ISSUE TITLE
Reorganise code for updating document

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3013]
### What should be done?

`UpdateDocument(...)` currently takes all parameter needed for all update operators. Some operator such as `$set` needs `filter` and `IDs` that exist in current collection (See PR https://github.com/FerretDB/FerretDB/pull/3009). It is getting out of control to keep adding needed parameters to `UpdateDocument` function.

Reorganize code so requirement/inputs of each operator can be self contained.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/update.go

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by wazir-ahmed** [comment]
@chilagrow Is this issue covered by #4069? Or the goal of this issue is different?

**Comment by chilagrow** [comment]
@wazir-ahmed 
Let's keep it, this issue was about reorganising arguments to `UpdateDocument()` function. :hugs:

**Comment by wazir-ahmed** [comment]
Okay. Most of the code in previous `UpdateDocument` has been moved to `processUpdateOperator`. So, is this still about `UpdateDocument`? or `processUpdateOperator` ?

**Comment by chilagrow** [comment]
@wazir-ahmed actually it's outdated. This can be marked as done as we know have clear separation between replacing and updating with operator from your work :+1: Thanks for spotting this!
