### ISSUE TITLE
Add validation for `$set` update operator for immutable _id

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3017]
### What should be done?

Validation of immutable `_id` was removed because `$set` operator needs to fetch information about existing IDs and filter value, see commit for more info https://github.com/FerretDB/FerretDB/pull/3009/commits/d7e53c4337a4fc23b4b055ef489d3fc3ab1b8dc5 in PR https://github.com/FerretDB/FerretDB/pull/3009.

This was not done because update requires reorganising work https://github.com/FerretDB/FerretDB/issues/3013.

There is a case where different ID does not throw error on `db.coll.updateOne({_id:1},{$set:{_id:2}})` if the collection does not contain querying `{_id: 1}`.

MongoDB with `task run-proxy`
```
test> db.coll.find()

test> db.coll.updateOne({_id:1},{$set:{_id:2, a:"new"}}) // different _id doesn't fail but nothing is updated
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 0,
  modifiedCount: 0,
  upsertedCount: 0
}
test> db.coll.find()

test> db.coll.insertOne({_id:1, v: "1"})
{ acknowledged: true, insertedId: 1 }
test> db.coll.updateOne({_id:1},{$set:{_id:2, v:"2"}}) // now updating different _id fails
MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'
test> db.coll.updateOne({_id:1},{$set:{_id:1, v:"new"}}) // you can always update same _id
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 1,
  modifiedCount: 1,
  upsertedCount: 0
}
```

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/update.go

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by wazir-ahmed** [comment]
@AlekSi I would like to pick this up next.
