### ISSUE TITLE
Reorganise `upsert` handling in `update` and `findAndModify`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3040]
### What should be done?

`upsert` logic for `update` and `findAndModify` are scattered and doesn't quite have an architecture. This makes following code extremely difficult.

SQLite handler also does not handle update in a transaction, that means a document updated can be modified between query and update is applied.

See the issue links in the code.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/findandmodify.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/pg/msg_update.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/pg/msg_findandmodify.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/sqlite/msg_update.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/sqlite/msg_findandmodify.go

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;

**Comment by wazir-ahmed** [comment]
@AlekSi I'm trying to refactor the `findAndModify` and `update` logic along with addressing #3017.
