### ISSUE TITLE
Integration tests should report their progress

### ISSUE THREAD

**Issue by quasilyte** [FerretDB/FerretDB#3055]
See https://github.com/FerretDB/FerretDB/issues/3055#issuecomment-1735504165.

---

### What should be done?

The integration tests should print something meaningful to the console once in a while, like "running test 24/1032".

Right now they can take 10-30 minutes on a dev machine without printing a thing. The terminal looks like it hangs, there is no indication of progress. A natural reaction to that is `ctrl+C` (which doesn't allow the tests to complete).

It could be a good idea to disable this progress printing when running the tests from CI (to avoid some redundant logs in a non-interactive environment).

### Where?

The integration tests runner maybe?
I haven't looked at the relevant test runner yet. :swe

### Definition of Done

- test runner is updated

**Comment by AlekSi** [comment]
This is tricky. Currently, we run integration tests with just `go test` that consumes all output:

```go
t.Log("t.Log")
fmt.Println("fmt.Println")
log.Println("log.Println")
os.Stdout.WriteString("os.Stdout\n")
os.Stderr.WriteString("os.Stderr\n")
```

All that output is not visible until and unless the test fails. That's just how `go test` without `-v` flag works.

What we could do is to extend `envtool` to:
1. Invoke `go test -json`.
2. Stream and parse its output.
3. Print progress report (we already know test names and count from existing sharding code).
4. Print the full test output as text when a test fails (like `go test` does).

**Comment by rubiagatra** [comment]
Please let me understand code base first @AlekSi. I Created draft https://github.com/FerretDB/FerretDB/pull/3471/files. 

Should I extend envtool on https://github.com/FerretDB/FerretDB/blob/main/cmd/envtool/tests.go? for the parser?

**Comment by AlekSi** [comment]
Yep, you are on the right track!

**Comment by AlekSi** [comment]
@rubiagatra any news? Anything we could help you with?

**Comment by rubiagatra** [comment]
I kinda understand the flow right now, Should I add 

```
p, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}

var r io.Reader = p
```

in `runCommand` at envtool?

also after that should I add

```
	d := json.NewDecoder(r)
	d.DisallowUnknownFields()

	res := &config.TestResults{
		TestResults: make(map[string]config.TestResult),
	}

	for {
		var event testEvent
		if err = d.Decode(&event); err != nil {
			if err == io.EOF {
				break
			}
			return nil, err
		}

		// skip package failures
		if event.Test == "" {
			continue
		}

		testName := event.Package + "/" + event.Test

		result := res.TestResults[testName]
		if result.Status == "" {
			result.Status = config.Unknown
		}

		result.Output += event.Output

		switch event.Action {
		case actionPass:
			result.Status = config.Pass
		case actionFail:
			result.Status = config.Fail
		case actionSkip:
			result.Status = config.Skip
		case actionBench, actionCont, actionOutput, actionPause, actionRun:
			fallthrough
		default:
			result.Status = config.Unknown
		}

		res.TestResults[testName] = result
	}
```

after `cmd.Run()` ?

appreciate your guidance @AlekSi

**Comment by rubiagatra** [comment]
Okay let me try first and I will update my PR thanks!
