### ISSUE TITLE
Support operators in query projection

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3075]
### What should be done?

Operator support was added in aggregation projection, we should do the same for query projection.

See issue link added by PR https://github.com/FerretDB/FerretDB/pull/3063

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/projection.go

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
@chilagrow I'm pretty sure that's #835. Please use that issue.

**Comment by AlekSi** [comment]
Duplicate of #835

**Comment by chilagrow** [comment]
Ouch thanks, my search skill is pretty bad :see_no_evil:
