### ISSUE TITLE
Support for in-memory SQLite

### ISSUE THREAD

**Issue by tbnguyen1407** [FerretDB/FerretDB#3084]
### What should be done?

Currently SQLite backend only accepts directory path as URI. Is it possible to add support for in-memory? Sample URIs:

```
:memory:
file::memory:
```

Thank you.

**Comment by AlekSi** [comment]
Yes, that's planned.

**Comment by AlekSi** [comment]
@tbnguyen1407 it should work already with URI `file:dir/?mode=memory`. `dir/` should be an existing directory, but it will not be actually used.

I will leave the issue open for documenting this.

**Comment by tbnguyen1407** [comment]
@AlekSi thanks I just tested this to just use current directory and it seems fine.

```
file:./?mode=memory
```
