### ISSUE TITLE
Add ability to freeze `*types.Document` and `*types.Array`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3112]
### What should be done?

`*types.Document` and `*types.Array` should have a `Freeze()` method that would disallow any receiver modifications. All future calls that would modify frozen objects (such as `*types.Document.SortFieldsByKey`, `*types.Array.RemoveByPath`, etc.) should panic.

That method will be called in places where we don't expect further modifications; for example, when documents are passed to backend methods.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/types

### Definition of Done

- unit tests added/updated;
- spot refactorings done.

**Comment by KrishnaSindhur** [comment]
I can pick this up

**Comment by AlekSi** [comment]
@KrishnaSindhur Let's finish #3154 first. There is no need to finish the whole issue (there are many cases), but let's finish that PR.
