### ISSUE TITLE
We should ignore Stable API / `apiVersion` / strict parameters

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#3121]
### FerretDB version

v1.7.0

### Backend

PostgreSQL

### Environment

- OS:
- Deployment:
- Deployment details:

### What did you do?

See repro in #3120.

This is not exactly a bug because it's a specific MongoDB parameter which will prevent a client from using commands that are deemed "unstable". The stable API encompasses a subset of commands that will **not** break your application when you upgrade. However, if a client has these parameters enabled it will send them in a command document as top-level fields. We _should_ ignore them.

### What did you expect to see?

I think it's the same issue as #3010, extracting parameters breaks stuff.

### What did you see instead?

```
dance_ferretdb  |         "errmsg": "insert: unknown field \"apiVersion\"",
dance_ferretdb  |         "code": 9,
dance_ferretdb  |         "codeName": "FailedToParse"
```

**Comment by chilagrow** [comment]
Do we have a list of commands that sends Stable API parameters? I found this page https://www.mongodb.com/docs/manual/reference/stable-api-changelog/#std-label-stable-api-changelog

**Comment by AlekSi** [comment]
on @Evengard
