### ISSUE TITLE
Fix indexes for SQLite

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#3183]
### What should be done?

```
=== RUN   TestUpdateCompat/ReplaceNonExistentUpsert/TestUpdateCompat-ReplaceNonExistentUpsert_Strings/string-double
    update_compat_test.go:565: Target error: (InternalError) [msg_update.go:46 sqlite.(*Handler).MsgUpdate] [collection.go:114 sqlite.(*collection).Insert] constraint failed: UNIQUE constraint failed: index 'testupdatecompat-replacenonexistentupsert_strings_61bfb088_id' (2067)
```

TBD

### Where?

- issue url mentions

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by AlekSi** [comment]
At least a part of it is already fixed, I think
