### ISSUE TITLE
Add tracing for `*sql.DB`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3218]
### What should be done?

We should have OpenTelemetry tracing for `*sql.DB`-based backends.

We should also make it and pgx's tracing, logging, and metrics similar to each other.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/util/fsql

### Definition of Done

TBD

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by jyz0309** [comment]
Can I take this issue? Want to try it :)

**Comment by AlekSi** [comment]
@jyz0309 feel free to start, but please understand that we don't know yet what the end result should look like, so working on that issues could be a bit frustrating

**Comment by jyz0309** [comment]
sure :) i will take a try and made a demo.

**Comment by jyz0309** [comment]
I have read the code in `/internal/backends/postgresql`, want to ask: 
The issue say that `We should also make it and pgx's tracing, logging, and metrics similar to each other` but it seems that `postgresql` pkg have not otel tracing, should I add it too?

**Comment by AlekSi** [comment]
@jyz0309 any news? Anything we could help you with?

**Comment by AlekSi** [comment]
Please start FerretDB with `task run` and provide the full output of `task mongosh`.
