### ISSUE TITLE
Move PostgreSQL backend to the new architecture

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3228]
After #3069, we need to migrate our existing PostgreSQL backend to the new architecture. Additionally, we should add support for other "PostgreSQL-like" backends (forks, extensions, protocol-compatible databases):  YugaByte, CockroachDB, Timescale, and YBD. We should try to combine them all in a single backend if that's easy and possible.

Note that the full support for PostgreSQL-like backends would likely require #226.

```[tasklist]
### PostgreSQL
- [ ] #3415
- [ ] #3416
- [x] Enable it by default, update changelog and docs
- [ ] #3243
- [ ] #3335
- [ ] #3388
- [ ] #3375
- [ ] #3404
- [ ] #3406
- [ ] #3393
- [ ] #3395
- [ ] #3400
- [ ] #3391
- [ ] #3389
- [ ] #3394
- [ ] #3399
- [ ] #3397
- [ ] #3398
- [ ] #3402
- [ ] #3414
- [ ] #3392
```

**Comment by JerrySievert** [comment]
have you already tested the hydra columnar store, or do you plan to include it in this overarching issue?

**Comment by FlyingOnion** [comment]
Hi, I'm new to this project. Are you planning to move the codes from `internal/handlers/pg/pgdb` to `internal/backends/postgresql`?

**Comment by AlekSi** [comment]
Yes, but also rewrite it in the process
