### ISSUE TITLE
Use multi-stage Docker build

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#323]
We should build FerretDB binary for Docker image inside Docker container using [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/).

* [x] Build all images with race detector and test coverage.
* [x] Build separate images for development (`ferretdb-dev` with race detector, test coverage, etc) and production (`ferretdb` image without race detector and test coverage).

See also #70.

**Comment by AlphaB** [comment]
@AlekSi should we use `latest` tag for build step or it's better to fix minor version on 1.18?

**Comment by AlekSi** [comment]
I think the best way would be to use `:1.18.2` and update Dependabot config to track changes

**Comment by AlphaB** [comment]
@AlekSi We won't be able to use race detector with `scratch` image since it requires `cgo`.

**Comment by AlekSi** [comment]
@AlphaB I think we should build two images:
* "release" image without race detector, code coverage, etc.
* "development" image with all that.

**Comment by AlekSi** [comment]
We will do the second task closer to v1.0.0
