### ISSUE TITLE
Cleanup and optimize inserts

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3271]
### What should be done?

Currently, both PostgreSQL and SQLite backends insert documents one by one: the `insert` command handler calls `Collection.InsertAll` with one document. We should pass more documents in one call. The trick is with error handling and `ordered` inserts: if `InsertAll` returned an error, we should retry those documents one by one to understand which one caused a problem. We already should have integration tests and benchmarks for that, but it is worth checking them.

Once this is done, we should optimize `Collection.InsertAll` methods themselves to insert multiple (say, 100) documents with a single `INSERT` statement.

See references to this issue in the code.

### Where?

https://github.com/FerretDB/FerretDB/blob/9475382b5923d1e3745f02903a3ca33e06bc3962/internal/handlers/sqlite/msg_insert.go#L140-L141

https://github.com/FerretDB/FerretDB/blob/9475382b5923d1e3745f02903a3ca33e06bc3962/internal/backends/postgresql/collection.go#L127-L128

https://github.com/FerretDB/FerretDB/blob/9475382b5923d1e3745f02903a3ca33e06bc3962/internal/backends/sqlite/collection.go#L116-L117

### Definition of Done

- new handler updated;
- integration/compatibility tests checked.

**Comment by princejha95** [comment]
Will pick this up.

Thanks

**Comment by princejha95** [comment]
I checked and there is neither benchmark test nor IT exist for testing this method. I was able to find only UTs for this. Can you please let me know if i missed something ?

cc: @AlekSi

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/blob/d8ac329267a3dd5751d6c124d7c61af9e19ef423/integration/benchmarks_test.go#L133

**Comment by princejha95** [comment]
> https://github.com/FerretDB/FerretDB/blob/d8ac329267a3dd5751d6c124d7c61af9e19ef423/integration/benchmarks_test.go#L133

Sorry but i think i am missing something. This method calls `insertMany`, how it is testing `insertAll` method ? Might be a naive question but can't help myself.

Thanks,
Prince

**Comment by AlekSi** [comment]
[`InsertMany`](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Collection.InsertMany) is a MongoDB driver's method. It, along with other methods like [`InsertOne`](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Collection.InsertOne), call [`insert`](https://www.mongodb.com/docs/manual/reference/command/insert/) MongoDB command. FerretDB implements this command [there](https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/sqlite/msg_insert.go). The implementation calls `Collection.InsertAll` [there](https://github.com/FerretDB/FerretDB/blob/d7493f75f0d8d9109dd3cc816e529425fea93cd6/internal/handlers/sqlite/msg_insert.go#L143).

**Comment by princejha95** [comment]
Got it. Thanks

**Comment by chilagrow** [comment]
@AlekSi, for inserting documents, do we want this size to be controlled in handler or backend.

For example 
1) handler calls InsertAll with all documents, then each backend inserts say batches of 100.
2) hanlder creates batches of 100 documents and calls InsertAll, then the backend inserts all of them.

**Comment by AlekSi** [comment]
Both (just like the description says)
