### ISSUE TITLE
SQLite Empty Aggregate returns "I'm a stub, not a real handler for aggregate"

### ISSUE THREAD

**Issue by BoBiene** [FerretDB/FerretDB#3273]
### FerretDB version

1.9

### Backend

SQLite

### Environment

- OS: Linux
- Deployment: ghcr.io/ferretdb/ferretdb:1.9.0
- Deployment details: Docker on Ubuntu

### What did you do?

Query with empty aggregate 

### What did you expect to see?

All elements from the collection

### What did you see instead?

"I'm a stub, not a real handler for aggregate"

**Comment by AlekSi** [comment]
It will be available in v1.10.0.

**Comment by AlekSi** [comment]
Duplicate of #3148
