### ISSUE TITLE
Add more tests for `findAndModify`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3306]
### What should be done?

`findAndModify` has logic that are not covered by tests. Add more tests to cover them.

See also issue links added by https://github.com/FerretDB/FerretDB/pull/3302

### Where?

https://github.com/FerretDB/FerretDB/blob/main/integration/findandmodify_compat_test.go
https://github.com/FerretDB/FerretDB/blob/main/integration/findandmodify_test.go

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
Could we use #2168, #2854, and/or #3040 instead?

**Comment by chilagrow** [comment]
Duplicate of https://github.com/FerretDB/FerretDB/issues/2168
