### ISSUE TITLE
Fix tests for MongoDB with enabled replica set

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3310]
### What should be done?

We should enable MongoDB's replica set (with a single node) and fix all failing tests.

Tests should be fixed in a way that would allow them to pass with FerretDB, with MongoDB without replica set, and with MongoDB with replica set. That basically means we should remove `$clusterTime` and `operationTime` fields from actual responses before comparing them with expected ones. See #3307 for an example.

### Where?

See references to this issue.

### Definition of Done

- replica set enabled for `mongodb` service;
- integration/compatibility tests updated;
- spot refactorings done.

**Comment by KrishnaSindhur** [comment]
@shibasisp yes please go ahead!!

**Comment by shibasisp** [comment]
@AlekSi Unfortunately, due to some unexpected work commitments, I won't be able to continue with this issue for now. 
Please feel free to reassign it to someone else, and I'll definitely be back to contribute when I have more time.

**Comment by KrishnaSindhur** [comment]
I can look into this meanwhile i have some time

**Comment by AlekSi** [comment]
@rumyantseva that's issue wasn't assigned by accident – other issues higher in Open are more important

**Comment by AlekSi** [comment]
(start date wasn't set)
