### ISSUE TITLE
Replace deprecated `go.opentelemetry.io/otel/exporters/jaeger`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3341]
### What should be done?

https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger@v1.17.0 says:

> Deprecated: This module is no longer supported. OpenTelemetry dropped support for Jaeger exporter in July 2023. Jaeger officially accepts and recommends using OTLP. Use [go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp) or [go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc) instead.

We should replace that package.

### Where?

Currently, it is used only by our integration tests, but when this issue is picked up, it could be used elsewhere.

### Definition of Done

This package is no longer imported without the loss of functionality.

**Comment by adetunjii** [comment]
Can I look into this issue?

**Comment by AlekSi** [comment]
Sure!

**Comment by AlekSi** [comment]
@adetunjii, without knowing much about OT, I _think_ we should use `otlptracehttp` to avoid otherwise unnecessary gRPC dependency.
