### ISSUE TITLE
Implement validation for `dropIndexes` command

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#3342]
### What should be done?

This issue is similar to #3320. Currently, we don't have much validation for `dropIndexes`. Because of this, some tests are marked failed. 

### Where?

See TODOs in the code.

### Definition of Done

- validation implemented;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by AlekSi** [comment]
Duplicate of #3320

**Comment by rumyantseva** [comment]
@AlekSi let's keep them separate to have smaller PRs?
