### ISSUE TITLE
A multi-update will terminate too early upon a validation failure

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#3351]
### FerretDB version

In MongoDB, it seems that if an update with multi-true, tries to modify a field that causes a validation error it will terminate the update without modifying subsequent documents.

This behavior is consistent in SQLite but not in PostgreSQL.

### Backend

PostgreSQL

### Environment

- OS:
- Deployment:
- Deployment details:

### What did you do?

See #3352.

### What did you expect to see?

The first document updated:

```sh
> t.find()
{ "_id" : ObjectId("65017c093bcc164ebd17079a"), "a" : [ 2 ] }
{ "_id" : ObjectId("65017c093bcc164ebd17079c"), "a" : 1 }
{ "_id" : ObjectId("65017c093bcc164ebd17079e"), "a" : [ ] }
```

### What did you see instead?

Nothing updated

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/pull/3352#issuecomment-1905626886

**Comment by AlekSi** [comment]
It was fixed some time ago
