### ISSUE TITLE
db.collection.find() works differently for FerretDB and for MongoDB

### ISSUE THREAD

**Issue by ribaraka** [FerretDB/FerretDB#336]
The ferretDB finds certain numbers according to the data type, while MongoDB finds all numbers, according to `filter`, no matter if it's int32/64 or even if it's located in array.

There is my output in `MongoDB`:
 **db.values.find({"value": 42})**
{ "_id" : ObjectId("612ec2800000040100000401"), "name" : "array", "value" : [ "array", 42 ] }
{ "_id" : ObjectId("612ec2800000040400000404"), "name" : "array-three", "value" : [ 42, "foo", null ] }
{ "_id" : ObjectId("612ec2800000100100001001"), "name" : "int32", "value" : 42 }
{ "_id" : ObjectId("612ec2800000120100001201"), "name" : "int64", "value" : NumberLong(42) }

And `FerretDB` Output:
**db.values.find({"value": 42})**
[ { _id: ObjectId("612ec2800000100100001001"),  name: 'int32', value: 42  }] 

As you can see, there is only one value found for Ferret DB.

**Comment by ribaraka** [comment]
I have already begun to study this moment with the bug and I want to take on solving it myself, since my [task](https://github.com/FerretDB/FerretDB/issues/251) that I have been doing depends on the solution of this problem.

**Comment by AlekSi** [comment]
I'm not sure if the problem is still present (it is possible I accidentally fixed it), but we definitely need handler and dance tests for it.

If something should be changed, it is likely there: https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/compare.go
