### ISSUE TITLE
Store index metadata

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3375]
### What should be done?

Information about indexes should be stored in metadata in the same way as in the old `pgdb` package.

Create unique index for `_id` when collection is created.

Only metadata/registry changes are in the scope. The rest is in #3394, #3399, #3397.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/backends/postgresql/metadata

### Definition of Done

- unit tests added/updated;
- spot refactorings done.

**Comment by AlekSi** [comment]
There is a bug: #3505
