### ISSUE TITLE
Implement `Explain`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3389]
### What should be done?

Implement `Explain` method for queries just like in `pgdb`.

Integration tests are not in the scope; they should be updated in #3414, #3415, #3416.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go

### Definition of Done

- method implemented;
- spot refactorings done.

**Comment by adetunjii** [comment]
@AlekSi Please can I be assigned to this issue?
