### ISSUE TITLE
Implement Prometheus collector for `Registry`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3392]
### What should be done?

Implement `internal/backends/postgresql/metadata.Registry.Collect` to return basic metrics about a number of databases and collections in the Registry. See SQLite backend as an example: https://github.com/FerretDB/FerretDB/blob/d976d8c5792454e04ab19b01db53a01f38131429/internal/backends/sqlite/metadata/registry.go#L565-L594

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/metadata/registry.go

### Definition of Done

- method implemented;
- spot refactorings done.

**Comment by Mihai22125** [comment]
Hello! I'd like to work on this item. Could you assign it to me, please?

**Comment by AlekSi** [comment]
@Mihai22125 done!
