### ISSUE TITLE
Implement `ListIndexes`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3394]
### What should be done?

Implement `ListIndexes` method.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go
https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/metadata/metadata.go

### Definition of Done

- method implemented;
- spot refactorings done.

**Comment by AlekSi** [comment]
There are references to this issue
