### ISSUE TITLE
Implement collection `Stats`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3398]
### What should be done?

Implement collection `Stats` method.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go

### Definition of Done

- method implemented;
- spot refactorings done.

**Comment by princejha95** [comment]
> ### What should be done?
> Implement collection `Stats` method.
> 
> ### Where?
> https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go
> 
> ### Definition of Done
> * method implemented;
> * spot refactorings done.

It will be great if you can give a little briefing about what this PR is all about. What will be changed once this feature is implemented so that a newbie like me can get to understand what is going across the codebase for better understanding. :)

Thanks

**Comment by chilagrow** [comment]
Hey @princejha95 this is already in progress, not available for pick up sorry.
