### ISSUE TITLE
Implement `ListCollections`, `CreateCollection`, and `DropCollection`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3406]
### What should be done?

Implement `ListCollections`, `CreateCollection`, and `DropCollection`methods.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/database.go

### Definition of Done

- methods implemented;
- spot refactorings done.

**Comment by Azanul** [comment]
May I take this up?

**Comment by Azanul** [comment]
Also, can I do it as a part of Hacktoberfest?
