### ISSUE TITLE
Some backend tests are fluky

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3409]
### What should be done?

SQLite:
* https://github.com/FerretDB/FerretDB/actions/runs/6262515571/job/17004858668?pr=3407
* https://github.com/FerretDB/FerretDB/actions/runs/6301692434/job/17107283075?pr=3430
* https://github.com/FerretDB/FerretDB/actions/runs/6416041905/job/17419012857?pr=3496

PostgreSQL:
* https://github.com/FerretDB/FerretDB/actions/runs/6271012235/job/17029850391?pr=3411
* https://github.com/FerretDB/FerretDB/actions/runs/6496580977/job/17643830496?pr=3565

We should either fix the test or our code.

### Where?

Integration tests, unit tests.

### Definition of Done

Test or code fixed.

**Comment by rumyantseva** [comment]
See also https://ferretdb.slack.com/archives/C02NWN1K3MJ/p1695984191528039.
