### ISSUE TITLE
Implement sort pushdown

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3415]
### What should be done?

We should implement collection query sort pushdown as in `pgdb`.

Relevant integration tests should pass.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go

### Definition of Done

- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by adetunjii** [comment]
@AlekSi can I be assigned this issue?

**Comment by adetunjii** [comment]
Alright great thanks.
