### ISSUE TITLE
Add SQLite info to glossary list

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#3427]
### What should be done?

In our glossary page https://docs.ferretdb.io/reference/glossary/, we need to include information on 

- SQLite: Mention that we now offer SQLite backend support.

**Comment by OsamaNabih** [comment]
Hello there, isn't it already mentioned or am I misunderstanding? https://docs.ferretdb.io/understanding-ferretdb/#sqlite

**Comment by Fashander** [comment]
> Hello there, isn't it already mentioned or am I misunderstanding? https://docs.ferretdb.io/understanding-ferretdb/#sqlite

@OsamaNabih Yes, it is mentioned in that section, but not in the glossary page where we describe terminologies for FerretDB: https://docs.ferretdb.io/reference/glossary/. 

It should have an almost similar description to that of PostgreSQL.

**Comment by Fashander** [comment]
Hi @OsamaNabih Is there any update on this and do you need help with it?

**Comment by pvinoda** [comment]
Hi please find the PR that closes this Issue.
Link: https://github.com/FerretDB/FerretDB/pull/3593
