### ISSUE TITLE
Add `$project` and `$unset` to documentation

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#3428]
### What should be done?

`$project` and `$unset` are currently [supported commands](https://docs.ferretdb.io/reference/supported-commands/#aggregation-pipeline-stages), and this should be reflected here https://docs.ferretdb.io/aggregation-operations/aggregation-stages/.

**Comment by Akhaled19** [comment]
Hi there! I would like to contribute to this issue ~ Here is what I understood: need to add `$project` and `$unset` commands to the Aggregation Stages list and give them a description as well https://github.com/FerretDB/FerretDB/blob/main/website/docs/aggregation-operations/aggregation-stages.md?plain=1 . What shall the description be? Thank you in advance

**Comment by AlekSi** [comment]
@Fashander please confirm

**Comment by Akhaled19** [comment]
Thank you @Fashander, for getting back to me.  Let me know if these definitions meet your requirements. `$project:  Specifies n number of fields in a document to pass to the next stage in the pipeline. 
$unset: Specifies n number of fields to be removed/excluded from a document. $unset is an alias for the $project stage. `

**Comment by Fashander** [comment]
> Thank you @Fashander, for getting back to me. Let me know if these definitions meet your requirements. `$project: Specifies n number of fields in a document to pass to the next stage in the pipeline. $unset: Specifies n number of fields to be removed/excluded from a document. $unset is an alias for the $project stage. `

This is good, thanks! Please send a PR, and I'll leave comments if necessary.
