### ISSUE TITLE
Add option to share listener/handler/backend between integration tests

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3442]
### What should be done?

Currently, our integration tests share a few things:
* debug handler with pprof, execution tracer, metrics, etc;
* `listenerMetrics` for the above handler;
* OTLP exporter for traces.

There should be a flag `-share-server` (false by default) that would make all tests share a single instance of listener/handler/backend. It should be started once in `setup.Startup` and stopped in `setup.Shutdown`. Functions like `setupListener` should return that shared listener/handler/backend.

This is likely the underlying reason for #3409, but fixing it or other integration test failures is not in the scope.
`Taskfile.yml` changes are not in the scope. That flag should be tested manually.

The MongoDB client should not be shared.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/integration/setup

### Definition of Done

- flag implemented;
- spot refactorings done.

**Comment by Mihai22125** [comment]
Hi @AlekSi, I'd like to give it a shoot. Can you assign it to me, please?

**Comment by AlekSi** [comment]
So, uh, while working on #3463 I realized why we don't want to do it, at least not yet. Creating test-specific listener/handler/backend allows us to use test-specific loggers. If a test passes, no output will be visible. If a test fails, only logs of that test's l/h/b will be visible. If we share l/h/b, one failing test will show a lot of output from other tests. I don't think we should try to solve that problem now.

Sorry.
