### ISSUE TITLE
Add operation modes definition to glossary list

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#3445]
### What should be done?

In the glossary list https://github.com/FerretDB/FerretDB/blob/main/website/docs/reference/glossary.md, we need to include information about FerretDB Operation modes.

DoD:

- Add a definition for `Operation modes` in FerretDB under section "O"
- Link to the Operation modes page at https://docs.ferretdb.io/configuration/operation-modes/

See the writing guide for help: https://docs.ferretdb.io/contributing/writing-guide/

**Comment by rohitkbc** [comment]
Hi @Fashander 👋, Can you assign this task to me once it is ready?
