### ISSUE TITLE
Remove `pgdb` from `envtool`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3452]
### What should be done?

`envtool` should use the new PostgreSQL backend (probably, `metadata/pool` package), not `pgdb`.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

- `envtool` no longer uses `pgdb`;
- spot refactorings done.

**Comment by ShatilKhan** [comment]
Hi, please assign me this issue @AlekSi

**Comment by ShatilKhan** [comment]
Hi, thanks for assigning @AlekSi 
I am new to this codebase & had a few questions regarding this issue
I found the `pgdb` section on this page `FerretDB/blob/main/cmd/envtool/envtool.go`
Here's the section 
![image](https://github.com/FerretDB/FerretDB/assets/52494840/fd3a4b78-2b83-405d-a3de-53e5ab9ae331)
By my understanding, I'm only supposed to remove any function or lines regarding `pgdb` , right?

**Comment by ShatilKhan** [comment]
@AlekSi I've made a PR, please let me know if there's any reviews

**Comment by AlekSi** [comment]
> By my understanding, I'm only supposed to remove any function or lines regarding pgdb , right?

The issue description says that:

> `envtool` should use the new PostgreSQL backend (probably, `metadata/pool` package), not `pgdb`.

It does not say that this code should be removed without replacement
