### ISSUE TITLE
Support capped collection clean-up

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3459]
### What should be done?

After #3466, #3467, and #3498, we should add support for cleaning up capped collections.

Let's start a background goroutine in the handler that would do the following every minute (configurable with a test flag) if `EnableOplog` is `true`:
* iterate over a list of databases;
* iterate over a list of capped collections in those databases;
* run `Collection.Stats` on the current collection;
* if stats are lower than capped collection parameters, continue to the next collection;
* query 10% (configurable with a test flag) RecordIDs of documents in this collection (with `Limit` and `OnlyRecordIDs` set);
* delete them;
* compact that collection.

The last step essentially involves the calling of the `compact` command with `force: false` (#3466). We should not call that command handler directly but refactor it to make the shared code callable from the handler and our background goroutine.

Databases and collections could disappear during the iteration; that should be handled.

The goroutine should not `panic` and not `recover`.
We should add basic logging and metrics for that background goroutine.

Most of the logic should already be tested. No new automated tests are necessary.

### Where?

The handler. All backend changes should already be done by that point.

### Definition of Done

- handlers updated;
- all backends tested manually;
- spot refactorings done;
- user documentation checked and updated.

**Comment by slavabobik** [comment]
Hi @AlekSi! Can I grab this issue? As I can see dependent tasks are mostly done(https://github.com/FerretDB/FerretDB/issues/3498 has opened PR). Or feel free please to suggest more suitable task on your opinion

**Comment by AlekSi** [comment]
@slavabobik feel free to pick up this task, just not try to do everything in a single PR

**Comment by AlekSi** [comment]
@slavabobik any news? Anything we could help you with?

**Comment by slavabobik** [comment]
@AlekSi Hi! sorry for the delay, I'm started work on this only today, and I'm try to keep updates more frequently

**Comment by rumyantseva** [comment]
Commands for manual testing (slow but good enough for testing purposes). Create a capped collection and insert docs:

```
mongosh --port=27017 --eval="db.createCollection('coll', {capped: true, size: 1000, max: 50})" cleanup

for in in (seq 100)
   mongosh --port=27017 --eval="db.coll.insert({data: 'document $i'})" cleanup
end
```

Check metrics and logs to ensure that cleanup goroutine is running.
