### ISSUE TITLE
Add test for tailable cursor with non-capped collection

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3462]
### What should be done?

Tailable cursors do not work with non-capped collections. Let's add an integration test for that.

The test should pass for MongoDB and the current FerretDB handler.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/integration/query_test.go

### Definition of Done

- the handler updated;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by michiboo** [comment]
Hello is this issue still open? I would like to work on it

**Comment by AlekSi** [comment]
@michiboo yep, thank you!

**Comment by AlekSi** [comment]
@michiboo any news? Anything we could help you with?

**Comment by michiboo** [comment]
Hello I am having troubles of setting up ferretdb, will share the log later on slack or here
