### ISSUE TITLE
Implement `compact` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3466]
### What should be done?

After #3484 and #3469, we should implement that command in the handler: https://www.mongodb.com/docs/manual/reference/command/compact/

The implementation should:
* run `Collection.Stats` method to get the current statistics;
* run `Collection.Compact` to compact it;
* run `Collection.Stats` method again to get the new statistics;
* log the difference between all metrics, and return the relevant one as `bytesFreed`.

If `force` is true, `Compact` should be called with `Full: true`. (There is a semantic difference between `force` and `full`, but that's fine.)

Errors (missing database, missing collection) should be returned as in MongoDB.

### Where?

* https://github.com/FerretDB/FerretDB/tree/main/internal/handlers/sqlite

Old `pgdb` handler should not be updated (or updated with a stub if required).

### Definition of Done

- handler updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated.

**Comment by adetunjii** [comment]
@AlekSi Please assign me to this.
