### ISSUE TITLE
Implement `Collection.Compact` for SQLite

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3469]
### What should be done?

SQLite's backend `Collection.Compact` method should call [`PRAGMA incremental_vacuum`](https://www.sqlite.org/pragma.html#pragma_incremental_vacuum) and then [`ANALYZE`](https://www.sqlite.org/lang_analyze.html) on the given collection/table.

When `Full` is true, [`VACUUM`](https://www.sqlite.org/lang_vacuum.html) should be run instead of `PRAGMA incremental_vacuum`.

If the database or collection does not exist, `ErrorCodeDatabaseDoesNotExist` or `ErrorCodeCollectionDoesNotExist` should be returned (that's already checked by the contact and backend test).

### Where?

* https://github.com/FerretDB/FerretDB/blob/main/internal/backends/sqlite/collection.go
* https://github.com/FerretDB/FerretDB/blob/main/internal/backends/collection_test.go

### Definition of Done

- SQLite backend updated;
- `Skip` removed from the test.

**Comment by Akhil-2001** [comment]
Hey @AlekSi, I'd like to try tackling this issue. Since I'm quite new to this, a short background would help me get going. Looking forward to get involved with this project.
