### ISSUE TITLE
Make `collStats` calculate collection size accurately after deletions of documents

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3483]
### What should be done?

[Capped collections](https://www.mongodb.com/docs/manual/core/capped-collections/) are fixed size collections.

Currently in PostgreSQL backend, `collStats` calculates collection size using `pg_table_size` and `pg_indexes_size`.

When we introduce capped collections, assuming running vacuum full is unlikely, the capped collection after many deletions and insertions will only increase in size with the current way of calculating collection size. This is inaccurate reflection of capped collection.

This issue is about finding way to report actual used size disregarding deleted items in the table.

This applies to both PostgreSQL and SQLite.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go
https://github.com/FerretDB/FerretDB/blob/main/internal/backends/sqlite/collection.go

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
I think as a part of this issue we should make a unified backend test, not two different sets of tests for two backends
