### ISSUE TITLE
Implement `Collection.Compact` for PostgreSQL

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3484]
### What should be done?

PostgreSQL's backend `Collection.Compact` method should call [`VACUUM ANALYZE`](https://www.postgresql.org/docs/current/sql-vacuum.html) on the given collection/table.

When `Full` is true, `VACUUM FULL ANALYZE` should be run instead.

If the database or collection does not exist, `ErrorCodeDatabaseDoesNotExist` or `ErrorCodeCollectionDoesNotExist` should be returned (that's already checked by the contact and backend test).

### Where?

* https://github.com/FerretDB/FerretDB/blob/main/internal/backends/postgresql/collection.go
* https://github.com/FerretDB/FerretDB/blob/main/internal/backends/collection_test.go

### Definition of Done

- PostgreSQL backend updated;
- `Skip` removed from the test.

**Comment by alhridoy** [comment]
Hi @AlekSi i would like to work on that. Please assign me for that

**Comment by AlekSi** [comment]
@alhridoy Done! We just merged #3485 that added stubs for this method

**Comment by alhridoy** [comment]
@AlekSi sounds good.

**Comment by AlekSi** [comment]
@alhridoy any news? Anything we could help you with?

**Comment by alhridoy** [comment]
> @alhridoy any news? Anything we could help you with?

Hi @AlekSi, I have created a PR for issue #3484 

Could you please review the PR and provide any feedback? I'm ready to make any necessary changes. Thank you!
