### ISSUE TITLE
Enable Mermaid diagrams in Docusaurus

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3528]
### What should be done?

https://docusaurus.io/docs/markdown-features/diagrams

So blog posts like https://blog.ferretdb.io/ferretdb-v1-10-production-ready-sqlite/ could be done with much less efforts.

### Where?

Both documentation and blog.

### Definition of Done

Plugin enabled for both documentation and blog websites.

**Comment by sid-js** [comment]
Hi, I'd be glad to work on this. Please assign this to me. @AlekSi

**Comment by sid-js** [comment]
@AlekSi I could not find the package.json file for the website to install  the mermaid plugin or is it with Docker ?. Could you please guide me ?

**Comment by AlekSi** [comment]
See:
* https://github.com/FerretDB/deps/commit/73ca9574661cc08525ea282487b38313b8e24c83
* https://github.com/FerretDB/deps/pkgs/container/docusaurus-docs/135541309?tag=2.4.3-2
* https://github.com/FerretDB/FerretDB/blob/main/build/deps/docusaurus-docs.Dockerfile
