### ISSUE TITLE
Enable linters to accept exclamation marks in headers

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#3564]
### What should be done?

We want to update the Markdown linter settings to accept exclamation marks in headers when formatting blogs. That way, a blog post can have headers like "Exciting times at FerretDB!"

See https://github.com/FerretDB/FerretDB/blob/main/build/.markdownlint.yml

### Where?

For FerretDB blog

### Definition of Done

- Linters accept trailing exclamation marks in headers

**Comment by chanon-mike** [comment]
I would like to work on this issue!
