### ISSUE TITLE
Generate queries with comments

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3573]
### What should be done?

When [`find` command](https://www.mongodb.com/docs/manual/reference/command/find/) is invoked with a `comment` argument, we pass its value to `Collection.Query`. It is not used after that.

We should use it in the generated SQL query. Instead of sending `SELECT _json …` to the database, we should send `SELECT /* <comment> */ _jsonb …`. We should also properly escape it: https://github.com/FerretDB/FerretDB/blob/1ea4ff41a8fe6a4f9fbbe6f898c41f336ab25254/internal/handlers/pg/pgdb/query.go#L177-L183

We already have tests for that. Let's check if they fail if we don't escape the comment: https://github.com/FerretDB/FerretDB/blob/1ea4ff41a8fe6a4f9fbbe6f898c41f336ab25254/integration/basic_test.go#L104-L116

### Where?

See references to this issue.

### Definition of Done

- both PostgreSQL and SQLite backends updated;
- handler updated;
- spot refactorings done.

**Comment by izruff** [comment]
Hi, I would like to work on this issue.

**Comment by AlekSi** [comment]
@izruff any news? Anything we could help you with?

**Comment by chumaumenze** [comment]
@AlekSi I opened a PR on this.
