### ISSUE TITLE
Improve `/debug` page

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3583]
### What should be done?

Our debug handler's page is really bare bones. Let's improve it a bit by adding descriptions of existing URLs.

### Where?

https://github.com/FerretDB/FerretDB/blob/4685aa7f8a73f6d593ab03511a721684672891e2/internal/util/debug/debug.go#L55-L65

### Definition of Done

- descriptions added;
- spot refactorings done.

**Comment by codenoid** [comment]
let me work on this
