### ISSUE TITLE
Implement `/debug/archive`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3584]
### What should be done?

We should implement a new debug handler at `/debug/archive` that would:
* self-scrape Prometheus metrics via `/debug/metrics`;
* take a binary memory pprof profile via `/debug/pprof/heap`;
* pack everything into a .zip archive and send it to the client.

We will add parameters to that handler and add more files to that archive in the future.

The file should be sent with a good content-disposition header and streamed to the client; for example, .zip header and Prometheus metrics could be sent before the memory profile is taken.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/util/debug/debug.go

### Definition of Done

- handler implemented;
- basic unit tests added;
- spot refactorings done.

**Comment by sushant102004** [comment]
I would like to work on this issue. Can I?

**Comment by sushant102004** [comment]
I'm new to open source, can you guide me a bit with this task?

**Comment by AlekSi** [comment]
It would be easier to guide you in an existing pull request with an initial attempt. See also https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md

**Comment by AlekSi** [comment]
@sushant102004 any news? Anything we could help you with?

**Comment by Aditya1404Sal** [comment]
I'm willing to work on this issue, please assign it to me !

**Comment by Aditya1404Sal** [comment]
I'm willing to work on this issue, please assign it to me !

**Comment by AlekSi** [comment]
Let's finish #3654 first

**Comment by sachinpuranik** [comment]
I shall work on it.
