### ISSUE TITLE
Test how `_id` set as a document works with `find` and `update`

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#3587]
### What should be done?

It's a valid case that `_id` might be set as a document, but currently, we don't have test cases that would use it.
The idea of this task is to add some cases and learn if FerretDB works correctly.

(Let's discuss the exact scope of this task - e.g. if we want to add tests for commands like `find` and `update` and test aggregation as well)

### Where?

https://github.com/FerretDB/FerretDB/tree/main/integration/shareddata, let's discuss what exactly we do.

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;
- ...

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/blob/9d3a3e1ed82ab22e842d36680c6418d7f366ba10/integration/query_test.go#L1046
