### ISSUE TITLE
`listIndexes` should return a sorted list

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3589]
### What should be done?

Currently, `listIndexes` command returns indexes in an unspecified order. It should return them sorted by name instead.

`Collection.ListIndexes` methods should also return results sorted by name. It will allow us to use a binary search on them.

We should also update our tests to compare sorted lists.

### Where?

See references to this issue.

### Definition of Done

- handler updated;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by codenoid** [comment]
I will work on this

**Comment by pvinoda** [comment]
I am looking into this.

**Comment by AlekSi** [comment]
@pvinoda It is already picked up
