### ISSUE TITLE
Generate collection UUIDs

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#3613]
We should generate and store [collection UUIDs](https://www.mongodb.com/docs/manual/core/databases-and-collections/#unique-identifiers). They should be visible in the [`listCollections` output](https://www.mongodb.com/docs/manual/reference/command/listCollections/#mongodb-data-listCollections.cursor).

**Comment by wazir-ahmed** [comment]
@AlekSi I'm interested in this issue. I can contribute to this.
