### ISSUE TITLE
Allow building without PostgreSQL or SQLite backend

### ISSUE THREAD

**Issue by med-ab** [FerretDB/FerretDB#3629]
We should allow building FerretDB without PostgreSQL and/or SQLite backend with `ferretdb_no_postgresql` and `ferretdb_no_sqlite` build tags. Both should be absent in official builds.

They should be documented at https://github.com/FerretDB/FerretDB/blob/main/build/version/version.go and tested at https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/registry/registry_test.go.

**Comment by AlekSi** [comment]
@med-ab what backends do you want to include/exclude and why?

**Comment by med-ab** [comment]
@AlekSi for me, i just need the sqlite backend, and i want to embed/bundle an sqlite-only ferretdb binary in one of my projects
i suppose such build will be more compact and practical for using ferretdb as a module in another project

**Comment by AlekSi** [comment]
I think we could add tags like `ferretdb_no_postgresql`, `ferretdb_no_sqlite` similar to how we already have `ferretdb_hana`.

Want to contribute that functionality?

**Comment by med-ab** [comment]
i'd love to contribute but i dont know go

**Comment by anunayasri** [comment]
@AlekSi I want to help with this issue. I am new to the codebase. I will need some time to get acquainted with the build process & code.

**Comment by AlekSi** [comment]
Build tags are documented there: https://github.com/FerretDB/FerretDB/blob/1f18df076dc2c7bc804e9358d3b933ad2f9992ec/build/version/version.go#L26

The build system is mostly in https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml

**Comment by AlekSi** [comment]
@anunayasri any news? Anything we could help you with?

**Comment by anunayasri** [comment]
@AlekSi I had been really busy and was not able to work on it. Apologies. Let me try it out this week. Will reach out to you for any clarifications.
