### ISSUE TITLE
Explicitly disallow duplicate keys in data documents

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#364]
BSON documents may have more than one field with the same name. However, that doesn't seem to be the feature that anyone uses. 

That's not true for command documents.

* https://www.mongodb.com/docs/manual/core/document/#field-names
* https://www.mongodb.com/docs/manual/reference/limits/#mongodb-does-not-support-duplicate-field-names

This is also not true for update documents. See #666.

DoD:
- [x] Let's explicitly disallow that in `types.Document` API, add tests and document that.
- [x] `ValidateData` for `types.Document` checks for duplicates and disallow them (check that d.keys doesn't contain duplicates).

**Comment by rumyantseva** [comment]
Implementation explanation:

As agreed with the team, quite a big refactoring was made. Now `types.Document`'s internal representation consists of a slice of fields where each field has a `string` field and `any` value.
That approach allows having duplicated keys in documents in principle.

However, `Document.ValidateData` checks that there are no duplicates.

Minor refactoring: `Document.Set`'s signature doesn't return `error `anymore, as, in fact, the implementation always returns `nil`. With that, there is no need to make the code more complicated (with all the checks for errors).
