### ISSUE TITLE
Add tracing to `envtool tests run`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3665]
### What should be done?

We should add OpenTelemetry traces to `envtool tests run`. That would give us better visibility into the way our parallel tests started, paused, and continued. Adding it to the tests itself is not enough because we call `t.Parallel()` before anything else.

Let's use one trace per top-level test and spans for subtests. Let's not create a span when the test is paused. And let's experiment with additional events to see what gives the best visualization.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

`envtool tests run` visualization is available, useful, and looks nice.

**Comment by hungaikev** [comment]
Can I pick this?
