### ISSUE TITLE
Test `panic` for `debugError`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3672]
### What should be done?

Original issue https://github.com/FerretDB/dance/issues/249

In FerretDB we have `debugError` command that allows us to see how everything would work if FerretDB panics.
Let's write a test for it.

As with the current `task run` configuration FerretDB panics and stops, we need to provide a way to run FerretDB in a non-debug mode (when panics are recovered and not thrown). 

TODO: 
- [ ] Add a `debugError` test that causes panic on the FerretDB side
- [ ] Fix FerretDB to provide the necessary configuration and setup CI to work this way

### Where?

https://github.com/FerretDB/FerretDB/blob/main/integration/basic_test.go

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment]
> As with the current task run configuration FerretDB panics and stops, we need to provide a way to run FerretDB in a non-debug mode (when panics are recovered and not thrown)
> Fix FerretDB to provide the necessary configuration and setup CI to work this way

That's not a job of FerretDB's CI / development environment. That should be in dance.

**Comment by noisersup** [comment]
@AlekSi btw, couldn't we create separate debug build tag, to not include `debugError` in the main build, or is it not necessary?
