### ISSUE TITLE
Make batch sizes configurable

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3708]
### What should be done?

https://github.com/FerretDB/FerretDB/blob/74009c036163fc63840dd6faaae27a084816ea35/internal/handlers/sqlite/msg_insert.go#L88
https://github.com/FerretDB/FerretDB/blob/74009c036163fc63840dd6faaae27a084816ea35/internal/backends/postgresql/collection.go#L133
https://github.com/FerretDB/FerretDB/blob/74009c036163fc63840dd6faaae27a084816ea35/internal/backends/sqlite/collection.go#L117

Currently, both handler-level and backends-level batch sizes are constants. That's because we don't want to consume too much memory on the FerretDB side and go over backend limits such as a maximum number or size of query parameters. We also don't know how to detect and/or auto-tune those parameters yet.

But we should allow changing those values via testing flags.

### Where?

See reference above.

### Definition of Done

- handler updated;
- all backends updated;
- benchmarks updated and run;
- spot refactorings done.

**Comment by 1garo** [comment]
Hello, I wanted to start contributing to Ferret, could I get this issue?

**Comment by AlekSi** [comment]
@1garo sure!

**Comment by 1garo** [comment]
Im setting up the environment following the contributing guide, in the steps `task env-up` and `task test`, the test runs but at some time it fails with `32.01s  signal: killed`.

I even tried `task test-unit` that is a shorter one and errors as well:

![image](https://github.com/FerretDB/FerretDB/assets/44412643/1d255964-b0b2-402f-82fd-878fc9199a31)

**Comment by AlekSi** [comment]
@1garo any news? Anything we could help you with?

**Comment by 1garo** [comment]
sorry, I got catch up in a middle of some trips, at the beginning I was having some problem having the dev env working but will try again and comeback if have some problem

**Comment by kropidlowsky** [comment]
Hi @AlekSi,

Can I work on it?
