### ISSUE TITLE
Return information about filter pushdown

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3761]
### What should be done?

`Collection.Query` should return a boolean field indicating if the requested filtering was fully applied by the backend. That field should be used by the `find` command implementation to skip filtering in the handler.

### Where?

See references to this issue.

### Definition of Done

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

#### Not in the scope

- changes in limit pushdowns;
- changes in `explain`.

**Comment by wazir-ahmed** [comment]
@AlekSi Hey, I'm interested in contributing to FerretDB. I can work on this issue.

**Comment by AlekSi** [comment]
@wazir-ahmed This issue is not ready to be picked up. Please choose something from this list: https://github.com/FerretDB/FerretDB/contribute
