### ISSUE TITLE
Support `speculativeAuthenticate`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3777]
### What should be done?

TBD

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by AlekSi** [comment]
There are open TODOs

**Comment by chilagrow** [comment]
Let me take a look for those todos
