### ISSUE TITLE
Support `SCRAM-SHA-256` authentication mechanism

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3784]
### What should be done?

We should implement `SCRAM-SHA-256` authentication mechanism. Credentials should be stored and validated on login. Enforcing authentication is in #1877.

The research prototype is in #3904, but its code should not be used. And we probably need to figure out integration testing first: both auth mechanisms (`PLAIN` and `SCRAM-SHA-256`) and new authentication enabled ~and disabled~.

### Where?

Handler.

### Definition of Done

- integration/compatibility tests added/updated;
- handler updated;
- spot refactorings done.

**Comment by b1ron** [comment]
Credentials should be stored when a user is created in https://github.com/FerretDB/FerretDB/blob/c8f8c6851e4a07ae5cc9297ae2a5019bcea6c7f1/internal/handler/msg_createuser.go#L34

**Comment by Neustradamus** [comment]
It is an important feature!

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/FerretDB/FerretDB/issues/2012
- https://github.com/FerretDB/FerretDB/issues/3784
- https://github.com/FerretDB/FerretDB/pull/3904
- https://github.com/FerretDB/FerretDB/issues/3938
- https://github.com/FerretDB/FerretDB/pull/3970
- https://github.com/FerretDB/FerretDB/pull/3989

**Comment by AlekSi** [comment]
@henvic There are TODO comments that refer to this issue

**Comment by henvic** [comment]
@AlekSi, closing it with #4086.
