### ISSUE TITLE
Support `--skip` for `envtool tests run`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3787]
### What should be done?

Go does not support negative matches in regular expressions, so, for example, running all query non-compat tests is quite hard.

We should add support for `go test`'s `-skip` flag so we could do something like
```
task test-integration-postgresql TEST_RUN='(?i)query' TEST_SKIP='(?i)compat'
```

Taskfile's `TEST_SKIP` variable should set `envtool tests run`'s `--skip` flag just like `TEST_RUN` sets `--run`.

### Where?

* https://github.com/FerretDB/FerretDB/blob/main/cmd/envtool/tests.go
* https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml

### Definition of Done

- `envtool` updated;
- tests added / updated.

**Comment by KrishnaSindhur** [comment]
i would like to work on this
