### ISSUE TITLE
Add tests for cursors

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#3818]
Add test for [this case](https://github.com/FerretDB/FerretDB/issues/3739#issuecomment-1833398536) [there](https://github.com/FerretDB/FerretDB/tree/main/integration/cursors).

Think of other cases we could add.

`maxTimeMS` / timeouts are in separate issues.

```[tasklist]
### Tasks
- [x] `AwaitData` tests
- [x] tailable=false, awaitData=true test
```

**Comment by AlekSi** [comment]
@noisersup https://github.com/FerretDB/FerretDB/pull/3823#issuecomment-1865692313
