### ISSUE TITLE
Use PBKDF2 for storing password for `PLAIN` authentication method

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3938]
### What should be done?

PBKDF2 is required for SCRAM anyway, so it does not make much sense to use Argon2 there.

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/FerretDB/FerretDB/issues/2012
- https://github.com/FerretDB/FerretDB/issues/3784
- https://github.com/FerretDB/FerretDB/pull/3904
- https://github.com/FerretDB/FerretDB/issues/3938
- https://github.com/FerretDB/FerretDB/pull/3970
- https://github.com/FerretDB/FerretDB/pull/3989
