### ISSUE TITLE
Use non-privileged `scratch` for production Docker images

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3992]
### What should be done?

Currently, our production Docker image uses `scratch` as a base and runs the FerretDB as a root. It turns out it is possible to run it as non-root user even with the `scratch` image: https://medium.com/@lizrice/non-privileged-containers-based-on-the-scratch-image-a80105d6d341. Let's do that.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/build/ferretdb/production.Dockerfile

### Definition of Done

The production Docker image runs FerretDB as non-root user, but still does not have `/bin/sh`, `/bin/bash`, etc.

**Comment by AlekSi** [comment]
@ahmethakanbesel sure, thank you!

**Comment by ahmethakanbesel** [comment]
Hi,

@AlekSi I can still work on that, but I don't know which part should be updated.

**Comment by AlekSi** [comment]
> with `chown` command

But there is no `chown` command in that container.

Does anyone actually use volumes with non-privileged `scratch` containers?
