### ISSUE TITLE
Use `slog` for logging

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4013]
### What should be done?

We should switch our logging to `log/slog` package:
* https://go.dev/blog/slog
* https://pkg.go.dev/log/slog

Among other things, that would make the usage of the embedded FerretDB package easier.

We probably should not remove all zap logging in this issue, but it should be hidden from the public interface of the `ferretdb` package.

That's a breaking change for v2.

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by sbshah97** [comment]
Would love to start contributing to this whenever this is marked as ready. I believe it'll be many small PRs
