### ISSUE TITLE
Make logger configurable in the embedded `ferretdb` package

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4014]
### What should be done?

`ferretdb.Config` struct should include `Logger *zap.Logger`. If that field is set, `ferretdb.New` should use that logger. Otherwise, it should initialize logging as we do it now, but only once (using `sync.Once`). 

### Where?

https://github.com/FerretDB/FerretDB/blob/main/ferretdb/ferretdb.go

### Definition of Done

- `ferretdb` package updated;
- tests / examples updated;
- documentation comments updated.

**Comment by fadyat** [comment]
@AlekSi hi, you can assign this to me! I'll do it this week

**Comment by fadyat** [comment]
Also, if there are other interesting and important tasks, I am ready to consider them :)
