### ISSUE TITLE
Add linter to check for "truncate" 

### ISSUE THREAD

**Issue by Fashander** [FerretDB/FerretDB#4048]
### What should be done?

We want to make sure that we don't publish a blog post without adding `<!--truncate-->` , so the whole post won't be displayed on homepage.

**Comment by sbshah97** [comment]
I'd love to take this up

**Comment by AlekSi** [comment]
@sbshah97 Thank you! The code is there: https://github.com/FerretDB/FerretDB/tree/main/tools/checkdocs

**Comment by sbshah97** [comment]
Can we give an example for this one? What is it that we have currently and what is it that we are expecting ?

From what I can see in the blog directory, we have a bunch of markdown files. What are we looking to do with that.

**Comment by sbshah97** [comment]
![Screenshot_20240208-173956.png](https://github.com/FerretDB/FerretDB/assets/16410361/1ec3a805-ea3b-4555-bf5c-e0ede8dac7e7)

Okay so from the looks of it, is it just a matter of doing a string search in the doc for that string and if that is not present we return false for that doc?

**Comment by sbshah97** [comment]
Okay so from the looks of it here's what I can do. 

1. Search the blog post for `<!--truncate-->` and if and wrote a method which returns a Boolean value. 
2. Call that method from the main method and in case it returns false mark an error and log the name of the file. 
3. Wrote a test for happy path and negative path as well.

**Comment by Fashander** [comment]
Yes that's correct. @sbshah97  All the blogposts md files must include the `<!--truncate-->`. That helps to cut off the remaining section of the blog from displaying on the homepage.

**Comment by AlekSi** [comment]
@sbshah97 any news? Anything we could help you with?

**Comment by sbshah97** [comment]
Hi apologies I had met with an accident and was in recovery due to some health issues
Will send this later today

**Comment by ptrfarkas** [comment]
@sbshah97 We are really sorry to hear about your accident - hope you are doing better now!
