### ISSUE TITLE
`checkswitch` should handle regular switches

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4082]
### What should be done?

Currently, it [handles](https://github.com/FerretDB/FerretDB/blob/5c76609b65c45d171e056df753ef71ac1b67fc58/tools/checkswitch/checkswitch.go#L89) only `*ast.TypeSwitchStmt`. It should also handle `*ast.SwitchStmt` to handle switches over [`bson.tag`](https://github.com/FerretDB/FerretDB/blob/5c76609b65c45d171e056df753ef71ac1b67fc58/internal/bson/tag.go).

### Where?

https://github.com/FerretDB/FerretDB/tree/main/tools/checkswitch

### Definition of Done

- tool updated;
- unit tests added/updated;
- [switch over `bson.tag`](https://github.com/FerretDB/FerretDB/blob/5c76609b65c45d171e056df753ef71ac1b67fc58/internal/bson/document.go#L188) is checked.

**Comment by kylediaz** [comment]
I'll give it a shot

**Comment by sbshah97** [comment]
Hey @kylediaz is this something you are working on or is this something I can take up ?

**Comment by AlekSi** [comment]
@sbshah97 feel free to grab it

**Comment by PaveenV** [comment]
I have taken this issue

**Comment by AlekSi** [comment]
@chilagrow Let's simplify it even more and merge `orderTypes` and `orderTags`. After all, we don't check if that's a `types` or `bson` package, etc. They are just strings as far as we are concerned.

**Comment by chilagrow** [comment]
> @chilagrow Let's simplify it even more and merge `orderTypes` and `orderTags`. After all, we don't check if that's a `types` or `bson` package, etc. They are just strings as far as we are concerned.

That's true, we can merge those. Let me work on them.

**Comment by chilagrow** [comment]
@AlekSi any reason `tag*` are different order from `types` package? `types` uses order from https://github.com/FerretDB/FerretDB/blob/main/internal/bson/bson.go#L15. I would use the same order for tags.
```
const (
	tagFloat64         = tag(0x01) // Float64
	tagString          = tag(0x02) // String
	tagDocument        = tag(0x03) // Document
	tagArray           = tag(0x04) // Array
	tagBinary          = tag(0x05) // Binary
```
in https://github.com/FerretDB/FerretDB/blob/main/internal/bson/tag.go#L22-L27

**Comment by AlekSi** [comment]
Tags are defined by the BSON spec: https://bsonspec.org/spec.html (`signed_byte(1)`, `signed_byte(2)`, etc). We can't change their values
