### ISSUE TITLE
Backend authentication is not bypassed correctly for SCRAM

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#4115]
### FerretDB version

v1.20.0-12-gb6fd73b4-dirty

### Backend

PostgreSQL

### Environment

dev

### What did you do?

See repro #4119.

### What did you expect to see?

A successful connection.

### What did you see instead?

```
MongoServerError: [msg_saslstart.go:184 handler.(*Handler).scramCredentialLookup] [collection.go:57 postgresql.(*collection).Query] [registry.go:279 metadata.(*Registry).DatabaseGetExisting] [registry.go:132 metadata.(*Registry).getPool] [pool.go:128 pool.(*Pool).Get] [opendb.go:95 pool.openDB] [opendb.go:110 pool.checkConnection] failed to connect to `host=127.0.0.1 user=byron database=ferretdb`: failed SASL auth (FATAL: password authentication failed for user "byron" (SQLSTATE 28P01))
```

**Comment by AlekSi** [comment]
Let's re-check with the current dev version

**Comment by b1ron** [comment]
This is no longer an issue with the current version. However, what's quite confusing is that is passes locally but _only_ once, and always fails on CI. It could be related to the fact that we authenticate using a new [client instance](https://github.com/FerretDB/FerretDB/pull/4119/files#diff-b956b11ca4b1fd8e11d6f48c9eb7d0613895f8709229b7efd35307600f0f86d9R42) in the shell. 

I need to debug the test further in #4119 to fully understand the problem.
