### ISSUE TITLE
`checkdocs` should check if linked issues are still open

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4171]
### What should be done?

https://github.com/FerretDB/FerretDB/blob/main/website/docs/reference/supported-commands.md?plain=1

We have a list of supported and unsupported commands and parameters in the file above. We should check if the linked issues are still open.

There is a code for checking if issue is open or closed in the `checkcomments` tool. We should refactor a shared part into a separate package and use it from both tools.

### Where?

* https://github.com/FerretDB/FerretDB/tree/main/tools/checkdocs
* https://github.com/FerretDB/FerretDB/tree/main/tools/checkcomments

### Definition of Done

- tool updated;
- unit tests added/updated;
- spot refactorings done.

Updating documentation itself is not in the scope.

**Comment by kropidlowsky** [comment]
Hi @AlekSi,

Can I work on this issue?

**Comment by AlekSi** [comment]
@kropidlowsky any news? Anything we could help you with?

**Comment by kropidlowsky** [comment]
@AlekSi sorry, I was busy recently.
I will push changes in couple of days (probably Friday). Hope it works.

Just to clarify:
Should we check ir only in this file?
https://github.com/FerretDB/FerretDB/blob/main/website/docs/reference/supported-commands.md?plain=1
