### ISSUE TITLE
Improve `validate` diagnostic command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#419]
### What should be done?

https://www.mongodb.com/docs/manual/reference/command/validate/

We should implement that command. It should not actually "validate" anything; all parameters other than `validate` with a collection name should be ignored. It should call `Collection.Stats` and return `nrecords` and `nIndexes`.

### Where?

* https://github.com/FerretDB/FerretDB/tree/main/internal/handlers/sqlite

### Definition of Done

- handler updated;
- integration/compatibility tests added/updated;
- user documentation updated.

**Comment by tarunannapareddy** [comment]
Hi @AlekSi can I pick up this improvement? I am a new contributor to this repository. But I have the open-source experience to pick this up.

**Comment by AlekSi** [comment]
@tarunannapareddy sure, thank you!

**Comment by tarunannapareddy** [comment]
@AlekSi I see that we are not writing UnitTest cases, but instead using Integration Tests. Can you suggest the best way to write test cases for the Validate? 

I do not see its return used for any bigger functions. Should I create a separate test file?

**Comment by AlekSi** [comment]
@tarunannapareddy Please add a test there: https://github.com/FerretDB/FerretDB/blob/main/integration/commands_diagnostic_test.go The test should call `validate` on the existing collection (created by `Setup`) and check `nrecords`, `nIndexes`, `ok` in the response. See a bit more about our tests there: https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md#running-tests (and below)

**Comment by AlekSi** [comment]
@tarunannapareddy any news? Anything we could help you with?
