### ISSUE TITLE
Move website dir in its own repo

### ISSUE THREAD

**Issue by rock59** [FerretDB/FerretDB#4210]
### What should be done?

website dir contains 520 unnececery files and fetching these files everytime is realy time-consuming ,storage-consuming and bandwidth-consuming .. It would be nice to move this dir in its own repo and make developers happy
Thanks

### Where?

website dir

### Definition of Done

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by AlekSi** [comment]
Well, we (developers) update documentation quite often, too, and making code changes and documentation changes in the same PR to a single repo is much easier.

What is your use case that is time-consuming, storage-consuming, and bandwidth-consuming? Are you cloning the entire repository with LFS each time you do something? What is that "something" and why?

**Comment by AlekSi** [comment]
The only thing that could be fixed I can think of should be fixed by e98188452d531817bc9fc3eca9383e60a720c03b
