### ISSUE TITLE
Add restart: on-failure to postgres container as well

### ISSUE THREAD

**Issue by pravi** [FerretDB/FerretDB#4296]
### What should be done?

In docker-compose.yml at https://docs.ferretdb.io/quickstart-guide/docker/ only ferretdb has restart: on-failure set, without postgres also having the same option set, ferretdb won't be able to connect to postgres on a server restart.

So please add this to the example docker-compose.yml

**Comment by Spoomer** [comment]
The website is also on [github](https://github.com/FerretDB/FerretDB/blob/main/website/docs/quickstart-guide/docker.md). If you want to you can create a PR with your recommended changes. So the team needs only to approve your PR! :)

**Comment by AlekSi** [comment]
> ferretdb won't be able to connect to postgres on a server restart

FerretDB should continuously try to reconnect to PostgreSQL if a connection is lost for any reason. Do you see some other behavior?

**Comment by pravi** [comment]
> > ferretdb won't be able to connect to postgres on a server restart
> 
> FerretDB should continuously try to reconnect to PostgreSQL if a connection is lost for any reason. Do you see some other behavior?

PostgreSQL container does not start when the host machine is restarted if using the docker-compose.yml given in docs. After adding this option, the container gets restarted on the host machine restart (ferretdb container already has this option).
