### ISSUE TITLE
Setup Otel exporter for FerretDB

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4345]
### What should be done?

We have some code that setups Otel exporter for integration tests and in envtool. We should refactor it and use it for setting Otel exporter in the FerretDB process itself. It should be configurable with `--test-XXX` flags.

We should not "fix" traces in this issue.

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by rumyantseva** [comment]
Something to take a look at: https://github.com/FerretDB/FerretDB/actions/runs/9755345749/job/26923979624?pr=4380

**Comment by AlekSi** [comment]
We should fix "traces export: string field contains invalid UTF-8" error
