### ISSUE TITLE
Check database name during authentication

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4392]
### What should be done?

Should we check user's database and command's `$db` or that's a part of authorization? If yes, we should do it. If not, we should remove references.

### Where?

See references to this issue.

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by chilagrow** [comment]
We should use the database name as part of authentication. For example, `db1.user` and `db2.user` are two different users despite the same name. If `db1.user` user should have an access to `db2` or other databases, it is assigned via _authorization roles_. https://www.mongodb.com/docs/manual/core/security-users/#authentication-database
