### ISSUE TITLE
Refactor "runnables"

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#4403]
### What should be done?

After #4306 and #4380, we should refactor things that run with context to be more consistent. For example:
* all should have constructors that could return initialization errors;
* all should have a `Run(ctx)` method that runs until `ctx` is canceled (with `ctxutil.WithDelay` inside is needed) that doesn't return errors (?).

### Where?

TBD

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by rumyantseva** [comment]
> all should have a Run(ctx) method that runs until ctx is canceled (with ctxutil.WithDelay inside is needed) that doesn't return errors (?).

What if an error happens during the running phase?
