### ISSUE TITLE
Improve comparison/sorting

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#457]
We should make our comparison and sorting of scalar values, arrays, and documents work the same way as in MongoDB (excluding values we don't support, like NaNs and nested arrays).

* #1449
* #1450
* #1521
* #1522
* #1023

Compat newly discovered issues:
* #1539 
* #1542
* #1569
* #1577 
* #1578
* #1607
* #1637

---

* [x] comparison of documents without reflection;
* [x] comparison of `[]`, `[null]` arrays;
* [x] comparison of arrays with a different element order;
* [x] comparison of arrays with a different element types;
* [x] comparison of documents with missing fields and nulls;
* [x] comparison of documents with different fields order;
* [x] comparison of documents with different fields types;
* [x] ascending and descending sorting:
  * [x] scalars;
  * [x] documents;
  * [x] arrays;
* [x] check that changes are ported to `findAndModify`.

We might have some of that tested already, but we should check that, add missing tests, and fix bugs.

**Comment by AlekSi** [comment]
The last point remains

**Comment by ribaraka** [comment]
Sure!

**Comment by AlekSi** [comment]
I agree. I think let's check scalar types first (both comparing and sorting by them), then documents, then arrays (that are most difficult)

**Comment by ribaraka** [comment]
OK!

**Comment by seeforschauer** [comment]
todo: check support in `findAndModify`

**Comment by AlekSi** [comment]
On hold for now, until we decide about edge cases and validation
