### ISSUE TITLE
Error `unable to open database file: out of memory (14)` when inserting documents in FerretDB with sqlite backend 

### ISSUE THREAD

**Issue by jkoenig134** [FerretDB/FerretDB#4571]
### FerretDB version

1.24.0

### Backend

sqlite

### Environment

- OS: Ubuntu In Github actions
- Deployment: Docker `ghcr.io/ferretdb/ferretdb:1.24.0`
- Deployment details: started via https://github.com/js-soft/ferretdb-github-action

### What did you do?

Running our database driver tests (latest mongodb nodejs driver) against FerretDB with sqlite enabled.

Under the hood ferretdb is started with the following command:
```
docker run --name ferretdb \
    -p 27017 \
    -e FERRETDB_HANDLER=sqlite \
    -e FERRETDB_SQLITE_URL=file:./ \
    -d ghcr.io/ferretdb/ferretdb:1.24.0
```

### What did you expect to see?

No error.

### What did you see instead?

The error 
```
MongoServerError: [msg_insert.go:168 handler.(*Handler).MsgInsert] [collection.go:105 sqlite.(*collection).InsertAll] [registry.go:256 metadata.(*Registry).collectionCreate] [registry.go:152 metadata.(*Registry).databaseGetOrCreate] [pool.go:202 pool.(*Pool).GetOrCreate] file:x4p0m5.sqlite?_pragma=busy_timeout%2810000%29&_pragma=journal_mode%28wal%29&_pragma=auto_vacuum%28none%29: [opendb.go:57 pool.openDB] unable to open database file: out of memory (14)
```
showing up

**Comment by AlekSi** [comment]
That's a permission problem: `ferretdb` binary runs as a regular user [since v1.22](https://github.com/FerretDB/FerretDB/blob/main/CHANGELOG.md#docker-images-changes), and it can't write to the current directory (that is `/` in this image).
The easiest fix is to remove `FERRETDB_SQLITE_URL` variable from the `docker run` command completely.

**Comment by jkoenig134** [comment]
Hey!

That's exactly [what I found out in the meantime](https://github.com/js-soft/ferretdb-github-action/pull/6). I don't know what changed, on your side to make is possible to remove `FERRETDB_SQLITE_URL`, because this existed to get rid of another bug.
