### ISSUE TITLE
support $first?

### ISSUE THREAD

**Issue by Nyx2022** [FerretDB/FerretDB#4618]
### What should be done?

can ferret support $first in mongo?

**Comment by chilagrow** [comment]
Hi @Nyx2022

Thanks for reaching out to us! We are working on the next major version (in private for now), that would support more aggregation operators using the PostgreSQL extension. We are tracking supported aggregation pipeline operators in #1467.

**Comment by ptrfarkas** [comment]
We are expecting to release FerretDB 2.0 this year.

**Comment by chilagrow** [comment]
In a few months
