### ISSUE TITLE
Support `$push` array update operator

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#503]
https://www.mongodb.com/docs/manual/reference/operator/update/push/

Not in scope:

- `$each` modifier - https://github.com/FerretDB/FerretDB/issues/828
- `$position` modifier - https://github.com/FerretDB/FerretDB/issues/829
- `$slice` modifier - https://github.com/FerretDB/FerretDB/issues/830
- `$sort` modifier - https://github.com/FerretDB/FerretDB/issues/831

DoD:
- [x] Nested arrays (arrays of arrays) are not in the scope. 
- [x] Arrays of objects are in the scope
- [x] update user doc (supported operators)

Compatibility tests for both valid results and errors are in the scope:
- [x] push to existent array field
- [x] push to non-existent field
- [x] push to a non-array field
- [x] negative test cases 
- [x] dot notation
- [x] combination of `$push` and other operators (check if it's possible)
- [x] think what other test cases might be needed

**Comment by rumyantseva** [comment]
Mark as not ready for now as we have separate issues for modifiers, I'll go through them and will update the current issue afterwards.
