### ISSUE TITLE
Merge `BigNumbersData` into `Scalars`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#558]
https://github.com/FerretDB/FerretDB/blob/1191d9bf62651091aaec5d43e9e8ed71f9e6fc60/integration/shareddata/bignumbers.go#L20-L25

We probably should merge those values into `shareddata.Scalars` as those values are interesting for all tests. But that would require us to fix those tests.

**Comment by AlphaB** [comment]
Can I take this one?

**Comment by AlekSi** [comment]
Sure thing!
