### ISSUE TITLE
Check rlimit on startup

### ISSUE THREAD

**Issue by dmitryrn** [FerretDB/FerretDB#562]
Integration tests fail on macOS where the default open file limit is too low. Go 1.19 will increase it automatically on both Linux and macOS (in a [right way](https://github.com/golang/go/commit/8427429c592588af8c49522c76b3e0e0e335d270)). Until that, let's terminate all FerretDB processes (FerretDB itself, envtool, tests, etc) if we don't have enough.

Let's create a new package at `internal/util/rlimit` that would use [`unix.Getrlimit`](https://pkg.go.dev/golang.org/x/sys/unix#Getrlimit) in `init()` function and panic if the soft limit for a number of open files is less than 4096. That package should be blank-imported from all main packages (`package main`). Using build tags, we should make this package do nothing on Windows.

Original report below.

---

Possibly not closing connections somewhere in the code.

### Reproduction:
1) `task env-pull`
2) `task env-up`
3) `task test`
  - test fails with `socket: too many open files`
  - `netstat -na | grep TIME_WAIT`, notice a lot of them

### Temporary fix:
On MacOS `ulimit -a` reports `file descriptors                256`.
Increasing the limit `ulimit -n 1024` fixes the issue, tests run successfully.

**Comment by AlekSi** [comment]
It seems that connections are closed correctly, it is just that we run too many tests in parallel.

Our options are:
* do nothing and wait for Go 1.19 which [will raise limits automatically](https://github.com/golang/go/issues/46279);
* raise limits ourselves (only in tests, or in both FerretDB and tests);
* fail early and explicitly if limits are too low (only in tests, or in both FerretDB and tests).

Thoughts?

**Comment by AlekSi** [comment]
Updated description.

**Comment by AlekSi** [comment]
@DoodgeMatvey any news?

**Comment by DoodgeMatvey** [comment]
> @DoodgeMatvey any news?

I tried to reproduce it but didn't get this one `test fails with socket: too many open files`
And this command shows nothing `netstat -na | grep TIME_WAIT`
