### ISSUE TITLE
Support `$min` field update operator

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#623]
We already have `$max` update operator. Let's implement `$min`: https://www.mongodb.com/docs/manual/reference/operator/update/min/

We should check if the existing `types.Array.Min` and `types.Array.Max` methods are being used and correct. If they are not, we should fix them or remove them.

If, during implementation, we encounter some minor apparent bugs with the existing `$max` operator, we should fix them. However, we should create a new issue if they are not small or clear.

Unlike usual, we should not do other spot refactoring in this issue. Instead, please add comments to this issue, noting all refactoring opportunities.

**Comment by DoodgeMatvey** [comment]
I would like to work on this one
