### ISSUE TITLE
Add `UnimplementedDot` and `UnsupportedDot` helpers

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#632]
We are not sure where dot notation for field names could be used and where it is not allowed.

* [x] Implement a new helper, `UnimplementedDot`, that returns an error if the given document field is present and contains a dot-separated path.
* [x] Implement another helper, `UnsupportedDot`, that returns an error if an argument contains a dot.
* [x] Do research where dot notation is supported by MongoDB and where it is not. Add `UnimplementedDot` (for cases where it is supported by MongoDB, but not by FerretDB yet) or `UnsupportedDot` (for cases where is not supported by MongoDB) calls where appropriate.
* [ ] Add integration tests for cases with `UnsupportedDot`.

If there is a better name for `UnsupportedDot`, let's use it.

**Comment by w84thesun** [comment]
### Find

#### Documents

Dot notation is allowed only at the top query level.
```
db.values.insertOne({"value": {"foo": {"bar": {"baz": {"qaz": "wsx"}}}}});
```
This one will return the document:
```
db.values.findOne({"value.foo": {"bar": {"baz": {"qaz": "wsx"}}}});
```

This one will return `null`:
```
db.values.findOne({"value.foo": {"bar": {"baz.qaz": "wsx"}}});
```

#### Arrays

```
db.values.insertOne({"value": [{"foo": [1]}]})
```

```
db.values.find({"value.0.foo":1})
```

```
 db.values.find({"value.0": {"foo":1})
```


### Update

```
db.values.insertOne({"value": {"foo": "bar"}})

db.values.updateOne({"value.foo": "bar"}, {"$set": {"value.edc": "rfv"}})

db.values.find()
[
  { _id: ObjectId("629751053be35ac96eab0085"), value: { edc: 'rfv' } },
  {
    _id: ObjectId("6297513b3be35ac96eab0086"),
    value: { foo: 'bar', edc: 'rfv' }
  }
]
```


```
db.values.insertOne({"value": {"foo": {"bar": {"baz": {"qaz": "wsx"}}}}});

db.values.updateOne({"value.foo": {"bar":{"baz.qaz": "wsx"}}}, {"$set": {"value.rfv":123}});
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 0,
  modifiedCount: 0,
  upsertedCount: 0
}

db.values.updateOne({"value.foo": {"bar":{"baz":{"qaz": "wsx"}}}}, {"$set": {"value.rfv":123}}) 
{
  acknowledged: true,
  insertedId: null,
  matchedCount: 1,
  modifiedCount: 1,
  upsertedCount: 0
}

{
    _id: ObjectId("629756273be35ac96eab0087"),
    value: {
      foo: { bar: { baz: { qaz: 'wsx' } } },
      rfv: 123
    }
}
```

### Delete

The query for the delete command works in the same way as with the find command.


### What's not on scope.

At the moment there is no support for projection operators `$`, `$slice`, `$elemMatch`, `$meta`.

For update operations there is no support for `$`, `$[]`, `$[identifier`.

**Comment by w84thesun** [comment]
Dot notation is fully supported for querying documents. No helpers are needed.
