### ISSUE TITLE
Add `Min` and `Max` methods to `types.Array`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#637]
Those methods should return minimum and maximum values in an array as defined by `CompareOrder` function. They should panic for nil or empty array – the caller must check that array is not empty before calling those methods.

**Comment by AlekSi** [comment]
After #607

**Comment by ribaraka** [comment]
Got a few questions:
1. I have not seen that `CompareOrder` function  has defined a minimum and maximum values in an array. Could you please show me this information?
2. Why does an array have certain maximum values at all?
3.  Why panic if an array empty or nil? `CompareOrder` is for sorting; sorting works for empty and nil array.
Thank you!

**Comment by ribaraka** [comment]
@AlekSi, what if `Min` or `Max` value is another array, we just return this subarray ?
