### ISSUE TITLE
Incorrect test for `$mod`

### ISSUE THREAD

**Issue by fenogentov** [FerretDB/FerretDB#638]
https://github.com/FerretDB/FerretDB/blob/6f2ec6e8df6bbc42ff14b6a7c5014b9a740d2e7f/integration/query_evaluation_test.go#L278

**Comment by AlekSi** [comment]
What is wrong with it?

**Comment by fenogentov** [comment]
missing "value"

https://github.com/FerretDB/FerretDB/pull/645

`
- filter: bson.D{{"$mod", bson.A{math.Copysign(0, -1), 1}}},
+ filter: bson.D{{"value", bson.D{{"$mod", bson.A{math.Copysign(0, -1), 1}}}}},
`
