### ISSUE TITLE
Error on `nil` filter 

### ISSUE THREAD

**Issue by seeforschauer** [FerretDB/FerretDB#649]
The test case parameters:
```go
   "nil-filter": {
        filter:      nil,
        setOnInsert: bson.D{},
    },
```

Test it with the code:
```go
opts := options.Update().SetUpsert(true)
	var res *mongo.UpdateResult
	res, err = collection.UpdateOne(ctx, tc.filter, bson.D{{"$setOnInsert", tc.setOnInsert}}, opts)
	if tc.err != nil {
		if !AssertEqualWriteError(t, tc.err, tc.alt, err) {
			t.Logf("%[1]T %[1]v", err)
			t.FailNow()
		}
		return
	}
```

Error from MongoDB is `mongo.MarshalError`. 
This task is to start to return MarshalError.

**Comment by AlekSi** [comment]
That error comes from the driver, not from the MongoDB itself. From https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Collection.UpdateOne:

> The filter parameter must be a document containing query operators and can be used to select the document to be updated. It cannot be nil.
