### ISSUE TITLE
Explicitly do not support fields with a dot in data documents

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#659]
```
{"foo.bar": 42.13}
```

That's not a valid document in FerretDB, it can't be inserted, $inc'ed, etc

- [x] Update `Known differences` paragraph at README.md
- [x] Add checks to validation function
- [x] Write unit tests for validation function
- [x] Add tests for insert, update (replacement documents) - might be in ferretdb source code, might need to be removed
- [ ] Dance tests need to be updated (see the place where `$` is tested)

**Comment by w84thesun** [comment]
How we should process queries with dotted fields? MongoDB support such queries and:
```
db.test.findOne({"value.foo.bar": {"baz.quz": 1})
```
Where `"value.foo.bar"` would be dot notation but `"baz.quz"` is dotted field.

**Comment by AlekSi** [comment]
> How we should process queries with dotted fields? 

We reject them during validation
