### ISSUE TITLE
Unify `update` tests

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#674]
We should unify our update tests to unblock the implementation of more update operators.

* [ ] `update_test.go` tests should be split into four files:
* `update_field_test.go` for https://www.mongodb.com/docs/manual/reference/operator/update-field/ operators;
* `update_array_test.go` for https://www.mongodb.com/docs/manual/reference/operator/update-array/ operators;
* `update_bitwise_test.go` the sole https://www.mongodb.com/docs/manual/reference/operator/update-bitwise/ operator;
* and `update_test.go` may remain for some basic tests.
* [ ] Test names should have a file name as a prefix. For example, `TestUpdateFieldSet`.
* [ ] Tests should use shared data. They may insert test-specifical data if needed, but that should be an exception.
* [ ] Tests should generally look similar to query tests and each other.

**Comment by seeforschauer** [comment]
>  Tests should generally look similar to query tests and each other.

The similarity is not defined specifically.

**Comment by seeforschauer** [comment]
> update_array_test.go for https://www.mongodb.com/docs/manual/reference/operator/update-array/ operators;

There are no array operators at the moment. WDYM?
