### ISSUE TITLE
Make log level configurable

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#680]
We should add a new flag `-log-level` that would allow us to set the logging level.

Possible values should be [`zapcore`](https://pkg.go.dev/go.uber.org/zap/zapcore#Level)'s `DebugLevel`, `InfoLevel`, `WarnLevel`, and `ErrorLevel`. The usage text should show them all just like we do for `-handler` flag.

Additionally, only debug level should enable zap's [development mode](https://pkg.go.dev/go.uber.org/zap#Config).

**Comment by w84thesun** [comment]
Maybe just `Debug`, `Info`, `Warn`, and `Error`, without the `Level` part. WDYT?

**Comment by AlekSi** [comment]
Yes, sure. I mean, we should use `DebugLevel.String()`, etc and the [`ParseLevel`](https://pkg.go.dev/go.uber.org/zap/zapcore#ParseLevel) function.
