### ISSUE TITLE
Improve `tjson` package

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#683]
Higher prio:
* [x] #899
* [x] #900
* [x] #912
* [x] #907
* [x] #906
* [x] #905
* [x] #1007
* [x] #911
* [x] #917
* [x] #943

**Comment by rumyantseva** [comment]
### Support for `null` values

- [] Add support for `null` values for the Tigris handler.  Cases to cover:
    - [] Insert, upsert, update
    - [] Queries: <tbd>
- [] Add tests. Try to reuse existing null-related tests and shared data.

This is how `null` values work in Tigris:
- Primary key fields can't be set as `null`.
- Any other field can be explicitly set as `null` in the JSON payload.
- If the field is set as `null` it will be stored as `null`.
- If the field is not set in the JSON payload, it is not stored in Tigris.

**Comment by rumyantseva** [comment]
### Support arrays

- [ ] Add tests to work with arrays. Try to reuse existing array-related tests and shared data. Cases to cover:
  - [ ] Insert, upsert, update
  - [ ] Queries - array operations
- [ ] Based on the failed tests, add support for arrays for the Tigris handler.

In Tigris arrays are defined [according to the schema](https://docs.tigrisdata.com/overview/schema#array-1). All values of the array have the same type defined in the scema.

**Comment by rumyantseva** [comment]
### Enable fuzzing to cover more Tigris cases

**Comment by rumyantseva** [comment]
### `fjson` and `tjson`

- [ ] Move `fjson` data type's test cases to a directory that could be share between `fjson` and `tjson`. 
- [ ] Extend `fjson` data type's test cases to support both `fjson` and `tjson` - add a new field that would contain expected serialized result for `tjson`. 
- [ ] Reuse `fjson`'s testing approach - `test`, `fuzz`, `benchmark` in `tjson`. Probably, with some interfaces. Ideally, reuse common logic (same interface, different implementation for fjson and tjson).

**Comment by rumyantseva** [comment]
### Fix schema comparison

**Comment by rumyantseva** [comment]
### Tigris: Add support for all scalar values

**Comment by rumyantseva** [comment]
### Tigris: Add package documentation for mapping

**Comment by rumyantseva** [comment]
@AlekSi all the subtasks are created as issues. Please take another look to check that all the necessary things are covered.
