### ISSUE TITLE
`whatsmyuri` command is broken

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#692]
That command has been broken since #534, when we made Handler a shared object between all connections. Let's keep it shared but pass connection information to the handler method via context. That's a temporary solution until we understand what exactly we need in other handler methods.

* [x] Update documentation for `Handler` type to clarify that handler is shared between all connections.
* [x] Add `ConnInfo` struct to `clientconn` package with a peer address as a string.
* [x] Add `withConnInfo(ctx context.Context, connInfo *ConnInfo) context.Context` function that returns derived context with connection information set (using WithValue under the hood). Use that function in `route`.
* [x] Add `GetConnInfo(ctx context.Context) *ConnInfo` function that would return that information.
* [x] Move `MsgWhatsMyURI` to `handlers/common`, use connection information to implement that function.
* [x] Use that function in all three handlers. Update [integration test](https://github.com/FerretDB/FerretDB/blob/ddaa0d1ad65cc7b879643194e25b7ee39c8e9de5/integration/commands_administration_test.go#L796) to use two connections with different `you` responses. Ports will be different.

**Comment by rumyantseva** [comment]
@AlekSi a couple of questions for clarity:
-  Docs for `Handler` type - do you mean [handlers.Interface](https://github.com/FerretDB/FerretDB/blob/88d0ae6abdcb26b11474c7a424772baf6bc3a6c3/internal/handlers/handlers.go#L32) or all the implementations? Or both interface and implementations?
- `conn` package - do you mean [clientconn](https://github.com/FerretDB/FerretDB/blob/fd597b180973829ca177fa571285a206a7cdd20a/internal/clientconn/conn.go)?
