### ISSUE TITLE
Explicitly disallow field names with `$`

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#693]
DoD:

- [x] Add basic validation functions and calls mentioned in #871 
- [x] Disallow usage of `$` in data documents (but it is still allowed to use this symbol in command documents)
- [x] Add tests to check validation functions
- [ ] Finish FerretDB/dance#211
- [x] Create a separate issue for Tigris to have `tigrisdb` similar to `pgdb` 
       - #1248

**Comment by w84thesun** [comment]
Refs #643

**Comment by AlekSi** [comment]
Redefined "scope changed" to include both business (what should be done?) and technical (how it should be done?) scopes
