### ISSUE TITLE
Listen on a Unix domain socket

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#737]
There should be a way to configure FerretDB to listen and accept connections on the UNIX domain socket.

Let's add a flag `--listen-socket` that would contain a single file path to a UNIX socket FerretDB will listen on. Empty value (the default) will disable it. Both `--listen-addr` and `--listen-socket` could be given; in that case, FerretDB would listen on both.

* Integration test is in the scope.
* Embedded usage (public `ferretdb` package) is in the scope.

**Comment by Dragomir-Ivanov** [comment]
Hello There,
It also work if you make a call to FerretDB API, something like `GetEmbedAddress()`, and it will return a string containing random(free) listen socket. Then this string could be provided to MongoDB Driver.
