### ISSUE TITLE
Implement `MsgCreate` for Tigris

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#772]
Return an error if schema validator is provided for `pg` handler.
Accept Tigris-specific JSON schema as a validator for `tigris` handler.
Create a collection with that schema.

Both `tigrisdb` and a regular integration tests should be added; no compatibility test.

**Comment by rumyantseva** [comment]
@AlekSi for `pg` currently `validator` is in the list of unimplemented fields, is unimplemented enough as "return an error", or should it be some other error?
