### ISSUE TITLE
Implement `MsgFindAndModify` for Tigris

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#775]
We assume that we have `tigrisdb` package in some form already.

It should be as simple as copying and pasting PostgreSQL handler's code and tweaking it. We should also change `tigrisdb` to look more similar to `pgdb`, with one big exception of QueryDocuments – we should not use channel-based API for that one.

New compatibility tests for `findAndModify` are in the scope.

**Comment by AlekSi** [comment]
Currently, it looks like an XL tasks, it should be split

**Comment by rumyantseva** [comment]
Change size to S as only tests are left

**Comment by rumyantseva** [comment]
The PR is ready for review. Feel free to suggest and merge improvements if any.
