### ISSUE TITLE
Add integration tests for Tigris

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#786]
We should have good integration tests for Tigris. We can't re-use our existing tests for the PostgreSQL handler because they use different value types in the same field. We also don't want to duplicate all our tests. What can we do?

**Comment by rumyantseva** [comment]
I guess, one option would be to use "real" integration or "functional" tests, i.e. to come up with the same test set for all the backends and call it through mongodriver, not through calling exact handlers.

Like a "black-box" testing of FerretDB.
