### ISSUE TITLE
Rework database and collection creation for Tigris

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#787]
Currently, we try to create databases and collections in too many places. We should clean that up.

Expand `tigrisdb`. Port `CreateTableIfNotExist` and `insert` from `pg` handler. Use them where needed.

Remove our own "filter" from tigrisdb.

**Comment by rumyantseva** [comment]
+ same for database (see https://github.com/FerretDB/FerretDB/pull/887)

**Comment by rumyantseva** [comment]
@AlekSi case: a few documents are inserted ("insert many") into a collection that didn't exist. The schema for the collection is created based on the first document. The second document doesn't match the schema. What should be returned in such a case? - In fact, we created a collection and inserted one doc, but then the second doc insertion failed.
