### ISSUE TITLE
Update Tigris to the latest version

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#800]
* [x] Update Tigris and client to the latest version
* [x] Ensure that our smoke test still works.
* [x] Ensure that it works on macOS.
* [x] Check if it works on Windows.

**Comment by AlekSi** [comment]
@w84thesun Please check that the current `main` works on Windows: environment starts with Tigris, all tests pass

**Comment by w84thesun** [comment]
Everything works fine on Windows.
