### ISSUE TITLE
Support `$addToSet` array update operator

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#825]
https://www.mongodb.com/docs/manual/reference/operator/update/addToSet/

DoD - to cover:

- [x] existing field - new value non-array, new value array
- [x] existing field - existing value
- [x] non-existent field - new value non-array, new value array
- [ ] invalid field name
- [x] dot notation

Not in scope:
- `$each` - https://github.com/FerretDB/FerretDB/issues/828

**Comment by wreiske** [comment]
https://github.com/meteor/meteor/discussions/12150

I'm working on testing FerretDB for use with Meteor. I ran into $addToSet not being supported today.
