### ISSUE TITLE
Support `$pull` array update operator

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#826]
https://www.mongodb.com/docs/manual/reference/operator/update/pull/

Only basic support is in scope, support of operators inside `$pull` (e.g. `{ $pull: { v: { $gte: 42 } } }`) is in a separate issue - https://github.com/FerretDB/FerretDB/issues/1765.

DoD:
- [x] Nested arrays (arrays of arrays) are not in the scope. 
- [x] Arrays of objects are in the scope
- [ ] <del>update user doc (supported operators) </del>

Compatibility tests for both valid results and errors are in the scope:
- [x] pull from existent array field
- [x] pull from non-existent field
- [x] pull from a non-array field
- [ ] negative test cases 
- [x] dot notation
- [x] null values in an array
- [x] arrays with duplicate values (should all duplicates be removed by `$pull` or only the first one?)
- [ ] think what other test cases might be needed

**Comment by rumyantseva** [comment]
@rumyantseva todo: split the issue - 1) pull + dot notaion; 2) support filter operators.

**Comment by rumyantseva** [comment]
I removed the size from this issue as we haven't planned it for the Sprint.
