### ISSUE TITLE
Improve data validation, document unsupported edge-cases

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#871]
FerretDB should be more strict with the values it stores and commands it accepts. For example, it is currently possible to store NaN and ±infinity IEEE 754 values, but that will cause problems down the road with indexing, other backends, etc. We should forbid NaNs in both data and commands. We should forbid infinity values but allow them in queries as conditions like `x < y` should still work when `y` is infinity.

Those unsupported edge cases should return clear errors and be covered with tests and documented.

## What should be done?

This is an epic to collect validation-related issues. 

We need to add some basic validation methods for `types.Document`. 
We can add ~two~ one method:
- `ValidateData` to validate documents that represent data (called before data are inserted/updated in the DB).
- ~`ValidateCmd` to validate documents that represent commands.~ – that should be a function in the `wire` package.

This method should be called from handlers' implementations (for both Tigris and Postgres).

---

- #898
- #693 
- #659 
- #1150 
- #364 
- #1235
- #1151 
- #1000 
- #1305
- #1263

**Comment by rumyantseva** [comment]
@AlekSi how should `x < y` work if `y` is infinity? If we receive such condition, should we just exclude it from the query? like, for each x != infinity it's true that x < y.

**Comment by AlekSi** [comment]
Infinity is always signed in IEEE 754:
* x > -Infinity ∀𝑥∈R
* x < +Infinity ∀𝑥∈R

But the current issue description is not ready yet; it is just an idea. Maybe we will completely forbid ±Infinity too.
