### ISSUE TITLE
Support count function

### ISSUE THREAD

**Issue by thuan1412** [FerretDB/FerretDB#89]
The project currently does not support the `count` function.

![image](https://user-images.githubusercontent.com/36019052/143276633-8759ead0-d36f-4df2-9b55-c02a16fc71aa.png)

**Comment by OpenSauce** [comment]
I can pick this up, unless you want to give it a try @thuan1412 ?

**Comment by thuan1412** [comment]
@OpenSauce yeh, I gonna try to resolve this issue this weekend. I think it's a good opportunity for me to have much understanding of the project.

**Comment by dstpierre** [comment]
Hey same here, I'm trying to test mangodb for my project and I'm getting this:

`(NotImplemented) unhandled msg "aggregate"`

It's also for a "Count" command, but not receiving same error msg as above.

This is very promising project and I'd be happy to help.

**Comment by dstpierre** [comment]
This is the line generating the `aggregate` error, it's a count. Maybe the Go driver of Mongo uses `aggregate` in its internal:

```go
count, err := db.Collection("accounts").CountDocuments(ctx, bson.M{"email": email})
```
