### ISSUE TITLE
Offer a better design for fetching documents (iterator)

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#898]
Currently, we use a channel [to fetch documents](https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/pg/pgdb/query_documents.go).

Such an approach doesn't look safe and handy: the caller of the channel needs to drain the channel (so that the goroutine that writes to the channel can return). Inaccuracy in that might cause leaking goroutines, a data race, or even a panic. 

We need to come up with a better and safer design when the caller doesn't need to drain the channel. A potential solution is to implement an iterator design pattern. 

The issue number of this issue is used in code `TODO`s.

---

Let's use interface from golang/go#54245.

* [ ] Add interface with one method to get the next document (with `Close`) in a separe package.
* [ ] Implement that interface for pgdb, use it in pg handler.
* [ ] Implement that interface for tigrisdb, use it in Tigris handler (in another PR).

**Comment by AlekSi** [comment]
We probably could use the interface from https://github.com/golang/go/discussions/54245
