### ISSUE TITLE
`tjson`: Enable fuzzing in CI

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#918]
This task is a part of #683 epic.
This task should be taken after #899 is done.

As the result of #899, we should have some fuzzing for `tjson` tests. Let's research if it's reasonable to enable it on CI. (Let's enable it and see what happens).

**Comment by rumyantseva** [comment]
@AlekSi I need your help to add some details to this task's description. I guess, it's something related to this https://github.com/FerretDB/FerretDB/blob/main/.github/workflows/go.yml#L154 place?..

**Comment by AlekSi** [comment]
I think it is fine to keep that task in the icebox for now
