### ISSUE TITLE
Implement `distinct` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#945]
https://www.mongodb.com/docs/manual/reference/command/distinct/

In the scope:
* `distinct`, `key`, `query`, `comment` arguments;
* compatibility tests, etc (as usual).

Not in the scope:
* query statistics, query plan.

DoD:
- [x] usual things: both pg and tigris are in the scope, compat tests are in the scope, check various data types with compat tests, update docs about supported commands - https://docs.ferretdb.io/reference/supported_commands/
- [x] test an example where `key` uses dot notation

**Comment by ADawesomeguy** [comment]
I'd be interested in implementing this if possible, are there any examples of other commands implemented?

**Comment by AlekSi** [comment]
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/pg/msg_count.go is probably the most similar

**Comment by rumyantseva** [comment]
So, are both Postgres and Tigris in scope as usual?

**Comment by rumyantseva** [comment]
I guess collation is not in the scope too.

**Comment by rumyantseva** [comment]
@AlekSi please answer the questions above ^

**Comment by AlekSi** [comment]
> So, are both Postgres and Tigris in scope as usual?

Yes, as usual

> I guess collation is not in the scope too

It would be weird to start supporting collations (#10) in this issue

> One more question: how should results be sorted if we in the given field we have data of different types

Compatibility tests should pass
